// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project a6e0de7208a6e203 "VeeBran", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Secondary' // Variant
 * label?: string // Label
}} Props

 */
import { className, css, fonts } from "../chunks/chunk-A53DKFKD.js";
import { routes } from "../chunks/chunk-ID6ACFOJ.js";

// virtual:element/label
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/9nuQmgdODXKp1tEq44aF/G2Ic0h0koMSDoGIKNY3i/OzxnYEwmt.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["alzYs6g9o", "TkMkDxI3S"];
var serializationHash = "framer-NiFTu";
var variantClassNames = {
	alzYs6g9o: "framer-v-91jkw2",
	TkMkDxI3S: "framer-v-15tk01k",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	duration: 0,
	type: "tween",
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "alzYs6g9o",
	Secondary: "TkMkDxI3S",
};
var getProps = ({ height, id, label, width, ...props }) => {
	return {
		...props,
		tWUpRXPNf: label ?? props.tWUpRXPNf ?? "Label Name",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "alzYs6g9o",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		tWUpRXPNf,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "alzYs6g9o",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-91jkw2",
							className2,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"alzYs6g9o"}
						ref={refBinding}
						style={{
							background:
								"linear-gradient(180deg, var(--token-4d6fb0aa-347b-4d07-918a-f12b70b08ad3, rgb(33, 33, 33)) 0%, rgba(35, 35, 35, 0.2) 100%)",
							borderBottomLeftRadius: 33,
							borderBottomRightRadius: 33,
							borderTopLeftRadius: 33,
							borderTopRightRadius: 33,
							...style,
						}}
						{...addPropertyOverrides(
							{
								TkMkDxI3S: {
									"data-framer-name": "Secondary",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-sceg6s"}
							data-framer-name={"Label"}
							layoutDependency={layoutDependency}
							layoutId={"f3IyA851M"}
							style={{
								backgroundColor:
									"var(--token-c311f7eb-2396-4f7f-8edd-f790b3c42ec3, rgb(5, 5, 5))",
								borderBottomLeftRadius: 33,
								borderBottomRightRadius: 33,
								borderTopLeftRadius: 33,
								borderTopRightRadius: 33,
							}}
							transformTemplate={transformTemplate1}
							variants={{
								TkMkDxI3S: {
									backgroundColor:
										"var(--token-70b4ad58-9042-4a72-8dea-68d8a9efadf0, rgb(13, 13, 13))",
								},
							}}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-l2l7a4"}
								data-framer-name={"label"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"KX3Y0ZpCv"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-d3f304a1-8f3c-4236-99dd-3a229afb5214, rgb(239, 139, 46))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={tWUpRXPNf}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-bkongl"}
										data-styles-preset={"IEx8UeCkP"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-d3f304a1-8f3c-4236-99dd-3a229afb5214, rgb(239, 139, 46)))",
										}}
									>
										{"Label Name"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-NiFTu.framer-skgalw, .framer-NiFTu .framer-skgalw { display: block; }",
	".framer-NiFTu.framer-91jkw2 { gap: 0px; height: 31px; overflow: visible; position: relative; width: 117px; }",
	".framer-NiFTu .framer-sceg6s { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 7px; height: min-content; justify-content: flex-start; left: 50%; overflow: visible; padding: 9px 20px 9px 20px; position: absolute; top: 52%; width: min-content; }",
	".framer-NiFTu .framer-l2l7a4 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	...css,
];
var FramerOzxnYEwmt = withCSS(Component, css2, "framer-NiFTu");
var stdin_default = FramerOzxnYEwmt;
FramerOzxnYEwmt.displayName = "Element/Label";
FramerOzxnYEwmt.defaultProps = {
	height: 31,
	width: 117,
};
addPropertyControls(FramerOzxnYEwmt, {
	variant: {
		options: ["alzYs6g9o", "TkMkDxI3S"],
		optionTitles: ["Default", "Secondary"],
		title: "Variant",
		type: ControlType.Enum,
	},
	tWUpRXPNf: {
		defaultValue: "Label Name",
		displayTextArea: false,
		title: "Label",
		type: ControlType.String,
	},
});
addFonts(
	FramerOzxnYEwmt,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:element/label
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "alzYs6g9o",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a6e0de7208a6e203a13a02c0c2342fdcb8c3548bcbc64ba40bb03307875e0fbf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders LabelFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a6e0de7208a6e203a13a02c0c2342fdcb8c3548bcbc64ba40bb03307875e0fbf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var label_default = ComponentWithRoot;
export { label_default as default };
