// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project a6e0de7208a6e203 "VeeBran", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import { stdin_default } from "../chunks/chunk-LFCN3FO3.js";
import { Physics } from "../chunks/chunk-GD26GQNW.js";
import { routes } from "../chunks/chunk-ID6ACFOJ.js";

// virtual:element/physics-label
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/rSZxANHZtBIl4XPqLO1a/gFwnz027dCX3TAq1EBgZ/ugcb8GbnV.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var CardFeatureSmallFonts = getFonts(stdin_default);
var PhysicsFonts = getFonts(Physics);
var cycleOrder = ["ofM_VReS1", "UoEClOBvu", "cq2V5N45S"];
var serializationHash = "framer-UUHgv";
var variantClassNames = {
	cq2V5N45S: "framer-v-wvlqnp",
	ofM_VReS1: "framer-v-m8i9ls",
	UoEClOBvu: "framer-v-1rra1ou",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var addImageAlt = (image, alt) => {
	if (!image || typeof image !== "object") {
		return;
	}
	return {
		...image,
		alt,
	};
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "ofM_VReS1",
	Phone: "cq2V5N45S",
	Tablet: "UoEClOBvu",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "ofM_VReS1",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "ofM_VReS1",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (baseVariant === "cq2V5N45S") return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "UoEClOBvu") return true;
		return false;
	};
	const isDisplayed2 = () => {
		if (["UoEClOBvu", "cq2V5N45S"].includes(baseVariant)) return false;
		return true;
	};
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-m8i9ls",
							className,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"ofM_VReS1"}
						ref={ref ?? ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								cq2V5N45S: {
									"data-framer-name": "Phone",
								},
								UoEClOBvu: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<ComponentViewportProvider>
								<motion.div
									className={"framer-650bh0-container"}
									layoutDependency={layoutDependency}
									layoutId={"k9Uu2MYJL-container"}
								>
									<Physics
										densityOptions={{
											density: 0.1,
											enable: true,
										}}
										friction={{
											friction: 0.1,
											frictionAir: 0.01,
										}}
										gravX={0}
										gravY={0.5}
										height={"100%"}
										id={"k9Uu2MYJL"}
										layoutId={"k9Uu2MYJL"}
										mouseOptions={{
											angularStiffness: 0,
											enable: true,
											stiffness: 0.5,
										}}
										style={{
											height: "100%",
											width: "100%",
										}}
										wallOptions={{
											bottom: true,
											left: true,
											right: true,
											top: false,
										}}
										width={"100%"}
									>
										<ComponentViewportProvider height={66} width={"205.5px"}>
											<motion.div
												className={"framer-ol76uj-container"}
												data-framer-name={"Feature Label 1"}
												layoutDependency={layoutDependency}
												layoutId={"D9GcvUS7y-container"}
												name={"Feature Label 1"}
											>
												{_jsx(stdin_default, {
													height: "100%",
													Hqt2h3vZ2: "Virtual Assistants",
													id: "D9GcvUS7y",
													J1HJ1g2nv: addImageAlt(
														{
															src: "https://framerusercontent.com/images/WAStXM67xiG29TOK2TCCxlKOmM.svg",
														},
														"",
													),
													layoutId: "D9GcvUS7y",
													name: "Feature Label 1",
													variant: "k07xlIvCg",
													width: "100%",
												})}
											</motion.div>
										</ComponentViewportProvider>
										<ComponentViewportProvider height={66} width={"223px"}>
											<motion.div
												className={"framer-1qbgjdp-container"}
												data-framer-name={"Feature Label 2"}
												layoutDependency={layoutDependency}
												layoutId={"pRWIbEoI5-container"}
												name={"Feature Label 2"}
											>
												{_jsx(stdin_default, {
													height: "100%",
													Hqt2h3vZ2: "AI-Driven Solutions",
													id: "pRWIbEoI5",
													J1HJ1g2nv: addImageAlt(
														{
															src: "https://framerusercontent.com/images/sPmibGCLfmQVJHX0tlJqMt1ZOb8.svg",
														},
														"",
													),
													layoutId: "pRWIbEoI5",
													name: "Feature Label 2",
													variant: "k07xlIvCg",
													width: "100%",
												})}
											</motion.div>
										</ComponentViewportProvider>
										<ComponentViewportProvider height={66} width={"244.5px"}>
											<motion.div
												className={"framer-1sgyqy6-container"}
												data-framer-name={"Feature Label 3"}
												layoutDependency={layoutDependency}
												layoutId={"PsyATKRqm-container"}
												name={"Feature Label 3"}
											>
												{_jsx(stdin_default, {
													height: "100%",
													Hqt2h3vZ2: "Serverless Computing",
													id: "PsyATKRqm",
													J1HJ1g2nv: addImageAlt(
														{
															src: "https://framerusercontent.com/images/TpMsQ4JuQXH87CLdEKVrih7OjaY.svg",
														},
														"",
													),
													layoutId: "PsyATKRqm",
													name: "Feature Label 3",
													variant: "k07xlIvCg",
													width: "100%",
												})}
											</motion.div>
										</ComponentViewportProvider>
									</Physics>
								</motion.div>
							</ComponentViewportProvider>
						)}
						{isDisplayed1() && (
							<ComponentViewportProvider>
								<motion.div
									className={"framer-2gmxox-container"}
									layoutDependency={layoutDependency}
									layoutId={"MlsTGt18i-container"}
								>
									<Physics
										densityOptions={{
											density: 0.1,
											enable: true,
										}}
										friction={{
											friction: 0.1,
											frictionAir: 0.01,
										}}
										gravX={0}
										gravY={0.5}
										height={"100%"}
										id={"MlsTGt18i"}
										layoutId={"MlsTGt18i"}
										mouseOptions={{
											angularStiffness: 0,
											enable: true,
											stiffness: 0.5,
										}}
										style={{
											height: "100%",
											width: "100%",
										}}
										wallOptions={{
											bottom: true,
											left: true,
											right: true,
											top: false,
										}}
										width={"100%"}
									>
										<ComponentViewportProvider height={66} width={"205.5px"}>
											<motion.div
												className={"framer-ol76uj-container"}
												data-framer-name={"Feature Label 1"}
												layoutDependency={layoutDependency}
												layoutId={"D9GcvUS7y-container"}
												name={"Feature Label 1"}
											>
												{_jsx(stdin_default, {
													height: "100%",
													Hqt2h3vZ2: "Virtual Assistants",
													id: "D9GcvUS7y",
													J1HJ1g2nv: addImageAlt(
														{
															src: "https://framerusercontent.com/images/WAStXM67xiG29TOK2TCCxlKOmM.svg",
														},
														"",
													),
													layoutId: "D9GcvUS7y",
													name: "Feature Label 1",
													variant: "k07xlIvCg",
													width: "100%",
												})}
											</motion.div>
										</ComponentViewportProvider>
										<ComponentViewportProvider height={66} width={"223px"}>
											<motion.div
												className={"framer-1qbgjdp-container"}
												data-framer-name={"Feature Label 2"}
												layoutDependency={layoutDependency}
												layoutId={"pRWIbEoI5-container"}
												name={"Feature Label 2"}
											>
												{_jsx(stdin_default, {
													height: "100%",
													Hqt2h3vZ2: "AI-Driven Solutions",
													id: "pRWIbEoI5",
													J1HJ1g2nv: addImageAlt(
														{
															src: "https://framerusercontent.com/images/sPmibGCLfmQVJHX0tlJqMt1ZOb8.svg",
														},
														"",
													),
													layoutId: "pRWIbEoI5",
													name: "Feature Label 2",
													variant: "k07xlIvCg",
													width: "100%",
												})}
											</motion.div>
										</ComponentViewportProvider>
										<ComponentViewportProvider height={66} width={"244.5px"}>
											<motion.div
												className={"framer-1sgyqy6-container"}
												data-framer-name={"Feature Label 3"}
												layoutDependency={layoutDependency}
												layoutId={"PsyATKRqm-container"}
												name={"Feature Label 3"}
											>
												{_jsx(stdin_default, {
													height: "100%",
													Hqt2h3vZ2: "Serverless Computing",
													id: "PsyATKRqm",
													J1HJ1g2nv: addImageAlt(
														{
															src: "https://framerusercontent.com/images/TpMsQ4JuQXH87CLdEKVrih7OjaY.svg",
														},
														"",
													),
													layoutId: "PsyATKRqm",
													name: "Feature Label 3",
													variant: "k07xlIvCg",
													width: "100%",
												})}
											</motion.div>
										</ComponentViewportProvider>
										<ComponentViewportProvider height={66} width={"233.5px"}>
											<motion.div
												className={"framer-1h4grzu-container"}
												data-framer-name={"Feature Label 4"}
												layoutDependency={layoutDependency}
												layoutId={"Z76D7d8ef-container"}
												name={"Feature Label 4"}
											>
												{_jsx(stdin_default, {
													height: "100%",
													Hqt2h3vZ2: "Blockchain Solutions",
													id: "Z76D7d8ef",
													J1HJ1g2nv: addImageAlt(
														{
															src: "https://framerusercontent.com/images/8kqYvFGTUzPYPs0dhPf77CqNFG4.svg",
														},
														"",
													),
													layoutId: "Z76D7d8ef",
													name: "Feature Label 4",
													variant: "k07xlIvCg",
													width: "100%",
												})}
											</motion.div>
										</ComponentViewportProvider>
									</Physics>
								</motion.div>
							</ComponentViewportProvider>
						)}
						{isDisplayed2() && (
							<ComponentViewportProvider>
								<motion.div
									className={"framer-yu788l-container"}
									layoutDependency={layoutDependency}
									layoutId={"Q23XWyi38-container"}
								>
									<Physics
										densityOptions={{
											density: 0.1,
											enable: true,
										}}
										friction={{
											friction: 0.1,
											frictionAir: 0.01,
										}}
										gravX={0}
										gravY={0.5}
										height={"100%"}
										id={"Q23XWyi38"}
										layoutId={"Q23XWyi38"}
										mouseOptions={{
											angularStiffness: 0,
											enable: true,
											stiffness: 0.5,
										}}
										style={{
											height: "100%",
											width: "100%",
										}}
										wallOptions={{
											bottom: true,
											left: true,
											right: true,
											top: false,
										}}
										width={"100%"}
									>
										<ComponentViewportProvider height={66} width={"205.5px"}>
											<motion.div
												className={"framer-ol76uj-container"}
												data-framer-name={"Feature Label 1"}
												layoutDependency={layoutDependency}
												layoutId={"D9GcvUS7y-container"}
												name={"Feature Label 1"}
											>
												{_jsx(stdin_default, {
													height: "100%",
													Hqt2h3vZ2: "Virtual Assistants",
													id: "D9GcvUS7y",
													J1HJ1g2nv: addImageAlt(
														{
															src: "https://framerusercontent.com/images/WAStXM67xiG29TOK2TCCxlKOmM.svg",
														},
														"",
													),
													layoutId: "D9GcvUS7y",
													name: "Feature Label 1",
													variant: "k07xlIvCg",
													width: "100%",
												})}
											</motion.div>
										</ComponentViewportProvider>
										<ComponentViewportProvider height={66} width={"223px"}>
											<motion.div
												className={"framer-1qbgjdp-container"}
												data-framer-name={"Feature Label 2"}
												layoutDependency={layoutDependency}
												layoutId={"pRWIbEoI5-container"}
												name={"Feature Label 2"}
											>
												{_jsx(stdin_default, {
													height: "100%",
													Hqt2h3vZ2: "AI-Driven Solutions",
													id: "pRWIbEoI5",
													J1HJ1g2nv: addImageAlt(
														{
															src: "https://framerusercontent.com/images/sPmibGCLfmQVJHX0tlJqMt1ZOb8.svg",
														},
														"",
													),
													layoutId: "pRWIbEoI5",
													name: "Feature Label 2",
													variant: "k07xlIvCg",
													width: "100%",
												})}
											</motion.div>
										</ComponentViewportProvider>
										<ComponentViewportProvider height={66} width={"244.5px"}>
											<motion.div
												className={"framer-1sgyqy6-container"}
												data-framer-name={"Feature Label 3"}
												layoutDependency={layoutDependency}
												layoutId={"PsyATKRqm-container"}
												name={"Feature Label 3"}
											>
												{_jsx(stdin_default, {
													height: "100%",
													Hqt2h3vZ2: "Serverless Computing",
													id: "PsyATKRqm",
													J1HJ1g2nv: addImageAlt(
														{
															src: "https://framerusercontent.com/images/TpMsQ4JuQXH87CLdEKVrih7OjaY.svg",
														},
														"",
													),
													layoutId: "PsyATKRqm",
													name: "Feature Label 3",
													variant: "k07xlIvCg",
													width: "100%",
												})}
											</motion.div>
										</ComponentViewportProvider>
										<ComponentViewportProvider height={66} width={"233.5px"}>
											<motion.div
												className={"framer-1h4grzu-container"}
												data-framer-name={"Feature Label 4"}
												layoutDependency={layoutDependency}
												layoutId={"Z76D7d8ef-container"}
												name={"Feature Label 4"}
											>
												{_jsx(stdin_default, {
													height: "100%",
													Hqt2h3vZ2: "Blockchain Solutions",
													id: "Z76D7d8ef",
													J1HJ1g2nv: addImageAlt(
														{
															src: "https://framerusercontent.com/images/8kqYvFGTUzPYPs0dhPf77CqNFG4.svg",
														},
														"",
													),
													layoutId: "Z76D7d8ef",
													name: "Feature Label 4",
													variant: "k07xlIvCg",
													width: "100%",
												})}
											</motion.div>
										</ComponentViewportProvider>
										<ComponentViewportProvider height={66} width={"210px"}>
											<motion.div
												className={"framer-19rpnir-container"}
												data-framer-name={"Feature Label 5"}
												layoutDependency={layoutDependency}
												layoutId={"jooWCyWaB-container"}
												name={"Feature Label 5"}
											>
												{_jsx(stdin_default, {
													height: "100%",
													Hqt2h3vZ2: "Cloud Integration",
													id: "jooWCyWaB",
													J1HJ1g2nv: addImageAlt(
														{
															src: "https://framerusercontent.com/images/fGRMJzZ1klCadiGWxHOwXOZ9qK0.svg",
														},
														"",
													),
													layoutId: "jooWCyWaB",
													name: "Feature Label 5",
													variant: "k07xlIvCg",
													width: "100%",
												})}
											</motion.div>
										</ComponentViewportProvider>
										<ComponentViewportProvider height={66} width={"170.5px"}>
											<motion.div
												className={"framer-lcayky-container"}
												data-framer-name={"Feature Label 6"}
												layoutDependency={layoutDependency}
												layoutId={"jEg3aOjDy-container"}
												name={"Feature Label 6"}
											>
												{_jsx(stdin_default, {
													height: "100%",
													Hqt2h3vZ2: "Data Insight",
													id: "jEg3aOjDy",
													J1HJ1g2nv: addImageAlt(
														{
															src: "https://framerusercontent.com/images/OT81xXSmHrXj05Gjwm0H4r7m0L8.svg",
														},
														"",
													),
													layoutId: "jEg3aOjDy",
													name: "Feature Label 6",
													variant: "k07xlIvCg",
													width: "100%",
												})}
											</motion.div>
										</ComponentViewportProvider>
									</Physics>
								</motion.div>
							</ComponentViewportProvider>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-UUHgv.framer-3e3u0e, .framer-UUHgv .framer-3e3u0e { display: block; }",
	".framer-UUHgv.framer-m8i9ls { height: 500px; overflow: visible; position: relative; width: 1200px; }",
	".framer-UUHgv .framer-650bh0-container { bottom: 0px; flex: none; height: 100%; left: 0px; position: absolute; right: 0px; }",
	".framer-UUHgv .framer-ol76uj-container, .framer-UUHgv .framer-1qbgjdp-container, .framer-UUHgv .framer-1sgyqy6-container, .framer-UUHgv .framer-1h4grzu-container, .framer-UUHgv .framer-19rpnir-container, .framer-UUHgv .framer-lcayky-container { height: auto; position: relative; width: auto; }",
	".framer-UUHgv .framer-2gmxox-container, .framer-UUHgv .framer-yu788l-container { flex: none; height: 100%; left: 0px; position: absolute; right: 0px; top: calc(50.00000000000002% - 100% / 2); }",
	".framer-UUHgv.framer-v-1rra1ou.framer-m8i9ls { height: 400px; }",
	".framer-UUHgv.framer-v-wvlqnp.framer-m8i9ls { height: 320px; }",
];
var Framerugcb8GbnV = withCSS(Component, css, "framer-UUHgv");
var stdin_default2 = Framerugcb8GbnV;
Framerugcb8GbnV.displayName = "Element/Physics Label";
Framerugcb8GbnV.defaultProps = {
	height: 500,
	width: 1200,
};
addPropertyControls(Framerugcb8GbnV, {
	variant: {
		options: ["ofM_VReS1", "UoEClOBvu", "cq2V5N45S"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	Framerugcb8GbnV,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...CardFeatureSmallFonts,
		...PhysicsFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:element/physics-label
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a6e0de7208a6e203a13a02c0c2342fdcb8c3548bcbc64ba40bb03307875e0fbf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PhysicsLabelFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a6e0de7208a6e203a13a02c0c2342fdcb8c3548bcbc64ba40bb03307875e0fbf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var physics_label_default = ComponentWithRoot;
export { physics_label_default as default };
