// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project a6e0de7208a6e203 "VeeBran", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' | 'Variant 3' | 'Variant 4' | 'Variant 5' // Variant
 * link?: string // Link
}} Props

 */
import { routes } from "../chunks/chunk-ID6ACFOJ.js";

// virtual:element/scroll-arrow
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/vyE14o1sshplJTqOsYQN/pdApkshaeCoQ9tnOOPqu/ScnJWqTFQ.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Link,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = [
	"T_CvI17AE",
	"NLjFvq_w7",
	"oR7NbJZEE",
	"fSQSC2oD8",
	"vuGZkRmwz",
];
var serializationHash = "framer-SGpTV";
var variantClassNames = {
	fSQSC2oD8: "framer-v-1hiwqs2",
	NLjFvq_w7: "framer-v-1u5up2x",
	oR7NbJZEE: "framer-v-1ddlsh6",
	T_CvI17AE: "framer-v-95xppr",
	vuGZkRmwz: "framer-v-1wwjc5j",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 1,
	ease: [0.12, 0.23, 0.5, 1],
	type: "tween",
};
var transition2 = {
	delay: 0,
	duration: 1.2,
	ease: [0.12, 0.23, 0.5, 1],
	type: "tween",
};
var transition3 = {
	delay: 0,
	duration: 0.1,
	ease: [0.12, 0.23, 0.5, 1],
	type: "tween",
};
var transition4 = {
	delay: 0,
	duration: 0.5,
	ease: [0.12, 0.23, 0.5, 1],
	type: "tween",
};
var transition5 = {
	delay: 0,
	duration: 0.2,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var transition6 = {
	delay: 0,
	duration: 1.5,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "T_CvI17AE",
	"Variant 2": "NLjFvq_w7",
	"Variant 3": "oR7NbJZEE",
	"Variant 4": "fSQSC2oD8",
	"Variant 5": "vuGZkRmwz",
};
var getProps = ({ height, id, link, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		M25celVi6: link !== null && link !== void 0 ? link : props.M25celVi6,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "T_CvI17AE",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, M25celVi6, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "T_CvI17AE",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEnterdw2aul = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		await delay(() => setVariant("NLjFvq_w7"), 100);
	});
	const onAppear1iftyzk = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("oR7NbJZEE"), 1200);
	});
	const onAppear1n277bc = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("fSQSC2oD8"), 100);
	});
	const onAppear181ekmi = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("vuGZkRmwz"), 100);
	});
	const onAppear1to9nm3 = activeVariantCallback(async (...args) => {
		setVariant("T_CvI17AE");
	});
	const onMouseLeave10yz658 = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: false,
		});
		await delay(() => setVariant("T_CvI17AE"), 100);
	});
	useOnVariantChange(baseVariant, {
		fSQSC2oD8: onAppear181ekmi,
		NLjFvq_w7: onAppear1iftyzk,
		oR7NbJZEE: onAppear1n277bc,
		vuGZkRmwz: onAppear1to9nm3,
	});
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition
					value={transition1}
					{...addPropertyOverrides(
						{
							fSQSC2oD8: {
								value: transition3,
							},
							NLjFvq_w7: {
								value: transition2,
							},
							oR7NbJZEE: {
								value: transition3,
							},
							vuGZkRmwz: {
								value: transition4,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<Link href={M25celVi6} openInNewTab={false} smoothScroll={true}>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							aria-label={"scroll-down"}
							className={`${cx(serializationHash, ...sharedStyleClassNames, "framer-95xppr", className, classNames)} framer-1tzgvpm`}
							data-framer-name={"Variant 1"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"T_CvI17AE"}
							onMouseEnter={onMouseEnterdw2aul}
							ref={ref !== null && ref !== void 0 ? ref : ref1}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									fSQSC2oD8: {
										"data-framer-name": "Variant 4",
										onMouseEnter: void 0,
									},
									NLjFvq_w7: {
										"data-framer-name": "Variant 2",
										onMouseEnter: void 0,
									},
									oR7NbJZEE: {
										"data-framer-name": "Variant 3",
										onMouseEnter: void 0,
									},
									vuGZkRmwz: {
										"data-framer-name": "Variant 5",
										onMouseEnter: void 0,
										onMouseLeave: onMouseLeave10yz658,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-19yvooo"}
								data-framer-name={"Wrapper"}
								layoutDependency={layoutDependency}
								layoutId={"fitwUzO9p"}
								style={{
									mask: "url('https://framerusercontent.com/images/Q77DT4BAeafdNrAQaK3vjiSvIqg.svg') alpha no-repeat center / cover add",
									scale: 0.7,
									WebkitMask:
										"url('https://framerusercontent.com/images/Q77DT4BAeafdNrAQaK3vjiSvIqg.svg') alpha no-repeat center / cover add",
								}}
							>
								<Transition
									value={transition5}
									{...addPropertyOverrides(
										{
											fSQSC2oD8: {
												value: transition6,
											},
											NLjFvq_w7: {
												value: transition6,
											},
											oR7NbJZEE: {
												value: transition6,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<motion.div
										className={"framer-qncxaj"}
										data-framer-name={"Blur Top"}
										layoutDependency={layoutDependency}
										layoutId={"Dypj5Vle0"}
										style={{
											backgroundColor:
												"var(--token-d5252198-b6fa-4f67-95e8-b1ca52183b58, rgb(228, 111, 3))",
											borderBottomLeftRadius: 54,
											borderBottomRightRadius: 54,
											borderTopLeftRadius: 54,
											borderTopRightRadius: 54,
											filter: "blur(30px)",
											WebkitFilter: "blur(30px)",
										}}
									/>
								</Transition>
								<Transition
									value={transition5}
									{...addPropertyOverrides(
										{
											fSQSC2oD8: {
												value: transition6,
											},
											NLjFvq_w7: {
												value: transition6,
											},
											oR7NbJZEE: {
												value: transition6,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<motion.div
										className={"framer-14mfayh"}
										data-framer-name={"Blur Bottom"}
										layoutDependency={layoutDependency}
										layoutId={"qwoTX1VsT"}
										style={{
											backgroundColor:
												"var(--token-b1d42292-dd1a-4d81-95dc-d6ccd2a40e51, rgb(232, 149, 72))",
											borderBottomLeftRadius: 54,
											borderBottomRightRadius: 54,
											borderTopLeftRadius: 54,
											borderTopRightRadius: 54,
											filter: "blur(30px)",
											WebkitFilter: "blur(30px)",
										}}
									/>
								</Transition>
								<motion.div
									className={"framer-1jyhv35"}
									data-framer-name={"Blur Moving"}
									layoutDependency={layoutDependency}
									layoutId={"PSR4FZvX3"}
									style={{
										backgroundColor:
											"var(--token-b1fb3a8e-a88d-40f2-ad39-1f269e6b91e0, rgb(255, 255, 255))",
										borderBottomLeftRadius: 35,
										borderBottomRightRadius: 35,
										borderTopLeftRadius: 35,
										borderTopRightRadius: 35,
										filter: "blur(30px)",
										opacity: 0.8,
										WebkitFilter: "blur(30px)",
									}}
									transformTemplate={transformTemplate1}
									{...addPropertyOverrides(
										{
											fSQSC2oD8: {
												transformTemplate: void 0,
											},
											NLjFvq_w7: {
												transformTemplate: void 0,
											},
											oR7NbJZEE: {
												transformTemplate: void 0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-SGpTV.framer-1tzgvpm, .framer-SGpTV .framer-1tzgvpm { display: block; }",
	".framer-SGpTV.framer-95xppr { cursor: pointer; height: 190px; overflow: hidden; position: relative; text-decoration: none; width: 150px; }",
	".framer-SGpTV .framer-19yvooo { flex: none; height: 153px; left: calc(49.33333333333336% - 113px / 2); overflow: visible; position: absolute; top: calc(50.00000000000002% - 153px / 2); width: 113px; }",
	".framer-SGpTV .framer-qncxaj { flex: none; height: 142px; left: calc(49.557522123893825% - 87px / 2); overflow: visible; position: absolute; top: -40px; width: 87px; }",
	".framer-SGpTV .framer-14mfayh { bottom: -30px; flex: none; height: 122px; left: -14px; overflow: visible; position: absolute; right: -14px; }",
	".framer-SGpTV .framer-1jyhv35 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 69px); left: 50%; overflow: visible; position: absolute; top: -110px; width: 69px; z-index: 0; }",
	".framer-SGpTV.framer-v-1u5up2x .framer-19yvooo, .framer-SGpTV.framer-v-1ddlsh6 .framer-19yvooo, .framer-SGpTV.framer-v-1hiwqs2 .framer-19yvooo, .framer-SGpTV.framer-v-1wwjc5j .framer-19yvooo { bottom: 0px; top: unset; }",
	".framer-SGpTV.framer-v-1u5up2x .framer-qncxaj { top: -30px; }",
	".framer-SGpTV.framer-v-1u5up2x .framer-14mfayh { bottom: -29px; height: 105px; left: 0px; right: 0px; }",
	".framer-SGpTV.framer-v-1u5up2x .framer-1jyhv35 { aspect-ratio: unset; height: 124px; left: calc(50.44247787610622% - 140px / 2); top: calc(150.98039215686276% - 124px / 2); width: 140px; }",
	".framer-SGpTV.framer-v-1ddlsh6 .framer-14mfayh { bottom: -33px; height: 109px; left: 0px; right: 0px; }",
	".framer-SGpTV.framer-v-1ddlsh6 .framer-1jyhv35 { aspect-ratio: unset; height: 124px; left: calc(183.18584070796462% - 124px / 2); top: calc(150.98039215686276% - 124px / 2); width: 124px; }",
	".framer-SGpTV.framer-v-1hiwqs2 .framer-14mfayh { bottom: -31px; height: 113px; left: 0px; right: 0px; }",
	".framer-SGpTV.framer-v-1hiwqs2 .framer-1jyhv35 { aspect-ratio: unset; height: 124px; left: calc(175.22123893805312% - 124px / 2); top: calc(-78.43137254901958% - 124px / 2); width: 124px; }",
	".framer-SGpTV.framer-v-1wwjc5j .framer-14mfayh { bottom: -40px; height: 142px; }",
	".framer-SGpTV.framer-v-1wwjc5j .framer-1jyhv35 { top: -130px; }",
];
var FramerScnJWqTFQ = withCSS(Component, css, "framer-SGpTV");
var stdin_default = FramerScnJWqTFQ;
FramerScnJWqTFQ.displayName = "Element/Scroll Arrow";
FramerScnJWqTFQ.defaultProps = {
	height: 190,
	width: 150,
};
addPropertyControls(FramerScnJWqTFQ, {
	variant: {
		options: ["T_CvI17AE", "NLjFvq_w7", "oR7NbJZEE", "fSQSC2oD8", "vuGZkRmwz"],
		optionTitles: [
			"Variant 1",
			"Variant 2",
			"Variant 3",
			"Variant 4",
			"Variant 5",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	M25celVi6: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerScnJWqTFQ,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:element/scroll-arrow
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "T_CvI17AE",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a6e0de7208a6e203a13a02c0c2342fdcb8c3548bcbc64ba40bb03307875e0fbf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ScrollArrowFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a6e0de7208a6e203a13a02c0c2342fdcb8c3548bcbc64ba40bb03307875e0fbf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var scroll_arrow_default = ComponentWithRoot;
export { scroll_arrow_default as default };
