// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project a6e0de7208a6e203 "VeeBran", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { routes } from "../chunks/chunk-ID6ACFOJ.js";

// virtual:card-elements/code
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/xUn6dW6AUaiRdTkisujo/EtjLVB2Pfcz9oe0kUmQk/wHOkSCVjJ.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS as withCSS2,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";

// /:https://framerusercontent.com/modules/vgSbxmWWvbgW6ShllXld/IkcZ6LdJBUqPPlbnntkz/Typewriter.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	RenderTarget,
	withCSS,
} from "unframer";
import Typewriter from "typewriter-effect";
var headingStyles = (props) => {
	return {
		width: "100%",
		height: "100%",
		position: "relative",
		overflow: "visible",
		fontSize: props.font.fontSize,
		fontFamily: props.font.fontFamily || "Inter",
		fontWeight: props.font.fontWeight,
		letterSpacing: props.font.letterSpacing,
		lineHeight: props.font.lineHeightType
			? props.font.lineHeight
			: `${props.font.lineHeightPixels}px`,
		textAlign: props.font.textAlign,
		whiteSpace: props.font.whiteSpace,
		color: props.color,
		left: `${props.font.offset}%`,
		margin: 0,
		padding: 0,
	};
};
function TypeWriter(props) {
	const isCanvas = RenderTarget.current() === RenderTarget.canvas;
	const isPreview = RenderTarget.current() === RenderTarget.preview;
	const strings = props.text.split(" ");
	const content = props.split ? strings : props.text;
	const canvasContent = props.split ? strings[0] : props.text;
	const tagMap = {
		paragraph: "p",
		heading1: "h1",
		heading2: "h2",
		heading3: "h3",
	};
	const Tag = tagMap[props.tag];
	const cursorStyles = `.${props.id} .Typewriter { font-size: ${props.font.fontSize}px; font-weight: ${props.font.fontWeight}; margin: 0; padding: 0; } .${props.id} .Typewriter__cursor { color: ${props.cursorColor} !important; }`;
	const TypeWriterPure = () => (
		<span style={headingStyles(props)}>
			<Typewriter
				options={{
					strings: content,
					autoStart: props.autoStart,
					loop: props.loop,
					cursor: props.cursor,
					pauseFor: props.pauseFor * 1e3,
					delay: props.delayType ? "natural" : props.delayNumber * 1e3,
				}}
				component={isPreview ? "span" : Tag}
				onInit={(typewriter) => {
					typewriter.callFunction((state) => {
						if (props.loop) return;
						if (!props.caretVisibility) {
							state.elements.cursor.style.display = "none";
						}
					});
				}}
			/>
		</span>
	);
	const TypeWriterWithCSS = withCSS(
		() => (
			<span
				style={{
					display: "contents",
				}}
				className={`${props.id}`}
			>
				<TypeWriterPure />
			</span>
		),
		cursorStyles,
	);
	return isCanvas ? (
		<div style={headingStyles(props)}>{canvasContent}</div>
	) : (
		<TypeWriterWithCSS />
	);
}
TypeWriter.displayName = "Typewriter";
TypeWriter.defaultProps = {
	text: "Hello World",
	font: {
		fontFamily: "Inter",
		fontSize: 32,
		fontWeight: 600,
		textAlign: "center",
		lineHeight: 1.2,
		lineHeightType: true,
		lineHeightPixels: 100,
		letterSpacing: 0,
		offset: 0,
		whiteSpace: "nowrap",
	},
	cursor: "|",
	delayType: true,
	delayNumber: 0.2,
	pauseFor: 1,
	loop: true,
	caretVisibility: true,
	split: false,
	autoStart: true,
	tag: "heading1",
	color: "#888",
	cursorColor: "rgba(136, 136, 136, 0.5)",
};
addPropertyControls(TypeWriter, {
	tag: {
		title: "Tag",
		type: ControlType.Enum,
		options: ["heading1", "heading2", "heading3", "paragraph"],
		optionTitles: ["H1", "H2", "H3", "P"],
		defaultValue: TypeWriter.defaultProps.tag,
		displaySegmentedControl: true,
	},
	text: {
		type: ControlType.String,
		title: "Text",
		defaultValue: TypeWriter.defaultProps.text,
	},
	autoStart: {
		title: "Autoplay",
		type: ControlType.Boolean,
		defaultValue: TypeWriter.defaultProps.autoStart,
	},
	split: {
		title: "Per Word",
		type: ControlType.Boolean,
		defaultValue: TypeWriter.defaultProps.split,
	},
	loop: {
		title: "Loop",
		type: ControlType.Boolean,
		defaultValue: TypeWriter.defaultProps.loop,
	},
	caretVisibility: {
		title: "Caret",
		type: ControlType.Boolean,
		enabledTitle: "Show",
		disabledTitle: "Hide",
		defaultValue: TypeWriter.defaultProps.caretVisibility,
		hidden: (props) => props.loop,
	},
	delayType: {
		title: "Delay",
		type: ControlType.Boolean,
		enabledTitle: "Natural",
		disabledTitle: "Number",
		defaultValue: TypeWriter.defaultProps.delayType,
	},
	delayNumber: {
		title: "Delay",
		type: ControlType.Number,
		step: 0.1,
		min: 0,
		defaultValue: TypeWriter.defaultProps.delayNumber,
		displayStepper: true,
		hidden: (props) => props.delayType,
	},
	pauseFor: {
		title: "Pause",
		type: ControlType.Number,
		min: 0,
		defaultValue: TypeWriter.defaultProps.pauseFor,
		displayStepper: true,
	},
	color: {
		type: ControlType.Color,
		defaultValue: TypeWriter.defaultProps.color,
	},
	font: {
		type: ControlType.Object,
		controls: {
			fontFamily: {
				title: "Font",
				type: ControlType.String,
				placeholder: "Inter",
				defaultValue: TypeWriter.defaultProps.font.fontFamily,
			},
			fontSize: {
				title: "Size",
				type: ControlType.Number,
				min: 0,
				max: 500,
				step: 0.5,
				defaultValue: TypeWriter.defaultProps.font.fontSize,
			},
			fontWeight: {
				type: ControlType.Enum,
				options: [100, 200, 300, 400, 500, 600, 700, 800, 900],
				defaultValue: TypeWriter.defaultProps.font.fontWeight,
				title: "Weight",
			},
			textAlign: {
				type: ControlType.Enum,
				displaySegmentedControl: true,
				title: "Align",
				options: ["left", "center", "right"],
				optionTitles: ["Left", "Center", "Right"],
				defaultValue: TypeWriter.defaultProps.font.textAlign,
			},
			letterSpacing: {
				title: "Letter",
				type: ControlType.Number,
				defaultValue: TypeWriter.defaultProps.font.letterSpacing,
				step: 0.1,
				displayStepper: true,
			},
			offset: {
				type: ControlType.Number,
				title: "Offset",
				min: -100,
				max: 100,
				displayStepper: true,
				step: 0.25,
				defaultValue: TypeWriter.defaultProps.font.offset,
				unit: "%",
			},
			whiteSpace: {
				type: ControlType.Enum,
				title: "Space",
				options: [
					"normal",
					"nowrap",
					"pre",
					"pre-wrap",
					"preline",
					"break-spaces",
				],
				optionTitles: [
					"Normal",
					"No Wrap",
					"Pre",
					"Pre Wrap",
					"Preline",
					"Break Spaces",
				],
				defaultValue: TypeWriter.defaultProps.font.whiteSpace,
			},
			lineHeight: {
				type: ControlType.Number,
				title: "Line",
				min: -500,
				max: 500,
				displayStepper: true,
				step: 0.1,
				defaultValue: TypeWriter.defaultProps.font.lineHeight,
				hidden: (props) => !props.lineHeightType,
			},
			lineHeightPixels: {
				type: ControlType.Number,
				title: "Line",
				min: -500,
				max: 500,
				displayStepper: true,
				step: 0.1,
				defaultValue: TypeWriter.defaultProps.font.lineHeightPixels,
				hidden: (props) => props.lineHeightType,
			},
			lineHeightType: {
				type: ControlType.Boolean,
				title: " ",
				enabledTitle: "em",
				disabledTitle: "px",
				defaultValue: TypeWriter.defaultProps.font.lineHeightType,
			},
		},
	},
	cursor: {
		title: "Cursor",
		type: ControlType.String,
		defaultValue: TypeWriter.defaultProps.cursor,
		placeholder: "Character",
	},
	cursorColor: {
		type: ControlType.Color,
		title: " ",
		defaultValue: TypeWriter.defaultProps.cursorColor,
	},
});

// /:https://framerusercontent.com/modules/E5q5bZnwnywMSHzc29LM/3mROWlDzRVTdlLkz6FRR/xTQD5vwpU.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"GF;Roboto Mono-500",
	"GF;Roboto Mono-700",
	"GF;Roboto Mono-700italic",
	"GF;Roboto Mono-500italic",
]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Roboto Mono",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/robotomono/v23/L0xuDF4xlVMF-BfR8bXMIhJHg45mwgGEFl0_7PqPRu-5Ip2sSQ.woff2",
				weight: "500",
			},
			{
				family: "Roboto Mono",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/robotomono/v23/L0xuDF4xlVMF-BfR8bXMIhJHg45mwgGEFl0_Of2PRu-5Ip2sSQ.woff2",
				weight: "700",
			},
			{
				family: "Roboto Mono",
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/robotomono/v23/L0xoDF4xlVMF-BfR8bXMIjhOsXG-q2oeuFoqFrmAB-W4AJi8SZwt.woff2",
				weight: "700",
			},
			{
				family: "Roboto Mono",
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/robotomono/v23/L0xoDF4xlVMF-BfR8bXMIjhOsXG-q2oeuFoqFrlVAOW4AJi8SZwt.woff2",
				weight: "500",
			},
		],
	},
];
var css = [
	'.framer-To6Lj .framer-styles-preset-1reeuw3:not(.rich-text-wrapper), .framer-To6Lj .framer-styles-preset-1reeuw3.rich-text-wrapper p { --framer-font-family: "Roboto Mono", monospace; --framer-font-family-bold: "Roboto Mono", monospace; --framer-font-family-bold-italic: "Roboto Mono", monospace; --framer-font-family-italic: "Roboto Mono", monospace; --framer-font-open-type-features: normal; --framer-font-size: 12px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 500; --framer-font-weight-bold: 500; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: 0em; --framer-line-height: 1.6em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-0bd91f44-2ee2-49df-bd1a-78a1b1ec8984, #afafaf); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-To6Lj .framer-styles-preset-1reeuw3:not(.rich-text-wrapper), .framer-To6Lj .framer-styles-preset-1reeuw3.rich-text-wrapper p { --framer-font-family: "Roboto Mono", monospace; --framer-font-family-bold: "Roboto Mono", monospace; --framer-font-family-bold-italic: "Roboto Mono", monospace; --framer-font-family-italic: "Roboto Mono", monospace; --framer-font-open-type-features: normal; --framer-font-size: 12px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 500; --framer-font-weight-bold: 500; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: 0em; --framer-line-height: 1.6em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-0bd91f44-2ee2-49df-bd1a-78a1b1ec8984, #afafaf); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-To6Lj .framer-styles-preset-1reeuw3:not(.rich-text-wrapper), .framer-To6Lj .framer-styles-preset-1reeuw3.rich-text-wrapper p { --framer-font-family: "Roboto Mono", monospace; --framer-font-family-bold: "Roboto Mono", monospace; --framer-font-family-bold-italic: "Roboto Mono", monospace; --framer-font-family-italic: "Roboto Mono", monospace; --framer-font-open-type-features: normal; --framer-font-size: 10.5px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 500; --framer-font-weight-bold: 500; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: 0em; --framer-line-height: 1.6em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-0bd91f44-2ee2-49df-bd1a-78a1b1ec8984, #afafaf); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className = "framer-To6Lj";

// /:https://framerusercontent.com/modules/xUn6dW6AUaiRdTkisujo/EtjLVB2Pfcz9oe0kUmQk/wHOkSCVjJ.js
var TypewriterFonts = getFonts(TypeWriter);
var serializationHash = "framer-OKfbP";
var variantClassNames = {
	AGNRJl0mz: "framer-v-dqjxnm",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 1,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "AGNRJl0mz",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-dqjxnm",
							className2,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"AGNRJl0mz"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							borderBottomLeftRadius: 11,
							borderBottomRightRadius: 11,
							borderTopLeftRadius: 11,
							borderTopRightRadius: 11,
							...style,
						}}
					>
						<motion.div
							className={"framer-rofrdl"}
							layoutDependency={layoutDependency}
							layoutId={"IPZE4lYY1"}
							style={{
								borderBottomLeftRadius: 10,
								borderBottomRightRadius: 10,
								borderTopLeftRadius: 10,
								borderTopRightRadius: 10,
							}}
						>
							<motion.div
								className={"framer-h95dpm"}
								data-framer-name={"Line"}
								layoutDependency={layoutDependency}
								layoutId={"n9OlZexOf"}
								style={{
									background:
										'linear-gradient(-89.99998409720868deg, var(--token-4d67072c-df86-41a3-8260-1a48b41c6ca7, rgb(20, 20, 20)) /* {"name":"Dark/400"} */ 0%, var(--token-c311f7eb-2396-4f7f-8edd-f790b3c42ec3, rgb(5, 5, 5)) /* {"name":"Dark/600"} */ 100%)',
									borderBottomLeftRadius: 10,
									borderTopLeftRadius: 10,
									opacity: 0.68,
								}}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-vjo39e"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"ORv2vr3ig"}
									style={{
										"--extracted-1sbpzw":
											"var(--token-cfa5bfd0-3a9c-40a0-a3bd-57ca9dc5f070, rgb(98, 98, 98))",
										"--extracted-1w3ko1f":
											"var(--token-cfa5bfd0-3a9c-40a0-a3bd-57ca9dc5f070, rgb(98, 98, 98))",
										"--extracted-41musj":
											"var(--token-cfa5bfd0-3a9c-40a0-a3bd-57ca9dc5f070, rgb(98, 98, 98))",
										"--extracted-7f00lb":
											"var(--token-cfa5bfd0-3a9c-40a0-a3bd-57ca9dc5f070, rgb(98, 98, 98))",
										"--extracted-c9yw3e":
											"var(--token-cfa5bfd0-3a9c-40a0-a3bd-57ca9dc5f070, rgb(98, 98, 98))",
										"--extracted-dfbufw":
											"var(--token-cfa5bfd0-3a9c-40a0-a3bd-57ca9dc5f070, rgb(98, 98, 98))",
										"--extracted-hjr9e8":
											"var(--token-cfa5bfd0-3a9c-40a0-a3bd-57ca9dc5f070, rgb(98, 98, 98))",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1reeuw3"}
											data-styles-preset={"xTQD5vwpU"}
										>
											<motion.span
												style={{
													"--framer-text-color":
														"var(--extracted-1w3ko1f, var(--token-cfa5bfd0-3a9c-40a0-a3bd-57ca9dc5f070, rgb(98, 98, 98)))",
												}}
											>
												{"1"}
											</motion.span>
											<motion.br />
											<motion.span
												style={{
													"--framer-text-color":
														"var(--extracted-c9yw3e, var(--token-cfa5bfd0-3a9c-40a0-a3bd-57ca9dc5f070, rgb(98, 98, 98)))",
												}}
											>
												{"2"}
											</motion.span>
											<motion.br />
											<motion.span
												style={{
													"--framer-text-color":
														"var(--extracted-dfbufw, var(--token-cfa5bfd0-3a9c-40a0-a3bd-57ca9dc5f070, rgb(98, 98, 98)))",
												}}
											>
												{"3"}
											</motion.span>
											<motion.br />
											<motion.span
												style={{
													"--framer-text-color":
														"var(--extracted-41musj, var(--token-cfa5bfd0-3a9c-40a0-a3bd-57ca9dc5f070, rgb(98, 98, 98)))",
												}}
											>
												{"4"}
											</motion.span>
											<motion.br />
											<motion.span
												style={{
													"--framer-text-color":
														"var(--extracted-1sbpzw, var(--token-cfa5bfd0-3a9c-40a0-a3bd-57ca9dc5f070, rgb(98, 98, 98)))",
												}}
											>
												{"5"}
											</motion.span>
											<motion.br />
											<motion.span
												style={{
													"--framer-text-color":
														"var(--extracted-7f00lb, var(--token-cfa5bfd0-3a9c-40a0-a3bd-57ca9dc5f070, rgb(98, 98, 98)))",
												}}
											>
												{"6"}
											</motion.span>
											<motion.br />
											<motion.span
												style={{
													"--framer-text-color":
														"var(--extracted-hjr9e8, var(--token-cfa5bfd0-3a9c-40a0-a3bd-57ca9dc5f070, rgb(98, 98, 98)))",
												}}
											>
												{"7"}
											</motion.span>
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-g0o75b"}
								data-framer-name={"Code Snippet"}
								layoutDependency={layoutDependency}
								layoutId={"cDPvDvJ5k"}
								style={{
									background:
										'linear-gradient(-89.99998718973049deg, var(--token-c311f7eb-2396-4f7f-8edd-f790b3c42ec3, rgb(5, 5, 5)) /* {"name":"Dark/600"} */ 0%, rgba(0, 0, 0, 1) 100%)',
									borderBottomRightRadius: 10,
									borderTopRightRadius: 10,
									opacity: 0.68,
								}}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-fjllxr"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"Kk5tYyLx4"}
									style={{
										"--extracted-1w3ko1f":
											"var(--token-d3f304a1-8f3c-4236-99dd-3a229afb5214, rgb(239, 139, 46))",
										"--extracted-dfbufw":
											"var(--token-d3f304a1-8f3c-4236-99dd-3a229afb5214, rgb(239, 139, 46))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1reeuw3"}
											data-styles-preset={"xTQD5vwpU"}
										>
											<motion.span
												style={{
													"--framer-text-color":
														"var(--extracted-1w3ko1f, var(--token-d3f304a1-8f3c-4236-99dd-3a229afb5214, rgb(239, 139, 46)))",
												}}
											>
												{"Class"}
											</motion.span>
											{" ChatBot{ "}
											<motion.br />
											{"  address public owner; "}
											<motion.br />
											{"  int private response;"}
											<motion.br />
											{"  "}
											<motion.span
												style={{
													"--framer-text-color":
														"var(--extracted-dfbufw, var(--token-d3f304a1-8f3c-4236-99dd-3a229afb5214, rgb(239, 139, 46)))",
												}}
											>
												{"constructor"}
											</motion.span>
											{"(){"}
											<motion.br />
											{"    owner = msg.sender;"}
											<motion.br />
											{"  }"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<motion.div
									className={"framer-1ttsgr0"}
									data-framer-name={"Typing"}
									layoutDependency={layoutDependency}
									layoutId={"drE9KoZo4"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-zunpox"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"BaVrD0as3"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-d3f304a1-8f3c-4236-99dd-3a229afb5214, rgb(239, 139, 46))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-1reeuw3"}
												data-styles-preset={"xTQD5vwpU"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-d3f304a1-8f3c-4236-99dd-3a229afb5214, rgb(239, 139, 46)))",
												}}
											>
												{"  function "}
											</motion.p>
										</React.Fragment>
									</RichText>
									<ComponentViewportProvider>
										<motion.div
											className={"framer-32fi80-container"}
											layoutDependency={layoutDependency}
											layoutId={"Cm4jsKoey-container"}
										>
											<TypeWriter
												autoStart={true}
												caretVisibility={true}
												color={
													"var(--token-0bd91f44-2ee2-49df-bd1a-78a1b1ec8984, rgb(175, 175, 175))"
												}
												cursor={"|"}
												cursorColor={
													"var(--token-cfa5bfd0-3a9c-40a0-a3bd-57ca9dc5f070, rgb(98, 98, 98))"
												}
												delayNumber={0.1}
												delayType={true}
												font={{
													fontFamily: "roboto mono",
													fontSize: 10.5,
													fontWeight: 400,
													letterSpacing: 0,
													lineHeight: 1.6,
													lineHeightPixels: 100,
													lineHeightType: true,
													offset: 0,
													textAlign: "left",
													whiteSpace: "normal",
												}}
												height={"100%"}
												id={"Cm4jsKoey"}
												layoutId={"Cm4jsKoey"}
												loop={true}
												pauseFor={1}
												split={true}
												style={{
													width: "100%",
												}}
												tag={"paragraph"}
												text={"response(msg){"}
												width={"100%"}
											/>
										</motion.div>
									</ComponentViewportProvider>
								</motion.div>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-OKfbP.framer-qtk5ro, .framer-OKfbP .framer-qtk5ro { display: block; }",
	".framer-OKfbP.framer-dqjxnm { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 185px; justify-content: center; overflow: visible; padding: 1px; position: relative; width: 285px; }",
	".framer-OKfbP .framer-rofrdl { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 100%; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-OKfbP .framer-h95dpm { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 100%; justify-content: center; max-width: 46px; padding: 10px 12px 10px 12px; position: relative; width: 1px; }",
	".framer-OKfbP .framer-vjo39e, .framer-OKfbP .framer-zunpox { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-OKfbP .framer-g0o75b { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 100%; justify-content: center; padding: 10px 5px 10px 18px; position: relative; width: 1px; }",
	".framer-OKfbP .framer-fjllxr { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-OKfbP .framer-1ttsgr0 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-OKfbP .framer-32fi80-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-OKfbP.framer-dqjxnm, .framer-OKfbP .framer-rofrdl, .framer-OKfbP .framer-h95dpm, .framer-OKfbP .framer-g0o75b, .framer-OKfbP .framer-1ttsgr0 { gap: 0px; } .framer-OKfbP.framer-dqjxnm > *, .framer-OKfbP .framer-rofrdl > *, .framer-OKfbP .framer-1ttsgr0 > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-OKfbP.framer-dqjxnm > :first-child, .framer-OKfbP .framer-rofrdl > :first-child, .framer-OKfbP .framer-1ttsgr0 > :first-child { margin-left: 0px; } .framer-OKfbP.framer-dqjxnm > :last-child, .framer-OKfbP .framer-rofrdl > :last-child, .framer-OKfbP .framer-1ttsgr0 > :last-child { margin-right: 0px; } .framer-OKfbP .framer-h95dpm > *, .framer-OKfbP .framer-g0o75b > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-OKfbP .framer-h95dpm > :first-child, .framer-OKfbP .framer-g0o75b > :first-child { margin-top: 0px; } .framer-OKfbP .framer-h95dpm > :last-child, .framer-OKfbP .framer-g0o75b > :last-child { margin-bottom: 0px; } }",
	...css,
];
var FramerwHOkSCVjJ = withCSS2(Component, css2, "framer-OKfbP");
var stdin_default = FramerwHOkSCVjJ;
FramerwHOkSCVjJ.displayName = "Card Elements/Code";
FramerwHOkSCVjJ.defaultProps = {
	height: 185,
	width: 285,
};
addFonts(
	FramerwHOkSCVjJ,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...TypewriterFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:card-elements/code
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a6e0de7208a6e203a13a02c0c2342fdcb8c3548bcbc64ba40bb03307875e0fbf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CodeFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a6e0de7208a6e203a13a02c0c2342fdcb8c3548bcbc64ba40bb03307875e0fbf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var code_default = ComponentWithRoot;
export { code_default as default };
