// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project a6e0de7208a6e203 "VeeBran", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Feature' | 'Feature XS' // Variant
 * labelTitle?: string // Label Title
 * icon?: {src: string, srcSet?: string, alt?: string} // Icon
}} Props

 */
import { stdin_default } from "../chunks/chunk-LFCN3FO3.js";
import { routes } from "../chunks/chunk-ID6ACFOJ.js";

// virtual:section-service/service-small
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "k07xlIvCg",
	xl: "gndGeEyXW",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a6e0de7208a6e203a13a02c0c2342fdcb8c3548bcbc64ba40bb03307875e0fbf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ServiceSmallFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a6e0de7208a6e203a13a02c0c2342fdcb8c3548bcbc64ba40bb03307875e0fbf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var service_small_default = ComponentWithRoot;
export { service_small_default as default };
