// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project a6e0de7208a6e203 "VeeBran", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop Service Widget - A' | 'Desktop Service Widget - B' | 'Desktop Service Widget - C' | 'Mobile Service Widget - A' | 'Mobile Service Widget - B' | 'Mobile Service Widget - C' // Variant
 * title?: string // Title
 * text?: string // Text
}} Props

 */
import { className, css, fonts } from "../chunks/chunk-ZJPHMQ27.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "../chunks/chunk-WF6ASFEM.js";
import { routes } from "../chunks/chunk-ID6ACFOJ.js";

// virtual:section-service/service-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/tFOKcyX15kI2kQD65gEw/tXaKiHAzniSe992ZyiWf/FZKIN6ZmV.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = [
	"htN96S2j0",
	"VZHt01_Sw",
	"UWa9YVS8Y",
	"pmEDr1B_L",
	"okM1LWNPs",
	"LwGsRAL0V",
];
var serializationHash = "framer-kOo3Q";
var variantClassNames = {
	htN96S2j0: "framer-v-1o6kjpi",
	LwGsRAL0V: "framer-v-16jddom",
	okM1LWNPs: "framer-v-1bxm9jx",
	pmEDr1B_L: "framer-v-ngdgy",
	UWa9YVS8Y: "framer-v-wgtziy",
	VZHt01_Sw: "framer-v-1vu6tax",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Desktop Service Widget - A": "htN96S2j0",
	"Desktop Service Widget - B": "VZHt01_Sw",
	"Desktop Service Widget - C": "UWa9YVS8Y",
	"Mobile Service Widget - A": "pmEDr1B_L",
	"Mobile Service Widget - B": "okM1LWNPs",
	"Mobile Service Widget - C": "LwGsRAL0V",
};
var getProps = ({ height, id, text, title, width, ...props }) => {
	return {
		...props,
		LDtNkqyQr: title ?? props.LDtNkqyQr ?? "Title",
		olse2q6Lu: text ?? props.olse2q6Lu ?? "Detail",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "htN96S2j0",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		LDtNkqyQr,
		olse2q6Lu,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "htN96S2j0",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1o6kjpi",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop Service Widget - A"}
						layoutDependency={layoutDependency}
						layoutId={"htN96S2j0"}
						ref={refBinding}
						style={{
							background:
								"linear-gradient(180deg, var(--token-4d6fb0aa-347b-4d07-918a-f12b70b08ad3, rgb(33, 33, 33)) 0%, var(--token-4d67072c-df86-41a3-8260-1a48b41c6ca7, rgb(17, 17, 17)) 100%)",
							borderBottomLeftRadius: 25,
							borderBottomRightRadius: 25,
							borderTopLeftRadius: 25,
							borderTopRightRadius: 25,
							boxShadow: "0px 4px 33px 0px rgba(0, 0, 0, 0.05)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								LwGsRAL0V: {
									"data-framer-name": "Mobile Service Widget - C",
								},
								okM1LWNPs: {
									"data-framer-name": "Mobile Service Widget - B",
								},
								pmEDr1B_L: {
									"data-framer-name": "Mobile Service Widget - A",
								},
								UWa9YVS8Y: {
									"data-framer-name": "Desktop Service Widget - C",
								},
								VZHt01_Sw: {
									"data-framer-name": "Desktop Service Widget - B",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1xl2fcu"}
							data-framer-name={"Wrapper"}
							layoutDependency={layoutDependency}
							layoutId={"EXd6zwMwn"}
							style={{
								background:
									"radial-gradient(46% 31% at 50% 0%, var(--token-4d6fb0aa-347b-4d07-918a-f12b70b08ad3, rgb(33, 33, 33)) 0%, var(--token-4d67072c-df86-41a3-8260-1a48b41c6ca7, rgb(17, 17, 17)) 100%)",
								borderBottomLeftRadius: 25,
								borderBottomRightRadius: 25,
								borderTopLeftRadius: 25,
								borderTopRightRadius: 25,
							}}
						>
							<Image
								background={{
									alt: "card-background",
									fit: "fit",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											1 +
											(((componentViewport?.height || 388) - 2 - 501.5) / 2 +
												0 +
												0) +
											-5,
									),
									pixelHeight: 359,
									pixelWidth: 357,
									positionX: "center",
									positionY: "center",
									src: "https://framerusercontent.com/images/kqJNnjGgAUImwuaX1RZZWjFMc.png",
								}}
								className={"framer-zo8go7"}
								data-framer-name={"Grid Background"}
								layoutDependency={layoutDependency}
								layoutId={"s5RwVPAB3"}
								style={{
									borderBottomRightRadius: 23,
									opacity: 0.15,
									scale: 1,
								}}
								variants={{
									LwGsRAL0V: {
										scale: 0.8,
									},
									okM1LWNPs: {
										scale: 0.8,
									},
									pmEDr1B_L: {
										scale: 0.8,
									},
								}}
								{...addPropertyOverrides(
									{
										LwGsRAL0V: {
											background: {
												alt: "card-background",
												fit: "fit",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														1 +
														(((componentViewport?.height || 378) - 2 - 491.5) /
															2 +
															0 +
															0) +
														-26,
												),
												pixelHeight: 359,
												pixelWidth: 357,
												positionX: "center",
												positionY: "center",
												src: "https://framerusercontent.com/images/kqJNnjGgAUImwuaX1RZZWjFMc.png",
											},
										},
										okM1LWNPs: {
											background: {
												alt: "card-background",
												fit: "fit",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														1 +
														(((componentViewport?.height || 378) - 2 - 491.5) /
															2 +
															0 +
															0) +
														-26,
												),
												pixelHeight: 359,
												pixelWidth: 357,
												positionX: "center",
												positionY: "center",
												src: "https://framerusercontent.com/images/kqJNnjGgAUImwuaX1RZZWjFMc.png",
											},
										},
										pmEDr1B_L: {
											background: {
												alt: "card-background",
												fit: "fit",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														1 +
														(((componentViewport?.height || 378) - 2 - 491.5) /
															2 +
															0 +
															0) +
														-26,
												),
												pixelHeight: 359,
												pixelWidth: 357,
												positionX: "center",
												positionY: "center",
												src: "https://framerusercontent.com/images/kqJNnjGgAUImwuaX1RZZWjFMc.png",
											},
										},
										UWa9YVS8Y: {
											background: {
												alt: "card-background",
												fit: "fit",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														1 +
														(((componentViewport?.height || 200) - 2 - 501.5) /
															2 +
															0 +
															0) +
														-5,
												),
												pixelHeight: 359,
												pixelWidth: 357,
												positionX: "center",
												positionY: "center",
												src: "https://framerusercontent.com/images/kqJNnjGgAUImwuaX1RZZWjFMc.png",
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-s1ogn8"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"alO58lwyG"}
								style={{
									"--extracted-a0htzi":
										"var(--token-b1fb3a8e-a88d-40f2-ad39-1f269e6b91e0, rgb(255, 255, 255))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={LDtNkqyQr}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h3
										className={"framer-styles-preset-ez3j3x"}
										data-styles-preset={"VVJbpVX8b"}
										style={{
											"--framer-text-alignment": "center",
											"--framer-text-color":
												"var(--extracted-a0htzi, var(--token-b1fb3a8e-a88d-40f2-ad39-1f269e6b91e0, rgb(255, 255, 255)))",
										}}
									>
										{"Creative Expertise"}
									</motion.h3>
								</React.Fragment>
							</RichText>
							<motion.div
								className={"framer-1k2cxyx"}
								data-framer-name={"Widget"}
								layoutDependency={layoutDependency}
								layoutId={"ULohWb8LP"}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												1 +
												(((componentViewport?.height || 388) - 2 - 501.5) / 2 +
													0 +
													0) +
												32 +
												69.5 +
												0 +
												0,
										),
										pixelHeight: 2800,
										pixelWidth: 4096,
										positionX: "center",
										positionY: "center",
										sizes: `calc(${componentViewport?.width || "100vw"} - 66px)`,
										src: "https://framerusercontent.com/images/v1qtthOgVn0lhfNhOij2ZwStXk.jpg",
										srcSet:
											"https://framerusercontent.com/images/v1qtthOgVn0lhfNhOij2ZwStXk.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/v1qtthOgVn0lhfNhOij2ZwStXk.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/v1qtthOgVn0lhfNhOij2ZwStXk.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/v1qtthOgVn0lhfNhOij2ZwStXk.jpg 4096w",
									}}
									className={"framer-15te7nu"}
									data-border={true}
									data-framer-name={"Interactive Card"}
									layoutDependency={layoutDependency}
									layoutId={"iYZtFYryL"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-4d6fb0aa-347b-4d07-918a-f12b70b08ad3, rgb(38, 38, 38))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										borderBottomLeftRadius: 18,
										borderBottomRightRadius: 18,
										borderTopLeftRadius: 18,
										borderTopRightRadius: 18,
									}}
									{...addPropertyOverrides(
										{
											LwGsRAL0V: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															1 +
															(((componentViewport?.height || 378) -
																2 -
																491.5) /
																2 +
																0 +
																0) +
															36 +
															61.5 +
															0 +
															0,
													),
													pixelHeight: 2800,
													pixelWidth: 4096,
													positionX: "center",
													positionY: "center",
													sizes: `calc(${componentViewport?.width || "100vw"} - 50px)`,
													src: "https://framerusercontent.com/images/ZwYAqkd6JE3IFA2LtuBKgufaPc.jpg",
													srcSet:
														"https://framerusercontent.com/images/ZwYAqkd6JE3IFA2LtuBKgufaPc.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/ZwYAqkd6JE3IFA2LtuBKgufaPc.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/ZwYAqkd6JE3IFA2LtuBKgufaPc.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/ZwYAqkd6JE3IFA2LtuBKgufaPc.jpg 4096w",
												},
											},
											okM1LWNPs: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															1 +
															(((componentViewport?.height || 378) -
																2 -
																491.5) /
																2 +
																0 +
																0) +
															36 +
															61.5 +
															0 +
															0,
													),
													pixelHeight: 2649,
													pixelWidth: 4096,
													positionX: "center",
													positionY: "center",
													sizes: `calc(${componentViewport?.width || "100vw"} - 50px)`,
													src: "https://framerusercontent.com/images/iJiYT0Bkw6pRNh6fPlW8b1g3wk.jpg",
													srcSet:
														"https://framerusercontent.com/images/iJiYT0Bkw6pRNh6fPlW8b1g3wk.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/iJiYT0Bkw6pRNh6fPlW8b1g3wk.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/iJiYT0Bkw6pRNh6fPlW8b1g3wk.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/iJiYT0Bkw6pRNh6fPlW8b1g3wk.jpg 4096w",
												},
											},
											pmEDr1B_L: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															1 +
															(((componentViewport?.height || 378) -
																2 -
																491.5) /
																2 +
																0 +
																0) +
															36 +
															61.5 +
															0 +
															0,
													),
													pixelHeight: 2800,
													pixelWidth: 4096,
													positionX: "center",
													positionY: "center",
													sizes: `calc(${componentViewport?.width || "100vw"} - 50px)`,
													src: "https://framerusercontent.com/images/v1qtthOgVn0lhfNhOij2ZwStXk.jpg",
													srcSet:
														"https://framerusercontent.com/images/v1qtthOgVn0lhfNhOij2ZwStXk.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/v1qtthOgVn0lhfNhOij2ZwStXk.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/v1qtthOgVn0lhfNhOij2ZwStXk.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/v1qtthOgVn0lhfNhOij2ZwStXk.jpg 4096w",
												},
											},
											UWa9YVS8Y: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															1 +
															(((componentViewport?.height || 200) -
																2 -
																501.5) /
																2 +
																0 +
																0) +
															32 +
															69.5 +
															0 +
															0,
													),
													pixelHeight: 2800,
													pixelWidth: 4096,
													positionX: "center",
													positionY: "center",
													sizes: `calc(${componentViewport?.width || "100vw"} - 66px)`,
													src: "https://framerusercontent.com/images/ZwYAqkd6JE3IFA2LtuBKgufaPc.jpg",
													srcSet:
														"https://framerusercontent.com/images/ZwYAqkd6JE3IFA2LtuBKgufaPc.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/ZwYAqkd6JE3IFA2LtuBKgufaPc.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/ZwYAqkd6JE3IFA2LtuBKgufaPc.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/ZwYAqkd6JE3IFA2LtuBKgufaPc.jpg 4096w",
												},
											},
											VZHt01_Sw: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															1 +
															(((componentViewport?.height || 388) -
																2 -
																501.5) /
																2 +
																0 +
																0) +
															32 +
															69.5 +
															0 +
															0,
													),
													pixelHeight: 2649,
													pixelWidth: 4096,
													positionX: "center",
													positionY: "center",
													sizes: `calc(${componentViewport?.width || "100vw"} - 66px)`,
													src: "https://framerusercontent.com/images/iJiYT0Bkw6pRNh6fPlW8b1g3wk.jpg",
													srcSet:
														"https://framerusercontent.com/images/iJiYT0Bkw6pRNh6fPlW8b1g3wk.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/iJiYT0Bkw6pRNh6fPlW8b1g3wk.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/iJiYT0Bkw6pRNh6fPlW8b1g3wk.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/iJiYT0Bkw6pRNh6fPlW8b1g3wk.jpg 4096w",
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-botv0c"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"k3wkv5vAu"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={olse2q6Lu}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1237v2y"}
											data-styles-preset={"wRTC8eDCA"}
											style={{
												"--framer-text-alignment": "center",
											}}
										>
											{
												"First impressions matter. That'swhy our mission is to create clean."
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-kOo3Q.framer-48gvw1, .framer-kOo3Q .framer-48gvw1 { display: block; }",
	".framer-kOo3Q.framer-1o6kjpi { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 1px; position: relative; width: 383px; will-change: var(--framer-will-change-override, transform); }",
	".framer-kOo3Q .framer-1xl2fcu { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: hidden; padding: 32px 32px 42px 32px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-kOo3Q .framer-zo8go7 { flex: none; height: 239px; left: calc(50.13123359580055% - 239px / 2); overflow: hidden; position: absolute; top: -5px; width: 239px; will-change: var(--framer-will-change-override, transform); }",
	".framer-kOo3Q .framer-s1ogn8 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-kOo3Q .framer-1k2cxyx { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-kOo3Q .framer-15te7nu { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 190px; justify-content: center; overflow: visible; padding: 0px 16px 0px 16px; position: relative; width: 100%; }",
	".framer-kOo3Q .framer-botv0c { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: 100%; }",
	".framer-kOo3Q.framer-v-ngdgy .framer-1xl2fcu, .framer-kOo3Q.framer-v-1bxm9jx .framer-1xl2fcu, .framer-kOo3Q.framer-v-16jddom .framer-1xl2fcu { gap: 24px; padding: 36px 24px 36px 24px; }",
	".framer-kOo3Q.framer-v-ngdgy .framer-zo8go7, .framer-kOo3Q.framer-v-1bxm9jx .framer-zo8go7, .framer-kOo3Q.framer-v-16jddom .framer-zo8go7 { top: -26px; }",
	...css,
	...css2,
	'.framer-kOo3Q[data-border="true"]::after, .framer-kOo3Q [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerFZKIN6ZmV = withCSS(Component, css3, "framer-kOo3Q");
var stdin_default = FramerFZKIN6ZmV;
FramerFZKIN6ZmV.displayName = "Section Service/Service Card";
FramerFZKIN6ZmV.defaultProps = {
	height: 388,
	width: 383,
};
addPropertyControls(FramerFZKIN6ZmV, {
	variant: {
		options: [
			"htN96S2j0",
			"VZHt01_Sw",
			"UWa9YVS8Y",
			"pmEDr1B_L",
			"okM1LWNPs",
			"LwGsRAL0V",
		],
		optionTitles: [
			"Desktop Service Widget - A",
			"Desktop Service Widget - B",
			"Desktop Service Widget - C",
			"Mobile Service Widget - A",
			"Mobile Service Widget - B",
			"Mobile Service Widget - C",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	LDtNkqyQr: {
		defaultValue: "Title",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	olse2q6Lu: {
		defaultValue: "Detail",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
});
addFonts(
	FramerFZKIN6ZmV,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:section-service/service-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "LwGsRAL0V",
	xl: "UWa9YVS8Y",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a6e0de7208a6e203a13a02c0c2342fdcb8c3548bcbc64ba40bb03307875e0fbf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ServiceCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a6e0de7208a6e203a13a02c0c2342fdcb8c3548bcbc64ba40bb03307875e0fbf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var service_card_default = ComponentWithRoot;
export { service_card_default as default };
