// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project a6e0de7208a6e203 "VeeBran", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { stdin_default } from "../chunks/chunk-7XCOVW2X.js";
import "../chunks/chunk-66EJKQKM.js";
import "../chunks/chunk-NULYBL27.js";
import { routes } from "../chunks/chunk-ID6ACFOJ.js";

// virtual:section-faq/accordion
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/i6W1dWQ4XdlraRj5falD/ZZhnfhtFhMOY2zVzIqfn/tuudda9SI.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var SectionFAQAccordionItemFonts = getFonts(stdin_default);
var serializationHash = "framer-CqrPn";
var variantClassNames = {
	syHNzBCED: "framer-v-151bexu",
};
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "syHNzBCED",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-151bexu",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"syHNzBCED"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<ComponentViewportProvider
							height={68}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 316) - 0 - 314) / 2 + 0 + 0)
							}
						>
							<SmartComponentScopedContainer
								className={"framer-1adb2q2-container"}
								layoutDependency={layoutDependency}
								layoutId={"sFgruxCm_-container"}
								nodeId={"sFgruxCm_"}
								rendersWithMotion={true}
								scopeId={"tuudda9SI"}
							>
								{_jsx(stdin_default, {
									h8iGjYmBY:
										"What makes VeeBran different from other automation agencies?",
									height: "100%",
									id: "sFgruxCm_",
									layoutId: "sFgruxCm_",
									style: {
										width: "100%",
									},
									variant: "Gtr_Mhomh",
									width: "100%",
									YgvPXMWsF:
										"We combine deep AI expertise with a personal touch\u2014ensuring every solution is tailored, transparent, and impactful.",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={68}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 316) - 0 - 314) / 2 + 68 + 14)
							}
						>
							<SmartComponentScopedContainer
								className={"framer-1h67c8g-container"}
								layoutDependency={layoutDependency}
								layoutId={"P5lwDBghV-container"}
								nodeId={"P5lwDBghV"}
								rendersWithMotion={true}
								scopeId={"tuudda9SI"}
							>
								{_jsx(stdin_default, {
									h8iGjYmBY: "How does the LinkedIn First Approach work?",
									height: "100%",
									id: "P5lwDBghV",
									layoutId: "P5lwDBghV",
									style: {
										width: "100%",
									},
									variant: "Gtr_Mhomh",
									width: "100%",
									YgvPXMWsF:
										"We use AI-driven insights to craft your LinkedIn profile, create engaging content, and build authentic connections that drive real business results.",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={68}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 316) - 0 - 314) / 2 + 136 + 28)
							}
						>
							<SmartComponentScopedContainer
								className={"framer-1ch32kk-container"}
								layoutDependency={layoutDependency}
								layoutId={"XuiqYmGOT-container"}
								nodeId={"XuiqYmGOT"}
								rendersWithMotion={true}
								scopeId={"tuudda9SI"}
							>
								{_jsx(stdin_default, {
									h8iGjYmBY: "Can I customize my plan?",
									height: "100%",
									id: "XuiqYmGOT",
									layoutId: "XuiqYmGOT",
									style: {
										width: "100%",
									},
									variant: "Gtr_Mhomh",
									width: "100%",
									YgvPXMWsF:
										"Absolutely! Every business is unique. Let\u2019s discuss your needs and create a plan that fits.",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={68}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 316) - 0 - 314) / 2 + 204 + 42)
							}
						>
							<SmartComponentScopedContainer
								className={"framer-5mht65-container"}
								layoutDependency={layoutDependency}
								layoutId={"q1pxE8Vj8-container"}
								nodeId={"q1pxE8Vj8"}
								rendersWithMotion={true}
								scopeId={"tuudda9SI"}
							>
								{_jsx(stdin_default, {
									h8iGjYmBY: "Is this only for tech businesses?",
									height: "100%",
									id: "q1pxE8Vj8",
									layoutId: "q1pxE8Vj8",
									style: {
										width: "100%",
									},
									variant: "Gtr_Mhomh",
									width: "100%",
									YgvPXMWsF:
										"Nope. We work with coaches, agencies, creators, SaaS founders, eComm brands, and more.",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-CqrPn.framer-1n40f, .framer-CqrPn .framer-1n40f { display: block; }",
	".framer-CqrPn.framer-151bexu { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 14px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 854px; }",
	".framer-CqrPn .framer-1adb2q2-container, .framer-CqrPn .framer-1h67c8g-container, .framer-CqrPn .framer-1ch32kk-container, .framer-CqrPn .framer-5mht65-container { flex: none; height: auto; position: relative; width: 100%; }",
];
var Framertuudda9SI = withCSS(Component, css, "framer-CqrPn");
var stdin_default2 = Framertuudda9SI;
Framertuudda9SI.displayName = "Section FAQ/Accordion";
Framertuudda9SI.defaultProps = {
	height: 316,
	width: 854,
};
addFonts(
	Framertuudda9SI,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...SectionFAQAccordionItemFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:section-faq/accordion
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a6e0de7208a6e203a13a02c0c2342fdcb8c3548bcbc64ba40bb03307875e0fbf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AccordionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a6e0de7208a6e203a13a02c0c2342fdcb8c3548bcbc64ba40bb03307875e0fbf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var accordion_default = ComponentWithRoot;
export { accordion_default as default };
