// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project a6e0de7208a6e203 "VeeBran", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Active 1' | 'Active 2' | 'Active 3' // Variant
}} Props

 */
import {
	className,
	css,
	fonts,
	stdin_default,
} from "./chunks/chunk-OQGMRSSP.js";
import { routes } from "./chunks/chunk-ID6ACFOJ.js";

// virtual:line-wrap
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/mgHktD2VGmZ3IWO3rbvZ/FgyhQ91MkVpcTGJkPTW3/tnS557Vos.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType2,
	cx as cx2,
	CycleVariantState,
	getFonts as getFonts2,
	useActiveVariantCallback,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useOnVariantChange,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";

// /:https://framerusercontent.com/modules/vA9goUwPzYBkH8QgIwI7/0HhvcCXVcbA15VPqBg1X/CXyBK6wov.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var ElementGlowRunningStrokeFonts = getFonts(stdin_default);
var MotionDivWithFX = withFX(motion.div);
var ImageWithFX = withFX(Image);
var cycleOrder = ["Bzaal16Oz", "VOreSDgHj"];
var serializationHash = "framer-txB5C";
var variantClassNames = {
	Bzaal16Oz: "framer-v-12dm3um",
	VOreSDgHj: "framer-v-zxlfig",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 1,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 0.98,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition2 = {
	delay: 0,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 0.98,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var transition3 = {
	delay: 5.7,
	duration: 0.8,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var transition4 = {
	delay: 0,
	duration: 0.8,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation3 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition4,
	x: 0,
	y: 0,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Active: "VOreSDgHj",
	Inactive: "Bzaal16Oz",
};
var getProps = ({ height, iconActive, id, labelTitle, width, ...props }) => {
	var _ref, _humanReadableVariantMap_props_variant, _ref1, _ref2;
	return {
		...props,
		hwe2DRarF:
			(_ref =
				labelTitle !== null && labelTitle !== void 0
					? labelTitle
					: props.hwe2DRarF) !== null && _ref !== void 0
				? _ref
				: "Trigger",
		variant:
			(_ref1 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref1 !== void 0
				? _ref1
				: "Bzaal16Oz",
		VDw2eKpLT:
			(_ref2 =
				iconActive !== null && iconActive !== void 0
					? iconActive
					: props.VDw2eKpLT) !== null && _ref2 !== void 0
				? _ref2
				: {
						src: "https://framerusercontent.com/images/XOnttL4leuqK6Du1BqhfhKbsrc.svg",
					},
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		hwe2DRarF,
		VDw2eKpLT,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "Bzaal16Oz",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (baseVariant === "VOreSDgHj") return true;
		return false;
	};
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-12dm3um",
							className2,
							classNames,
						)}
						data-framer-name={"Inactive"}
						layoutDependency={layoutDependency}
						layoutId={"Bzaal16Oz"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								VOreSDgHj: {
									"data-framer-name": "Active",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<ComponentViewportProvider
								{...addPropertyOverrides(
									{
										VOreSDgHj: {
											height:
												((componentViewport === null ||
												componentViewport === void 0
													? void 0
													: componentViewport.height) || 40) - 0,
											width:
												(componentViewport === null ||
												componentViewport === void 0
													? void 0
													: componentViewport.width) || "100vw",
											y:
												((componentViewport === null ||
												componentViewport === void 0
													? void 0
													: componentViewport.y) || 0) + 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<MotionDivWithFX
									__framer__animate={{
										transition: transition2,
									}}
									__framer__animateOnce={false}
									__framer__enter={animation}
									__framer__exit={animation1}
									__framer__loop={animation2}
									__framer__loopEffectEnabled={true}
									__framer__loopRepeatDelay={0}
									__framer__loopRepeatType={"loop"}
									__framer__loopTransition={transition3}
									__framer__styleAppearEffectEnabled={true}
									__framer__threshold={0.5}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-1u9aezh-container"}
									layoutDependency={layoutDependency}
									layoutId={"ez2NmOd_5-container"}
								>
									{_jsx(stdin_default, {
										height: "100%",
										id: "ez2NmOd_5",
										layoutId: "ez2NmOd_5",
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "G2l8IJrMG",
										width: "100%",
									})}
								</MotionDivWithFX>
							</ComponentViewportProvider>
						)}
						<motion.div
							className={"framer-1abjaga"}
							data-framer-name={"Card-Stroke"}
							layoutDependency={layoutDependency}
							layoutId={"FYhgsTals"}
							style={{
								background:
									'linear-gradient(141.3401922892204deg, var(--token-fab99bb1-2362-471f-8f94-4719e8b35bc0, rgb(61, 61, 61)) /* {"name":"Dark/200"} */ 0%, var(--token-4d67072c-df86-41a3-8260-1a48b41c6ca7, rgb(17, 17, 17)) /* {"name":"Dark/400"} */ 100%)',
								borderBottomLeftRadius: 8,
								borderBottomRightRadius: 8,
								borderTopLeftRadius: 8,
								borderTopRightRadius: 8,
							}}
						>
							<motion.div
								className={"framer-ehcqbl"}
								data-framer-name={"Card"}
								layoutDependency={layoutDependency}
								layoutId={"YTSNheeCm"}
								style={{
									backgroundColor:
										"var(--token-4d67072c-df86-41a3-8260-1a48b41c6ca7, rgb(17, 17, 17))",
									borderBottomLeftRadius: 7,
									borderBottomRightRadius: 7,
									borderTopLeftRadius: 7,
									borderTopRightRadius: 7,
								}}
							>
								<motion.div
									className={"framer-1rbpjnr"}
									data-framer-name={"Icon Stroke"}
									layoutDependency={layoutDependency}
									layoutId={"GXwvnmW1f"}
									style={{
										borderBottomLeftRadius: 6,
										borderBottomRightRadius: 6,
										borderTopLeftRadius: 6,
										borderTopRightRadius: 6,
									}}
								>
									<motion.div
										className={"framer-huytl0"}
										data-framer-name={"Background"}
										layoutDependency={layoutDependency}
										layoutId={"V1TUxNTkV"}
										style={{
											borderBottomLeftRadius: 5,
											borderBottomRightRadius: 5,
											borderTopLeftRadius: 5,
											borderTopRightRadius: 5,
										}}
									>
										<ImageWithFX
											__framer__animate={{
												transition: transition4,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation2}
											__framer__exit={animation3}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											background={{
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													((componentViewport === null ||
													componentViewport === void 0
														? void 0
														: componentViewport.y) || 0) +
														(1 +
															(((componentViewport === null ||
															componentViewport === void 0
																? void 0
																: componentViewport.height) || 40) -
																2 -
																38) /
																2) +
														1 +
														4 +
														1 +
														6,
												),
												pixelHeight: 20,
												pixelWidth: 20,
												sizes: "14px",
												...toResponsiveImage(VDw2eKpLT),
												...{
													positionX: "center",
													positionY: "center",
												},
											}}
											className={"framer-fldgm"}
											data-framer-name={"Icon"}
											layoutDependency={layoutDependency}
											layoutId={"CZ_RZJ4Sk"}
											style={{
												filter: "grayscale(1)",
												WebkitFilter: "grayscale(1)",
											}}
											variants={{
												VOreSDgHj: {
													filter: "grayscale(0)",
													WebkitFilter: "grayscale(0)",
												},
											}}
										/>
									</motion.div>
								</motion.div>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-eocgt5"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"Hc2Ub4Azz"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={hwe2DRarF}
									variants={{
										VOreSDgHj: {
											"--extracted-r6o4lv":
												"var(--token-b1fb3a8e-a88d-40f2-ad39-1f269e6b91e0, rgb(255, 255, 255))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											VOreSDgHj: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-12wg37s"}
															data-styles-preset={"n3IP9A5BI"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-b1fb3a8e-a88d-40f2-ad39-1f269e6b91e0, rgb(255, 255, 255)))",
															}}
														>
															{"Trigger"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-12wg37s"}
											data-styles-preset={"n3IP9A5BI"}
										>
											{"Trigger"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-txB5C.framer-6aa4p6, .framer-txB5C .framer-6aa4p6 { display: block; }",
	".framer-txB5C.framer-12dm3um { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 1px; position: relative; width: 140px; }",
	".framer-txB5C .framer-1u9aezh-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; }",
	".framer-txB5C .framer-1abjaga { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 38px; justify-content: center; padding: 1px; position: relative; width: 1px; }",
	".framer-txB5C .framer-ehcqbl { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: 100%; justify-content: flex-start; overflow: visible; padding: 5px; position: relative; width: 1px; }",
	".framer-txB5C .framer-1rbpjnr { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 28px; justify-content: center; overflow: visible; padding: 1px; position: relative; width: 28px; }",
	".framer-txB5C .framer-huytl0 { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 26px); justify-content: center; padding: 6px; position: relative; width: 1px; }",
	".framer-txB5C .framer-fldgm { flex: none; height: 14px; min-width: 13px; overflow: visible; position: relative; width: 14px; }",
	".framer-txB5C .framer-eocgt5 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-txB5C.framer-12dm3um, .framer-txB5C .framer-1abjaga, .framer-txB5C .framer-ehcqbl, .framer-txB5C .framer-1rbpjnr, .framer-txB5C .framer-huytl0 { gap: 0px; } .framer-txB5C.framer-12dm3um > *, .framer-txB5C .framer-1abjaga > *, .framer-txB5C .framer-1rbpjnr > *, .framer-txB5C .framer-huytl0 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-txB5C.framer-12dm3um > :first-child, .framer-txB5C .framer-1abjaga > :first-child, .framer-txB5C .framer-ehcqbl > :first-child, .framer-txB5C .framer-1rbpjnr > :first-child, .framer-txB5C .framer-huytl0 > :first-child { margin-left: 0px; } .framer-txB5C.framer-12dm3um > :last-child, .framer-txB5C .framer-1abjaga > :last-child, .framer-txB5C .framer-ehcqbl > :last-child, .framer-txB5C .framer-1rbpjnr > :last-child, .framer-txB5C .framer-huytl0 > :last-child { margin-right: 0px; } .framer-txB5C .framer-ehcqbl > * { margin: 0px; margin-left: calc(6px / 2); margin-right: calc(6px / 2); } }",
	".framer-txB5C.framer-v-zxlfig .framer-huytl0 { aspect-ratio: unset; height: 100%; }",
	...css,
];
var FramerCXyBK6wov = withCSS(Component, css2, "framer-txB5C");
var stdin_default2 = FramerCXyBK6wov;
FramerCXyBK6wov.displayName = "Line Step";
FramerCXyBK6wov.defaultProps = {
	height: 40,
	width: 140,
};
addPropertyControls(FramerCXyBK6wov, {
	variant: {
		options: ["Bzaal16Oz", "VOreSDgHj"],
		optionTitles: ["Inactive", "Active"],
		title: "Variant",
		type: ControlType.Enum,
	},
	hwe2DRarF: {
		defaultValue: "Trigger",
		displayTextArea: false,
		title: "Label Title",
		type: ControlType.String,
	},
	VDw2eKpLT: {
		__defaultAssetReference:
			"data:framer/asset-reference,XOnttL4leuqK6Du1BqhfhKbsrc.svg?originalFilename=settings+1+%281%29.svg&preferredSize=auto",
		title: "Icon Active",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerCXyBK6wov,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ElementGlowRunningStrokeFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/mgHktD2VGmZ3IWO3rbvZ/FgyhQ91MkVpcTGJkPTW3/tnS557Vos.js
var LineStepFonts = getFonts2(stdin_default2);
var cycleOrder2 = ["JBo3pqIPj", "gHBwe_C8J", "T0RjT2gsu"];
var serializationHash2 = "framer-lI2fc";
var variantClassNames2 = {
	gHBwe_C8J: "framer-v-9qax5l",
	JBo3pqIPj: "framer-v-lqm5pi",
	T0RjT2gsu: "framer-v-1aa3duh",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition12 = {
	delay: 0,
	duration: 2,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var addImageAlt = (image, alt) => {
	if (!image || typeof image !== "object") {
		return;
	}
	return {
		...image,
		alt,
	};
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	"Active 1": "JBo3pqIPj",
	"Active 2": "gHBwe_C8J",
	"Active 3": "T0RjT2gsu",
};
var getProps2 = ({ height, id, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap2[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "JBo3pqIPj",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo2();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "JBo3pqIPj",
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppear196ldst = activeVariantCallback(async (...args) => {
		await delay(() => setVariant(CycleVariantState), 6200);
	});
	useOnVariantChange(baseVariant, {
		default: onAppear196ldst,
	});
	const ref1 = React2.useRef(null);
	const defaultLayoutId = React2.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport2();
	return (
		<LayoutGroup2
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							serializationHash2,
							...sharedStyleClassNames,
							"framer-lqm5pi",
							className2,
							classNames,
						)}
						data-framer-name={"Active 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"JBo3pqIPj"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								gHBwe_C8J: {
									"data-framer-name": "Active 2",
								},
								T0RjT2gsu: {
									"data-framer-name": "Active 3",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-q2h2yy"}
							data-framer-name={"Line"}
							layoutDependency={layoutDependency}
							layoutId={"HDlgQzaTY"}
							style={{
								backgroundColor:
									"var(--token-4d6fb0aa-347b-4d07-918a-f12b70b08ad3, rgb(38, 38, 38))",
							}}
						/>
						<ComponentViewportProvider2
							height={40}
							y={
								((componentViewport === null || componentViewport === void 0
									? void 0
									: componentViewport.y) || 0) +
								0 +
								((((componentViewport === null || componentViewport === void 0
									? void 0
									: componentViewport.height) || 134) -
									0 -
									134) /
									2 +
									0 +
									0)
							}
						>
							<motion2.div
								className={"framer-fus75-container"}
								layoutDependency={layoutDependency}
								layoutId={"QUVK9vQ_a-container"}
							>
								{_jsx2(stdin_default2, {
									height: "100%",
									hwe2DRarF: "Trigger",
									id: "QUVK9vQ_a",
									layoutId: "QUVK9vQ_a",
									variant: "VOreSDgHj",
									VDw2eKpLT: addImageAlt(
										{
											src: "https://framerusercontent.com/images/c9Gh7XP4x4E6sMd2DeLSYdnLA.png",
										},
										"",
									),
									width: "100%",
									...addPropertyOverrides2(
										{
											gHBwe_C8J: {
												variant: "Bzaal16Oz",
											},
											T0RjT2gsu: {
												variant: "Bzaal16Oz",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion2.div>
						</ComponentViewportProvider2>
						<ComponentViewportProvider2
							height={40}
							y={
								((componentViewport === null || componentViewport === void 0
									? void 0
									: componentViewport.y) || 0) +
								0 +
								((((componentViewport === null || componentViewport === void 0
									? void 0
									: componentViewport.height) || 134) -
									0 -
									134) /
									2 +
									40 +
									7)
							}
						>
							<motion2.div
								className={"framer-85t89d-container"}
								layoutDependency={layoutDependency}
								layoutId={"Umfqup_ad-container"}
							>
								{_jsx2(stdin_default2, {
									height: "100%",
									hwe2DRarF: "Prompts",
									id: "Umfqup_ad",
									layoutId: "Umfqup_ad",
									variant: "Bzaal16Oz",
									VDw2eKpLT: addImageAlt(
										{
											src: "https://framerusercontent.com/images/3EjDBnc06ZqM2DalAwEiwBISOzc.png",
										},
										"",
									),
									width: "100%",
									...addPropertyOverrides2(
										{
											gHBwe_C8J: {
												variant: "VOreSDgHj",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion2.div>
						</ComponentViewportProvider2>
						<ComponentViewportProvider2
							height={40}
							y={
								((componentViewport === null || componentViewport === void 0
									? void 0
									: componentViewport.y) || 0) +
								0 +
								((((componentViewport === null || componentViewport === void 0
									? void 0
									: componentViewport.height) || 134) -
									0 -
									134) /
									2 +
									80 +
									14)
							}
						>
							<motion2.div
								className={"framer-vjfu9b-container"}
								layoutDependency={layoutDependency}
								layoutId={"pPRDsMhjB-container"}
							>
								{_jsx2(stdin_default2, {
									height: "100%",
									hwe2DRarF: "Send Email",
									id: "pPRDsMhjB",
									layoutId: "pPRDsMhjB",
									variant: "Bzaal16Oz",
									VDw2eKpLT: addImageAlt(
										{
											src: "https://framerusercontent.com/images/osFEtXrggbbUFT2PcLhEKwtKw.png",
										},
										"",
									),
									width: "100%",
									...addPropertyOverrides2(
										{
											T0RjT2gsu: {
												variant: "VOreSDgHj",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion2.div>
						</ComponentViewportProvider2>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-lI2fc.framer-stcdvm, .framer-lI2fc .framer-stcdvm { display: block; }",
	".framer-lI2fc.framer-lqm5pi { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 7px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-lI2fc .framer-q2h2yy { bottom: 20px; flex: none; left: calc(50.279329608938575% - 1px / 2); overflow: hidden; position: absolute; top: 20px; width: 1px; }",
	".framer-lI2fc .framer-fus75-container, .framer-lI2fc .framer-85t89d-container, .framer-lI2fc .framer-vjfu9b-container { flex: none; height: auto; position: relative; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-lI2fc.framer-lqm5pi { gap: 0px; } .framer-lI2fc.framer-lqm5pi > * { margin: 0px; margin-bottom: calc(7px / 2); margin-top: calc(7px / 2); } .framer-lI2fc.framer-lqm5pi > :first-child { margin-top: 0px; } .framer-lI2fc.framer-lqm5pi > :last-child { margin-bottom: 0px; } }",
];
var FramertnS557Vos = withCSS2(Component2, css3, "framer-lI2fc");
var stdin_default3 = FramertnS557Vos;
FramertnS557Vos.displayName = "Line Wrap";
FramertnS557Vos.defaultProps = {
	height: 134,
	width: 140,
};
addPropertyControls2(FramertnS557Vos, {
	variant: {
		options: ["JBo3pqIPj", "gHBwe_C8J", "T0RjT2gsu"],
		optionTitles: ["Active 1", "Active 2", "Active 3"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts2(
	FramertnS557Vos,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...LineStepFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:line-wrap
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "JBo3pqIPj",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a6e0de7208a6e203a13a02c0c2342fdcb8c3548bcbc64ba40bb03307875e0fbf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders LineWrapFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a6e0de7208a6e203a13a02c0c2342fdcb8c3548bcbc64ba40bb03307875e0fbf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var line_wrap_default = ComponentWithRoot;
export { line_wrap_default as default };
