// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project a6e0de7208a6e203 "VeeBran", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * children?: React.ReactNode[] // children
 * gravityY?: number // Gravity Y
 * gravityX?: number // Gravity X
 * walls?: {top: boolean, bottom: boolean, right: boolean, left: boolean // Walls
 * mouse?: {enable: boolean, angularStiffness: number, stiffness: number // Mouse
 * friction?: {friction: number, frictionAir: number // friction
 * density?: {enable: boolean, density: number // Density
}} Props

 */
import { Physics } from "./chunks/chunk-GD26GQNW.js";
import { routes } from "./chunks/chunk-ID6ACFOJ.js";

// virtual:physics
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a6e0de7208a6e203a13a02c0c2342fdcb8c3548bcbc64ba40bb03307875e0fbf"
			}
			locale={locale}
			locales={locales}
		>
			<Physics {...rest} />
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PhysicsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a6e0de7208a6e203a13a02c0c2342fdcb8c3548bcbc64ba40bb03307875e0fbf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={Physics}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, Physics);
var physics_default = ComponentWithRoot;
export { physics_default as default };
