// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project a6e0de7208a6e203 "VeeBran", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' | 'Variant 4' // Variant
 * color?: string // Color
}} Props

 */
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "../chunks/chunk-ONDWJXSP.js";
import { stdin_default as stdin_default2 } from "../chunks/chunk-LVDCOD2Z.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "../chunks/chunk-23QBYHU2.js";
import { stdin_default } from "../chunks/chunk-APKMYPFC.js";
import "../chunks/chunk-FKIQ7FXH.js";
import "../chunks/chunk-66EJKQKM.js";
import "../chunks/chunk-NULYBL27.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "../chunks/chunk-WF6ASFEM.js";
import { className, css, fonts } from "../chunks/chunk-A53DKFKD.js";
import { routes } from "../chunks/chunk-ID6ACFOJ.js";

// virtual:section/footer
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/egpIsWBL1NSX6NnW3q16/v0cQslisoQMGxflOOznl/iH9yd5Wn7.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/iAS0quANhJBskTlAyGt0/iT3d9yQ6hFeLwOmmD1pg/rDTuixtIv.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"FS;Satoshi-medium",
	"FS;Satoshi-bold",
	"FS;Satoshi-bold italic",
	"FS;Satoshi-medium italic",
]);
var fonts5 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Satoshi",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/P2LQKHE6KA6ZP4AAGN72KDWMHH6ZH3TA/ZC32TK2P7FPS5GFTL46EU6KQJA24ZYDB/7AHDUZ4A7LFLVFUIFSARGIWCRQJHISQP.woff2",
				weight: "500",
			},
			{
				family: "Satoshi",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/LAFFD4SDUCDVQEXFPDC7C53EQ4ZELWQI/PXCT3G6LO6ICM5I3NTYENYPWJAECAWDD/GHM6WVH6MILNYOOCXHXB5GTSGNTMGXZR.woff2",
				weight: "700",
			},
			{
				family: "Satoshi",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/CDEBEFT2R7XKNGXSBBLZGMY4MMHZG75P/HEVKDGQCYDZ7Z6CDVR2ZQGBCTUD6ZARH/BKWEE3VKGTFABE37K2DTH625VUSN2N35.woff2",
				weight: "700",
			},
			{
				family: "Satoshi",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/NID3I7RITWZSKXRCJGOCMP5NOADJK6IG/2HLHGD7OBTWCOHW64YXOE5KFXHU4KJHM/ZHME2QIRFR7UPJ47NLY27RCAFY44CKZJ.woff2",
				weight: "500",
			},
		],
	},
];
var css5 = [
	'.framer-buh6B .framer-styles-preset-1mb7oeh:not(.rich-text-wrapper), .framer-buh6B .framer-styles-preset-1mb7oeh.rich-text-wrapper h3 { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 48px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -1px; --framer-line-height: 1.25em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-b1fb3a8e-a88d-40f2-ad39-1f269e6b91e0, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: capitalize; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-buh6B .framer-styles-preset-1mb7oeh:not(.rich-text-wrapper), .framer-buh6B .framer-styles-preset-1mb7oeh.rich-text-wrapper h3 { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 38px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -1px; --framer-line-height: 1.25em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-b1fb3a8e-a88d-40f2-ad39-1f269e6b91e0, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: capitalize; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-buh6B .framer-styles-preset-1mb7oeh:not(.rich-text-wrapper), .framer-buh6B .framer-styles-preset-1mb7oeh.rich-text-wrapper h3 { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 27px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -1px; --framer-line-height: 1.25em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-b1fb3a8e-a88d-40f2-ad39-1f269e6b91e0, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: capitalize; } }',
];
var className5 = "framer-buh6B";

// /:https://framerusercontent.com/modules/egpIsWBL1NSX6NnW3q16/v0cQslisoQMGxflOOznl/iH9yd5Wn7.js
var ElementBackgroundDotsXLFonts = getFonts(stdin_default2);
var ImageWithFX = withFX(Image);
var RichTextWithFX = withFX(RichText);
var ButtonButtonFonts = getFonts(stdin_default);
var SmartComponentScopedContainerWithFX = withFX(SmartComponentScopedContainer);
var MotionDivWithFX = withFX(motion.div);
var cycleOrder = ["X76dN2SSh", "p4KNEh_xU", "JiIq5YNIP", "OYezazs8l"];
var serializationHash = "framer-idiYh";
var variantClassNames = {
	JiIq5YNIP: "framer-v-t15dn6",
	OYezazs8l: "framer-v-1e61xx7",
	p4KNEh_xU: "framer-v-em5pde",
	X76dN2SSh: "framer-v-ps2hmr",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 15,
};
var transition2 = {
	damping: 70,
	delay: 0,
	mass: 1,
	stiffness: 210,
	type: "spring",
};
var transition3 = {
	damping: 70,
	delay: 0.05,
	mass: 1,
	stiffness: 210,
	type: "spring",
};
var transition4 = {
	damping: 70,
	delay: 0.1,
	mass: 1,
	stiffness: 210,
	type: "spring",
};
var transition5 = {
	damping: 70,
	delay: 0.15,
	mass: 1,
	stiffness: 210,
	type: "spring",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition6 = {
	delay: 0.8,
	duration: 1.5,
	ease: [0.12, 0.23, 0.5, 1],
	type: "tween",
};
var transition7 = {
	damping: 70,
	delay: 0.2,
	mass: 1,
	stiffness: 210,
	type: "spring",
};
var transition8 = {
	damping: 70,
	delay: 0.25,
	mass: 1,
	stiffness: 210,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 4": "OYezazs8l",
	Desktop: "X76dN2SSh",
	Phone: "JiIq5YNIP",
	Tablet: "p4KNEh_xU",
};
var getProps = ({ color, height, id, width, ...props }) => {
	return {
		...props,
		T6gFUZS_O: color ?? props.T6gFUZS_O ?? "rgb(0, 74, 173)",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "X76dN2SSh",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className6,
		layoutId,
		variant,
		T6gFUZS_O,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "X76dN2SSh",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1717hfj = activeVariantCallback(async (...args) => {
		setVariant("JiIq5YNIP");
	});
	const sharedStyleClassNames = [
		className5,
		className2,
		className,
		className3,
		className4,
	];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const router = useRouter();
	const isDisplayed = () => {
		if (["JiIq5YNIP", "OYezazs8l"].includes(baseVariant)) return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (["JiIq5YNIP", "OYezazs8l"].includes(baseVariant)) return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.footer
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-ps2hmr",
							className6,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"X76dN2SSh"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								JiIq5YNIP: {
									"data-framer-name": "Phone",
								},
								OYezazs8l: {
									"data-framer-name": "Variant 4",
								},
								p4KNEh_xU: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-3o98s2"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"XHgPFS6ZV"}
						>
							<motion.div
								className={"framer-1u0y235"}
								data-framer-name={"Stroke"}
								layoutDependency={layoutDependency}
								layoutId={"sFQWi7HCB"}
								style={{
									background:
										"linear-gradient(180deg, rgba(33, 33, 33, 0.6) 0%, var(--token-70b4ad58-9042-4a72-8dea-68d8a9efadf0, rgb(13, 13, 13)) 100%)",
									borderBottomLeftRadius: 23,
									borderBottomRightRadius: 23,
									borderTopLeftRadius: 23,
									borderTopRightRadius: 23,
								}}
								variants={{
									JiIq5YNIP: {
										borderBottomLeftRadius: 26,
										borderBottomRightRadius: 26,
										borderTopLeftRadius: 26,
										borderTopRightRadius: 26,
									},
									OYezazs8l: {
										borderBottomLeftRadius: 26,
										borderBottomRightRadius: 26,
										borderTopLeftRadius: 26,
										borderTopRightRadius: 26,
									},
								}}
							>
								<motion.div
									className={"framer-19utmyd"}
									data-framer-name={"Footer Card"}
									layoutDependency={layoutDependency}
									layoutId={"jfF98QJss"}
									style={{
										backgroundColor:
											"var(--token-c311f7eb-2396-4f7f-8edd-f790b3c42ec3, rgb(5, 5, 5))",
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									}}
									variants={{
										JiIq5YNIP: {
											borderBottomLeftRadius: 23,
											borderBottomRightRadius: 23,
											borderTopLeftRadius: 23,
											borderTopRightRadius: 23,
										},
										OYezazs8l: {
											borderBottomLeftRadius: 23,
											borderBottomRightRadius: 23,
											borderTopLeftRadius: 23,
											borderTopRightRadius: 23,
										},
									}}
								>
									<ComponentViewportProvider
										height={1024.7}
										width={`calc((max(min(max(${componentViewport?.width || "100vw"} - 120px, 1px), 1228px), 1px) - 2px) * 1.04)`}
										y={
											(componentViewport?.y || 0) +
											(0 +
												((componentViewport?.height || 841) - 60 - 996.2) / 2) +
											0 +
											1 +
											0 +
											-2.086
										}
										{...addPropertyOverrides(
											{
												JiIq5YNIP: {
													height: 817.5,
													width: `calc((max(min(max(${componentViewport?.width || "100vw"} - 40px, 1px), 1228px), 1px) - 2px) * 1.04)`,
													y:
														(componentViewport?.y || 0) +
														(0 +
															((componentViewport?.height || 801) - 20 - 789) /
															2) +
														0 +
														1 +
														0 +
														-2.086,
												},
												OYezazs8l: {
													height: 817.5,
													width: `calc((max(min(max(${componentViewport?.width || "100vw"} - 40px, 1px), 1228px), 1px) - 2px) * 1.04)`,
													y:
														(componentViewport?.y || 0) +
														(0 +
															((componentViewport?.height || 801) - 20 - 789) /
															2) +
														0 +
														1 +
														0 +
														-2.086,
												},
												p4KNEh_xU: {
													height: 949.7,
													width: `calc((max(min(max(${componentViewport?.width || "100vw"} - 64px, 1px), 1228px), 1px) - 2px) * 1.04)`,
													y:
														(componentViewport?.y || 0) +
														(0 +
															((componentViewport?.height || 738) -
																32 -
																921.2) /
															2) +
														0 +
														1 +
														0 +
														-2.086,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-1cj0n6x-container"}
											layoutDependency={layoutDependency}
											layoutId={"p_bworbbo-container"}
											nodeId={"p_bworbbo"}
											rendersWithMotion={true}
											scopeId={"iH9yd5Wn7"}
											style={{
												rotateY: 180,
											}}
										>
											{_jsx(stdin_default2, {
												height: "100%",
												id: "p_bworbbo",
												layoutId: "p_bworbbo",
												style: {
													height: "100%",
													width: "100%",
												},
												variant: "WcACx4dJr",
												width: "100%",
												...addPropertyOverrides(
													{
														JiIq5YNIP: {
															variant: "eWZ_RAwHS",
														},
														OYezazs8l: {
															variant: "eWZ_RAwHS",
														},
														p4KNEh_xU: {
															variant: "LWG_1Ts8M",
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<motion.div
										className={"framer-mx0x8l"}
										data-framer-name={"Gradient"}
										layoutDependency={layoutDependency}
										layoutId={"eH97C5I8Q"}
										style={{
											background:
												"linear-gradient(180deg, var(--token-ca0eb946-0278-4b5f-be23-d71665cd022d, rgba(17, 17, 17, 0)) 0%, var(--token-c311f7eb-2396-4f7f-8edd-f790b3c42ec3, rgb(5, 5, 5)) 100%)",
											opacity: 0.87,
										}}
										variants={{
											JiIq5YNIP: {
												opacity: 0.8,
											},
											OYezazs8l: {
												opacity: 0.8,
											},
										}}
									/>
									<motion.div
										className={"framer-19fvdhy"}
										data-framer-name={"Footer Top"}
										layoutDependency={layoutDependency}
										layoutId={"lf96Pt5z3"}
									>
										<ImageWithFX
											__framer__animate={{
												transition: transition2,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											background={{
												alt: "",
												fit: "fit",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
													(0 +
														((componentViewport?.height || 841) -
															60 -
															996.2) /
														2) +
													0 +
													1 +
													0 +
													90 +
													0 +
													0 +
													0,
												),
												pixelHeight: 1695,
												pixelWidth: 7801,
												positionX: "center",
												positionY: "center",
												src: "https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png",
											}}
											className={"framer-guex1l"}
											data-framer-name={"Logo"}
											layoutDependency={layoutDependency}
											layoutId={"c0fKkmcwL"}
											{...addPropertyOverrides(
												{
													JiIq5YNIP: {
														background: {
															alt: "",
															fit: "fit",
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																(0 +
																	((componentViewport?.height || 801) -
																		20 -
																		789) /
																	2) +
																0 +
																1 +
																0 +
																45 +
																0 +
																0 +
																0,
															),
															pixelHeight: 1695,
															pixelWidth: 7801,
															positionX: "center",
															positionY: "center",
															src: "https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png",
														},
													},
													OYezazs8l: {
														background: {
															alt: "",
															fit: "fit",
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																(0 +
																	((componentViewport?.height || 801) -
																		20 -
																		789) /
																	2) +
																0 +
																1 +
																0 +
																45 +
																0 +
																0 +
																0,
															),
															pixelHeight: 1695,
															pixelWidth: 7801,
															positionX: "center",
															positionY: "center",
															src: "https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png",
														},
													},
													p4KNEh_xU: {
														background: {
															alt: "",
															fit: "fit",
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																(0 +
																	((componentViewport?.height || 738) -
																		32 -
																		921.2) /
																	2) +
																0 +
																1 +
																0 +
																60 +
																0 +
																0 +
																0,
															),
															pixelHeight: 1695,
															pixelWidth: 7801,
															positionX: "center",
															positionY: "center",
															src: "https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png",
														},
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
										<RichTextWithFX
											__framer__animate={{
												transition: transition3,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0}
											__fromCanvasComponent={true}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-1le974u"}
											fonts={["Inter", "Inter-Italic"]}
											layoutDependency={layoutDependency}
											layoutId={"D5AN4ydX6"}
											style={{
												"--extracted-a0htzi":
													"var(--variable-reference-T6gFUZS_O-iH9yd5Wn7)",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
												"--variable-reference-T6gFUZS_O-iH9yd5Wn7": T6gFUZS_O,
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.h3
													className={"framer-styles-preset-1mb7oeh"}
													data-styles-preset={"rDTuixtIv"}
													style={{
														"--framer-text-alignment": "center",
														"--framer-text-color":
															"var(--extracted-a0htzi, var(--variable-reference-T6gFUZS_O-iH9yd5Wn7))",
													}}
												>
													<motion.em>{"LET'S SUCCEED TOGETHER"}</motion.em>
												</motion.h3>
											</React.Fragment>
										</RichTextWithFX>
										<RichTextWithFX
											__framer__animate={{
												transition: transition4,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0}
											__fromCanvasComponent={true}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-fch4id"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"h93Cy8jBJ"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, rgb(133, 133, 133))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1237v2y"}
													data-styles-preset={"wRTC8eDCA"}
													style={{
														"--framer-text-alignment": "center",
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, rgb(133, 133, 133)))",
													}}
												>
													{
														"We bring your vision to life with creativity and precision. Let\u2019s make it happen."
													}
												</motion.p>
											</React.Fragment>
										</RichTextWithFX>
										<ResolveLinks
											links={[
												{
													href: {
														webPageId: "O9HKScYjf",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "O9HKScYjf",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "O9HKScYjf",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "O9HKScYjf",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks) => (
												<ComponentViewportProvider
													height={52}
													y={
														(componentViewport?.y || 0) +
														(0 +
															((componentViewport?.height || 841) -
																60 -
																996.2) /
															2) +
														0 +
														1 +
														0 +
														90 +
														0 +
														0 +
														375
													}
													{...addPropertyOverrides(
														{
															JiIq5YNIP: {
																y:
																	(componentViewport?.y || 0) +
																	(0 +
																		((componentViewport?.height || 801) -
																			20 -
																			789) /
																		2) +
																	0 +
																	1 +
																	0 +
																	45 +
																	0 +
																	0 +
																	371,
															},
															OYezazs8l: {
																y:
																	(componentViewport?.y || 0) +
																	(0 +
																		((componentViewport?.height || 801) -
																			20 -
																			789) /
																		2) +
																	0 +
																	1 +
																	0 +
																	45 +
																	0 +
																	0 +
																	371,
															},
															p4KNEh_xU: {
																y:
																	(componentViewport?.y || 0) +
																	(0 +
																		((componentViewport?.height || 738) -
																			32 -
																			921.2) /
																		2) +
																	0 +
																	1 +
																	0 +
																	60 +
																	0 +
																	0 +
																	375,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainerWithFX
														__framer__animate={{
															transition: transition5,
														}}
														__framer__animateOnce={true}
														__framer__enter={animation}
														__framer__styleAppearEffectEnabled={true}
														__framer__threshold={0}
														__perspectiveFX={false}
														__smartComponentFX={true}
														__targetOpacity={1}
														className={"framer-10arsp8-container"}
														layoutDependency={layoutDependency}
														layoutId={"zeLqBkYhk-container"}
														nodeId={"zeLqBkYhk"}
														rendersWithMotion={true}
														scopeId={"iH9yd5Wn7"}
													>
														{_jsx(stdin_default, {
															height: "100%",
															id: "zeLqBkYhk",
															layoutId: "zeLqBkYhk",
															mhjqxqWNT: resolvedLinks[0],
															mZ1MxQ6wB: "Book A Call",
															variant: "ZGGyVgByj",
															width: "100%",
															...addPropertyOverrides(
																{
																	JiIq5YNIP: {
																		mhjqxqWNT: resolvedLinks[2],
																	},
																	OYezazs8l: {
																		mhjqxqWNT: resolvedLinks[3],
																	},
																	p4KNEh_xU: {
																		mhjqxqWNT: resolvedLinks[1],
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainerWithFX>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
									</motion.div>
									<MotionDivWithFX
										__framer__animate={{
											transition: transition6,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation1}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-ug0b83"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"CymQM4deG"}
										style={{
											background:
												"linear-gradient(90deg, var(--token-ca0eb946-0278-4b5f-be23-d71665cd022d, rgba(17, 17, 17, 0)) 0%, var(--token-4d6fb0aa-347b-4d07-918a-f12b70b08ad3, rgb(38, 38, 38)) 25%, var(--token-4d6fb0aa-347b-4d07-918a-f12b70b08ad3, rgb(38, 38, 38)) 75%, var(--token-ca0eb946-0278-4b5f-be23-d71665cd022d, rgba(17, 17, 17, 0)) 100%)",
										}}
									/>
									<motion.div
										className={"framer-1oxmrzg"}
										data-framer-name={"Footer Bottom"}
										layoutDependency={layoutDependency}
										layoutId={"vHmvykgmJ"}
									>
										<MotionDivWithFX
											__framer__animate={{
												transition: transition7,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-1gg2qux"}
											data-framer-name={"Footer Nav"}
											layoutDependency={layoutDependency}
											layoutId={"bVqlbeNqC"}
										>
											<motion.div
												className={"framer-nhi4rf"}
												data-framer-name={"Link Row 2"}
												layoutDependency={layoutDependency}
												layoutId={"SN7Rd3em2"}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-1297xae"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"bIZol88Yd"}
													verticalAlignment={"top"}
													withExternalLayout={true}
													{...addPropertyOverrides(
														{
															JiIq5YNIP: {
																children: (
																	<React.Fragment>
																		<motion.p
																			className={"framer-styles-preset-12wg37s"}
																			data-styles-preset={"n3IP9A5BI"}
																			style={{
																				"--framer-text-alignment": "center",
																			}}
																		>
																			{"Email: vishva@veebran.com"}
																		</motion.p>
																	</React.Fragment>
																),
															},
															OYezazs8l: {
																children: (
																	<React.Fragment>
																		<motion.p
																			className={"framer-styles-preset-12wg37s"}
																			data-styles-preset={"n3IP9A5BI"}
																			style={{
																				"--framer-text-alignment": "center",
																			}}
																		>
																			{"Email: vishva@veebran.com"}
																		</motion.p>
																	</React.Fragment>
																),
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-bkongl"}
															data-styles-preset={"IEx8UeCkP"}
															style={{
																"--framer-text-alignment": "center",
															}}
														>
															{"Email: vishva@veebran.com"}
														</motion.p>
													</React.Fragment>
												</RichText>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-isbs89"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"xjSpeFUIj"}
													verticalAlignment={"top"}
													withExternalLayout={true}
													{...addPropertyOverrides(
														{
															JiIq5YNIP: {
																children: (
																	<React.Fragment>
																		<motion.p
																			className={"framer-styles-preset-12wg37s"}
																			data-styles-preset={"n3IP9A5BI"}
																			style={{
																				"--framer-text-alignment": "center",
																			}}
																		>
																			{"Location: India"}
																		</motion.p>
																	</React.Fragment>
																),
															},
															OYezazs8l: {
																children: (
																	<React.Fragment>
																		<motion.p
																			className={"framer-styles-preset-12wg37s"}
																			data-styles-preset={"n3IP9A5BI"}
																			style={{
																				"--framer-text-alignment": "center",
																			}}
																		>
																			{"Location: India"}
																		</motion.p>
																	</React.Fragment>
																),
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-bkongl"}
															data-styles-preset={"IEx8UeCkP"}
															style={{
																"--framer-text-alignment": "center",
															}}
														>
															{"Location: India"}
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.div>
											{isDisplayed() && (
												<motion.div
													className={"framer-167srki"}
													data-framer-name={"Footer Bottom"}
													layoutDependency={layoutDependency}
													layoutId={"I14TIzf8g"}
												>
													<MotionDivWithFX
														__framer__animate={{
															transition: transition7,
														}}
														__framer__animateOnce={true}
														__framer__enter={animation}
														__framer__styleAppearEffectEnabled={true}
														__framer__threshold={0}
														__perspectiveFX={false}
														__smartComponentFX={true}
														__targetOpacity={1}
														className={"framer-udbgom"}
														data-framer-name={"Footer Nav"}
														data-highlight={true}
														layoutDependency={layoutDependency}
														layoutId={"YTRqYY7q1"}
														onTap={onTap1717hfj}
													>
														<motion.div
															className={"framer-v05f94"}
															data-framer-name={"Link Row 1"}
															layoutDependency={layoutDependency}
															layoutId={"vnhAI37tl"}
														>
															<RichText
																__fromCanvasComponent={true}
																className={"framer-elm8fy"}
																fonts={["Inter"]}
																layoutDependency={layoutDependency}
																layoutId={"tObjE2Cvs"}
																verticalAlignment={"top"}
																withExternalLayout={true}
															>
																<React.Fragment>
																	<motion.p
																		className={"framer-styles-preset-12wg37s"}
																		data-styles-preset={"n3IP9A5BI"}
																		style={{
																			"--framer-text-alignment": "center",
																		}}
																	>
																		<Link
																			href={"/#why-us"}
																			motionChild={true}
																			nodeId={"tObjE2Cvs"}
																			openInNewTab={false}
																			scopeId={"iH9yd5Wn7"}
																			smoothScroll={false}
																		>
																			<motion.a
																				className={
																					"framer-styles-preset-rzeatr"
																				}
																				data-styles-preset={"NUFyQ_G3b"}
																			>
																				{"Why Us"}
																			</motion.a>
																		</Link>
																	</motion.p>
																</React.Fragment>
															</RichText>
															<RichText
																__fromCanvasComponent={true}
																className={"framer-1pnc7d9"}
																fonts={["Inter"]}
																layoutDependency={layoutDependency}
																layoutId={"oDN67fggP"}
																verticalAlignment={"top"}
																withExternalLayout={true}
															>
																<React.Fragment>
																	<motion.p
																		className={"framer-styles-preset-12wg37s"}
																		data-styles-preset={"n3IP9A5BI"}
																		style={{
																			"--framer-text-alignment": "center",
																		}}
																	>
																		<Link
																			href={"/#mission"}
																			motionChild={true}
																			nodeId={"oDN67fggP"}
																			openInNewTab={false}
																			scopeId={"iH9yd5Wn7"}
																			smoothScroll={false}
																		>
																			<motion.a
																				className={
																					"framer-styles-preset-rzeatr"
																				}
																				data-styles-preset={"NUFyQ_G3b"}
																			>
																				{"Mission"}
																			</motion.a>
																		</Link>
																	</motion.p>
																</React.Fragment>
															</RichText>

														</motion.div>
														<motion.div
															className={"framer-128cvz7"}
															data-framer-name={"Link Row 2"}
															layoutDependency={layoutDependency}
															layoutId={"KIk3EnP29"}
														>
															<RichText
																__fromCanvasComponent={true}
																className={"framer-palyqq"}
																fonts={["Inter"]}
																layoutDependency={layoutDependency}
																layoutId={"tEMG3F35b"}
																verticalAlignment={"top"}
																withExternalLayout={true}
															>
																<React.Fragment>
																	<motion.p
																		className={"framer-styles-preset-12wg37s"}
																		data-styles-preset={"n3IP9A5BI"}
																		style={{
																			"--framer-text-alignment": "center",
																		}}
																	>
																		<Link
																			href={"/#services"}
																			motionChild={true}
																			nodeId={"tEMG3F35b"}
																			openInNewTab={false}
																			scopeId={"iH9yd5Wn7"}
																			smoothScroll={false}
																		>
																			<motion.a
																				className={
																					"framer-styles-preset-rzeatr"
																				}
																				data-styles-preset={"NUFyQ_G3b"}
																			>
																				{"Services"}
																			</motion.a>
																		</Link>
																	</motion.p>
																</React.Fragment>
															</RichText>
															<RichText
																__fromCanvasComponent={true}
																className={"framer-1tre0kp"}
																fonts={["Inter"]}
																layoutDependency={layoutDependency}
																layoutId={"IjFqf9NM7"}
																verticalAlignment={"top"}
																withExternalLayout={true}
															>
																<React.Fragment>
																	<motion.p
																		className={"framer-styles-preset-12wg37s"}
																		data-styles-preset={"n3IP9A5BI"}
																		style={{
																			"--framer-text-alignment": "center",
																		}}
																	>
																		<Link
																			href={{
																				webPageId: "O9HKScYjf",
																			}}
																			motionChild={true}
																			nodeId={"IjFqf9NM7"}
																			openInNewTab={false}
																			scopeId={"iH9yd5Wn7"}
																			smoothScroll={false}
																		>
																			<motion.a
																				className={
																					"framer-styles-preset-rzeatr"
																				}
																				data-styles-preset={"NUFyQ_G3b"}
																			>
																				{"Contact"}
																			</motion.a>
																		</Link>
																	</motion.p>
																</React.Fragment>
															</RichText>
															<RichText
																__fromCanvasComponent={true}
																className={"framer-1nc74bi"}
																data-framer-name={"T & C"}
																fonts={["Inter"]}
																layoutDependency={layoutDependency}
																layoutId={"r49WUiP6C"}
																verticalAlignment={"top"}
																withExternalLayout={true}
															>
																<React.Fragment>
																	<motion.p
																		className={"framer-styles-preset-12wg37s"}
																		data-styles-preset={"n3IP9A5BI"}
																		style={{
																			"--framer-text-alignment": "center",
																		}}
																	>
																		<Link
																			href={{
																				webPageId: "Po_UhMe4P",
																			}}
																			motionChild={true}
																			nodeId={"r49WUiP6C"}
																			openInNewTab={false}
																			scopeId={"iH9yd5Wn7"}
																			smoothScroll={false}
																		>
																			<motion.a
																				className={
																					"framer-styles-preset-rzeatr"
																				}
																				data-styles-preset={"NUFyQ_G3b"}
																			>
																				{"T & C"}
																			</motion.a>
																		</Link>
																	</motion.p>
																</React.Fragment>
															</RichText>
														</motion.div>
													</MotionDivWithFX>
													<RichTextWithFX
														__framer__animate={{
															transition: transition8,
														}}
														__framer__animateOnce={true}
														__framer__enter={animation}
														__framer__styleAppearEffectEnabled={true}
														__framer__threshold={0}
														__fromCanvasComponent={true}
														__perspectiveFX={false}
														__smartComponentFX={true}
														__targetOpacity={1}
														className={"framer-1jbith2"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"NY9geUIKB"}
														style={{
															"--extracted-r6o4lv":
																"var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, rgb(133, 133, 133))",
															"--framer-link-text-color": "rgb(0, 153, 255)",
															"--framer-link-text-decoration": "underline",
														}}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-12wg37s"}
																data-styles-preset={"n3IP9A5BI"}
																style={{
																	"--framer-text-alignment": "center",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, rgb(133, 133, 133)))",
																}}
															>
																{'Copyright "VeeBran". All rights reserved.'}
															</motion.p>
														</React.Fragment>
													</RichTextWithFX>
												</motion.div>
											)}
										</MotionDivWithFX>
									</motion.div>
									{isDisplayed1() && (
										<motion.div
											className={"framer-1wwn5p8"}
											data-framer-name={"Footer Bottom"}
											layoutDependency={layoutDependency}
											layoutId={"GKGz6kQU0"}
										>
											<MotionDivWithFX
												__framer__animate={{
													transition: transition7,
												}}
												__framer__animateOnce={true}
												__framer__enter={animation}
												__framer__styleAppearEffectEnabled={true}
												__framer__threshold={0}
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												className={"framer-chifgp"}
												data-framer-name={"Footer Nav"}
												layoutDependency={layoutDependency}
												layoutId={"gpdbY0TPN"}
											>
												<motion.div
													className={"framer-16lcbtt"}
													data-framer-name={"Link Row 1"}
													layoutDependency={layoutDependency}
													layoutId={"txRkM25xe"}
												>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-ha3huj"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"HaAIStTws"}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-1237v2y"}
																data-styles-preset={"wRTC8eDCA"}
																style={{
																	"--framer-text-alignment": "center",
																}}
															>
																<Link
																	href={"/#why-us"}
																	motionChild={true}
																	nodeId={"HaAIStTws"}
																	openInNewTab={false}
																	scopeId={"iH9yd5Wn7"}
																	smoothScroll={false}
																>
																	<motion.a
																		className={"framer-styles-preset-rzeatr"}
																		data-styles-preset={"NUFyQ_G3b"}
																	>
																		{"Why Us"}
																	</motion.a>
																</Link>
															</motion.p>
														</React.Fragment>
													</RichText>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-1ojsxil"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"K7Aje3uxz"}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-1237v2y"}
																data-styles-preset={"wRTC8eDCA"}
																style={{
																	"--framer-text-alignment": "center",
																}}
															>
																<Link
																	href={"/#mission"}
																	motionChild={true}
																	nodeId={"K7Aje3uxz"}
																	openInNewTab={false}
																	scopeId={"iH9yd5Wn7"}
																	smoothScroll={false}
																>
																	<motion.a
																		className={"framer-styles-preset-rzeatr"}
																		data-styles-preset={"NUFyQ_G3b"}
																	>
																		{"Mission"}
																	</motion.a>
																</Link>
															</motion.p>
														</React.Fragment>
													</RichText>

												</motion.div>
												<motion.div
													className={"framer-16itjwm"}
													data-framer-name={"Link Row 2"}
													layoutDependency={layoutDependency}
													layoutId={"chhn8RA2E"}
												>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-8sjpkz"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"ZFeR_0q7P"}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-1237v2y"}
																data-styles-preset={"wRTC8eDCA"}
																style={{
																	"--framer-text-alignment": "center",
																}}
															>
																<Link
																	href={"/#services"}
																	motionChild={true}
																	nodeId={"ZFeR_0q7P"}
																	openInNewTab={false}
																	scopeId={"iH9yd5Wn7"}
																	smoothScroll={false}
																>
																	<motion.a
																		className={"framer-styles-preset-rzeatr"}
																		data-styles-preset={"NUFyQ_G3b"}
																	>
																		{"Services"}
																	</motion.a>
																</Link>
															</motion.p>
														</React.Fragment>
													</RichText>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-fl5bpi"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"GlUIYERz9"}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-1237v2y"}
																data-styles-preset={"wRTC8eDCA"}
																style={{
																	"--framer-text-alignment": "center",
																}}
															>
																<Link
																	href={{
																		webPageId: "O9HKScYjf",
																	}}
																	motionChild={true}
																	nodeId={"GlUIYERz9"}
																	openInNewTab={false}
																	scopeId={"iH9yd5Wn7"}
																	smoothScroll={false}
																>
																	<motion.a
																		className={"framer-styles-preset-rzeatr"}
																		data-styles-preset={"NUFyQ_G3b"}
																	>
																		{"Contact"}
																	</motion.a>
																</Link>
															</motion.p>
														</React.Fragment>
													</RichText>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-vfo5s9"}
														data-framer-name={"Terms & Conditions"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"VHIfhNryJ"}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-1237v2y"}
																data-styles-preset={"wRTC8eDCA"}
																style={{
																	"--framer-text-alignment": "center",
																}}
															>
																<Link
																	href={{
																		webPageId: "Po_UhMe4P",
																	}}
																	motionChild={true}
																	nodeId={"VHIfhNryJ"}
																	openInNewTab={false}
																	scopeId={"iH9yd5Wn7"}
																	smoothScroll={false}
																>
																	<motion.a
																		className={"framer-styles-preset-rzeatr"}
																		data-styles-preset={"NUFyQ_G3b"}
																	>
																		{"Terms & Conditions"}
																	</motion.a>
																</Link>
															</motion.p>
														</React.Fragment>
													</RichText>
												</motion.div>
											</MotionDivWithFX>
											<RichTextWithFX
												__framer__animate={{
													transition: transition8,
												}}
												__framer__animateOnce={true}
												__framer__enter={animation}
												__framer__styleAppearEffectEnabled={true}
												__framer__threshold={0}
												__fromCanvasComponent={true}
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												className={"framer-28230n"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"OcNm9DQEt"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, rgb(133, 133, 133))",
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1237v2y"}
														data-styles-preset={"wRTC8eDCA"}
														style={{
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, rgb(133, 133, 133)))",
														}}
													>
														{'Copyright "VeeBran". All rights reserved.'}
													</motion.p>
												</React.Fragment>
											</RichTextWithFX>
										</motion.div>
									)}
								</motion.div>
							</motion.div>
						</motion.div>
					</motion.footer>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-idiYh.framer-19iw8sw, .framer-idiYh .framer-19iw8sw { display: block; }",
	".framer-idiYh.framer-ps2hmr { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 60px 60px 60px; position: relative; width: 1200px; }",
	".framer-idiYh .framer-3o98s2 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; max-width: 1228px; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-idiYh .framer-1u0y235 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 1px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-idiYh .framer-19utmyd { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 45px; height: min-content; justify-content: center; overflow: hidden; padding: 90px 0px 90px 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-idiYh .framer-1cj0n6x-container { bottom: -28px; flex: none; left: calc(50.00000000000002% - 104% / 2); position: absolute; top: -2px; width: 104%; }",
	".framer-idiYh .framer-mx0x8l { bottom: 0px; flex: none; height: 95%; left: calc(50.00000000000002% - 100% / 2); overflow: visible; position: absolute; width: 100%; }",
	".framer-idiYh .framer-19fvdhy { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; z-index: 0; }",
	".framer-idiYh .framer-guex1l { aspect-ratio: 3.466666666666667 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 99px); overflow: visible; position: relative; width: 342px; }",
	".framer-idiYh .framer-1le974u { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: 725px; }",
	".framer-idiYh .framer-fch4id { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: 480px; }",
	".framer-idiYh .framer-10arsp8-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-idiYh .framer-ug0b83 { flex: none; height: 1px; overflow: hidden; position: relative; width: 40%; }",
	".framer-idiYh .framer-1oxmrzg, .framer-idiYh .framer-1wwn5p8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-idiYh .framer-1gg2qux, .framer-idiYh .framer-chifgp { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-idiYh .framer-nhi4rf, .framer-idiYh .framer-16lcbtt, .framer-idiYh .framer-16itjwm { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-idiYh .framer-1297xae, .framer-idiYh .framer-isbs89, .framer-idiYh .framer-elm8fy, .framer-idiYh .framer-1pnc7d9, .framer-idiYh .framer-ut20ew, .framer-idiYh .framer-palyqq, .framer-idiYh .framer-1tre0kp, .framer-idiYh .framer-1nc74bi, .framer-idiYh .framer-ha3huj, .framer-idiYh .framer-1ojsxil, .framer-idiYh .framer-wcg4kj, .framer-idiYh .framer-8sjpkz, .framer-idiYh .framer-fl5bpi, .framer-idiYh .framer-vfo5s9 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-idiYh .framer-167srki { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-idiYh .framer-udbgom { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 14px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-idiYh .framer-v05f94, .framer-idiYh .framer-128cvz7 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-idiYh .framer-1jbith2 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-idiYh .framer-28230n { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 441px; word-break: break-word; word-wrap: break-word; }",
	".framer-idiYh.framer-v-em5pde.framer-ps2hmr { padding: 0px 32px 32px 32px; }",
	".framer-idiYh.framer-v-em5pde .framer-19utmyd { gap: 40px; padding: 60px 0px 60px 0px; }",
	".framer-idiYh.framer-v-em5pde .framer-1oxmrzg, .framer-idiYh.framer-v-t15dn6 .framer-19fvdhy, .framer-idiYh.framer-v-1e61xx7 .framer-19fvdhy { gap: 30px; }",
	".framer-idiYh.framer-v-t15dn6.framer-ps2hmr, .framer-idiYh.framer-v-1e61xx7.framer-ps2hmr { padding: 0px 20px 20px 20px; width: 390px; }",
	".framer-idiYh.framer-v-t15dn6 .framer-19utmyd, .framer-idiYh.framer-v-1e61xx7 .framer-19utmyd { gap: 36px; padding: 45px 32px 45px 32px; }",
	".framer-idiYh.framer-v-t15dn6 .framer-mx0x8l, .framer-idiYh.framer-v-1e61xx7 .framer-mx0x8l { left: calc(50.00000000000002% - 101% / 2); width: 101%; }",
	".framer-idiYh.framer-v-t15dn6 .framer-guex1l, .framer-idiYh.framer-v-1e61xx7 .framer-guex1l { height: var(--framer-aspect-ratio-supported, 76px); width: 265px; }",
	".framer-idiYh.framer-v-t15dn6 .framer-1le974u, .framer-idiYh.framer-v-t15dn6 .framer-fch4id, .framer-idiYh.framer-v-t15dn6 .framer-ug0b83, .framer-idiYh.framer-v-1e61xx7 .framer-1le974u, .framer-idiYh.framer-v-1e61xx7 .framer-fch4id, .framer-idiYh.framer-v-1e61xx7 .framer-ug0b83 { width: 100%; }",
	".framer-idiYh.framer-v-t15dn6 .framer-1oxmrzg, .framer-idiYh.framer-v-1e61xx7 .framer-1oxmrzg { gap: 32px; width: 100%; }",
	".framer-idiYh.framer-v-t15dn6 .framer-1gg2qux, .framer-idiYh.framer-v-1e61xx7 .framer-1gg2qux { flex-direction: column; gap: 43px; width: 100%; }",
	".framer-idiYh.framer-v-t15dn6 .framer-nhi4rf, .framer-idiYh.framer-v-1e61xx7 .framer-nhi4rf { gap: 14px; }",
	".framer-idiYh.framer-v-t15dn6 .framer-1297xae, .framer-idiYh.framer-v-1e61xx7 .framer-1297xae { order: 1; }",
	".framer-idiYh.framer-v-t15dn6 .framer-isbs89, .framer-idiYh.framer-v-1e61xx7 .framer-isbs89 { order: 0; }",
	".framer-idiYh.framer-v-t15dn6 .framer-167srki, .framer-idiYh.framer-v-1e61xx7 .framer-167srki { flex: none; width: 100%; }",
	...css5,
	...css2,
	...css,
	...css3,
	...css4,
];
var FrameriH9yd5Wn7 = withCSS(Component, css6, "framer-idiYh");
var stdin_default3 = FrameriH9yd5Wn7;
FrameriH9yd5Wn7.displayName = "Section/Footer";
FrameriH9yd5Wn7.defaultProps = {
	height: 841,
	width: 1200,
};
addPropertyControls(FrameriH9yd5Wn7, {
	variant: {
		options: ["X76dN2SSh", "p4KNEh_xU", "JiIq5YNIP", "OYezazs8l"],
		optionTitles: ["Desktop", "Tablet", "Phone", "Variant 4"],
		title: "Variant",
		type: ControlType.Enum,
	},
	T6gFUZS_O: {
		defaultValue: "rgb(0, 74, 173)",
		title: "Color",
		type: ControlType.Color,
	},
});
addFonts(
	FrameriH9yd5Wn7,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "italic",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "italic",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "italic",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "italic",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "italic",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "italic",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vFzuJY0c65av44uhEKB6vyjFMg.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "italic",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
					weight: "400",
				},
			],
		},
		...ElementBackgroundDotsXLFonts,
		...ButtonButtonFonts,
		...getFontsFromSharedStyle(fonts5),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts4),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:section/footer
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "JiIq5YNIP",
	md: "p4KNEh_xU",
	xl: "X76dN2SSh",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a6e0de7208a6e203a13a02c0c2342fdcb8c3548bcbc64ba40bb03307875e0fbf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a6e0de7208a6e203a13a02c0c2342fdcb8c3548bcbc64ba40bb03307875e0fbf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var footer_default = ComponentWithRoot;
export { footer_default as default };
