// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project a6e0de7208a6e203 "VeeBran", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' | 'Phone Open' // Variant
}} Props

 */
import { className, css, fonts } from "../chunks/chunk-ONDWJXSP.js";
import { Icon } from "../chunks/chunk-66EJKQKM.js";
import "../chunks/chunk-NULYBL27.js";
import { routes } from "../chunks/chunk-ID6ACFOJ.js";

// virtual:section/navigation-2
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/o1jZdcUdW2kAIWh73jKJ/lcJq6cLcnT5IU0PZksCv/jQVnz9gLU.js
import {
	jsx as _jsx2,
	jsxs as _jsxs2,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType2,
	cx as cx2,
	Floating,
	getFonts as getFonts2,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	getLoadingLazyAtYPosition,
	Image,
	Link as Link2,
	ResolveLinks,
	RichText as RichText2,
	SmartComponentScopedContainer,
	useActiveVariantCallback as useActiveVariantCallback2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useOverlayState,
	useRouter,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
	withFX,
} from "unframer";
import {
	AnimatePresence,
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/6zTQsXgB0PkTaNyaxDc0/Ss5nx0qf04xxJaBtVmcJ/bUi6CG56e.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	CycleVariantState,
	getFonts,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";

// /:https://framerusercontent.com/modules/4NYMZoLVjjzMEP18TVwL/JJmOAjRp8AbdOAhBBIs0/SdN8D7okU.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"FS;Manrope-regular",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-Italic",
]);
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Manrope",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/2TYFCBHUANEXS6QGR5EQDUNAFH6LSWM3/AYNOU3VEA4LRTDNKJQUFNVNUTYSGOUOP/UXO4O7K2G3HI3D2VKD7UXVJVJD26P4BQ.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/QxmhnWTzLtyjIiZcfaLIJ8EFBXU.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/vFzuJY0c65av44uhEKB6vyjFMg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
				weight: "400",
			},
		],
	},
];
var css2 = [
	'.framer-GG9Df .framer-styles-preset-180noy4:not(.rich-text-wrapper), .framer-GG9Df .framer-styles-preset-180noy4.rich-text-wrapper p { --framer-font-family: "Manrope", "Manrope Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 400; --framer-font-weight-bold: 500; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.375em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, #858585); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-GG9Df .framer-styles-preset-180noy4:not(.rich-text-wrapper), .framer-GG9Df .framer-styles-preset-180noy4.rich-text-wrapper p { --framer-font-family: "Manrope", "Manrope Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 400; --framer-font-weight-bold: 500; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.375em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, #858585); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-GG9Df .framer-styles-preset-180noy4:not(.rich-text-wrapper), .framer-GG9Df .framer-styles-preset-180noy4.rich-text-wrapper p { --framer-font-family: "Manrope", "Manrope Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 400; --framer-font-weight-bold: 500; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.375em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, #858585); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className2 = "framer-GG9Df";

// /:https://framerusercontent.com/modules/6zTQsXgB0PkTaNyaxDc0/Ss5nx0qf04xxJaBtVmcJ/bUi6CG56e.js
var FeatherFonts = getFonts(Icon);
var enabledGestures = {
	on4bS9Ijv: {
		hover: true,
	},
	qjAclOIYh: {
		hover: true,
	},
	R5CB1p15o: {
		hover: true,
	},
	uaQcaqsJ0: {
		hover: true,
	},
};
var cycleOrder = ["uaQcaqsJ0", "R5CB1p15o", "on4bS9Ijv", "qjAclOIYh"];
var serializationHash = "framer-VNnqE";
var variantClassNames = {
	on4bS9Ijv: "framer-v-1rr231u",
	qjAclOIYh: "framer-v-qbo91",
	R5CB1p15o: "framer-v-vxtxsc",
	uaQcaqsJ0: "framer-v-kr6of7",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.3,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var transition2 = {
	delay: 0,
	duration: 0.8,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var transition3 = {
	delay: 0,
	duration: 0.3,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Bottom: "on4bS9Ijv",
	Left: "qjAclOIYh",
	Right: "R5CB1p15o",
	Top: "uaQcaqsJ0",
};
var getProps = ({ buttonText, height, id, link, width, ...props }) => {
	var _ref, _humanReadableVariantMap_props_variant, _ref1;
	return {
		...props,
		GS3bSUXSK: link !== null && link !== void 0 ? link : props.GS3bSUXSK,
		ofLqZhEO8:
			(_ref =
				buttonText !== null && buttonText !== void 0
					? buttonText
					: props.ofLqZhEO8) !== null && _ref !== void 0
				? _ref
				: "Running stroke",
		variant:
			(_ref1 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref1 !== void 0
				? _ref1
				: "uaQcaqsJ0",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		ofLqZhEO8,
		GS3bSUXSK,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "uaQcaqsJ0",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppear138cof = activeVariantCallback(async (...args) => {
		await delay(() => setVariant(CycleVariantState), 300);
	});
	const onAppear17vk1v4 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant(CycleVariantState), 800);
	});
	useOnVariantChange(baseVariant, {
		default: onAppear138cof,
		qjAclOIYh: onAppear17vk1v4,
		R5CB1p15o: onAppear17vk1v4,
	});
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className2];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition
					value={transition1}
					{...addPropertyOverrides(
						{
							qjAclOIYh: {
								value: transition2,
							},
							R5CB1p15o: {
								value: transition2,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<Link href={GS3bSUXSK} openInNewTab={false}>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(serializationHash, ...sharedStyleClassNames, "framer-kr6of7", className3, classNames)} framer-k2w4b`}
							data-framer-name={"Top"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"uaQcaqsJ0"}
							ref={ref !== null && ref !== void 0 ? ref : ref1}
							style={{
								backgroundColor: "rgb(32, 32, 32)",
								borderBottomLeftRadius: 7,
								borderBottomRightRadius: 7,
								borderTopLeftRadius: 7,
								borderTopRightRadius: 7,
								...style,
							}}
							{...addPropertyOverrides(
								{
									"on4bS9Ijv-hover": {
										"data-framer-name": void 0,
									},
									"qjAclOIYh-hover": {
										"data-framer-name": void 0,
									},
									"R5CB1p15o-hover": {
										"data-framer-name": void 0,
									},
									"uaQcaqsJ0-hover": {
										"data-framer-name": void 0,
									},
									on4bS9Ijv: {
										"data-framer-name": "Bottom",
									},
									qjAclOIYh: {
										"data-framer-name": "Left",
									},
									R5CB1p15o: {
										"data-framer-name": "Right",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-kz9f2t"}
								data-framer-name={"Stroke"}
								layoutDependency={layoutDependency}
								layoutId={"yTzU_O183"}
								style={{
									background:
										'radial-gradient(20.7% 50% at 0% 0%, var(--token-6edbd31d-41be-4de3-9d80-c4d0ae2c7447, rgb(158, 100, 46)) /* {"name":"UI Orange 450"} */ 0%, rgba(255, 255, 255, 0) 100%)',
									borderBottomLeftRadius: 7,
									borderBottomRightRadius: 7,
									borderTopLeftRadius: 7,
									borderTopRightRadius: 7,
								}}
								variants={{
									"on4bS9Ijv-hover": {
										background:
											'radial-gradient(75% 181.15942028985506% at 50% 50%, var(--token-6edbd31d-41be-4de3-9d80-c4d0ae2c7447, rgb(158, 100, 46)) /* {"name":"UI Orange 450"} */ 0%, rgba(255, 255, 255, 0) 100%)',
									},
									"qjAclOIYh-hover": {
										background:
											'radial-gradient(75% 181.15942028985506% at 50% 50%, var(--token-6edbd31d-41be-4de3-9d80-c4d0ae2c7447, rgb(158, 100, 46)) /* {"name":"UI Orange 450"} */ 0%, rgba(255, 255, 255, 0) 100%)',
									},
									"R5CB1p15o-hover": {
										background:
											'radial-gradient(75% 181.15942028985506% at 50% 50%, var(--token-6edbd31d-41be-4de3-9d80-c4d0ae2c7447, rgb(158, 100, 46)) /* {"name":"UI Orange 450"} */ 0%, rgba(255, 255, 255, 0) 100%)',
									},
									"uaQcaqsJ0-hover": {
										background:
											'radial-gradient(75% 181.15942028985506% at 50% 50%, var(--token-6edbd31d-41be-4de3-9d80-c4d0ae2c7447, rgb(158, 100, 46)) /* {"name":"UI Orange 450"} */ 0%, rgba(255, 255, 255, 0) 100%)',
									},
									on4bS9Ijv: {
										background:
											'radial-gradient(20.7% 50% at 100% 100%, var(--token-6edbd31d-41be-4de3-9d80-c4d0ae2c7447, rgb(158, 100, 46)) /* {"name":"UI Orange 450"} */ 0%, rgba(255, 255, 255, 0) 100%)',
									},
									qjAclOIYh: {
										background:
											'radial-gradient(16.6% 43.1% at 0% 100%, var(--token-6edbd31d-41be-4de3-9d80-c4d0ae2c7447, rgb(158, 100, 46)) /* {"name":"UI Orange 450"} */ 0%, rgba(255, 255, 255, 0) 100%)',
									},
									R5CB1p15o: {
										background:
											'radial-gradient(16.2% 41.199999999999996% at 100% 0%, var(--token-6edbd31d-41be-4de3-9d80-c4d0ae2c7447, rgb(158, 100, 46)) /* {"name":"UI Orange 450"} */ 0%, rgba(255, 255, 255, 0) 100%)',
									},
								}}
							/>
							<motion.div
								className={"framer-ff818b"}
								data-framer-name={"Glow"}
								layoutDependency={layoutDependency}
								layoutId={"aEonBSyh0"}
								style={{
									background:
										'radial-gradient(25% 50% at 0% 0%, var(--token-6edbd31d-41be-4de3-9d80-c4d0ae2c7447, rgb(158, 100, 46)) /* {"name":"UI Orange 450"} */ 0%, rgba(255, 255, 255, 0) 100%)',
									borderBottomLeftRadius: 7,
									borderBottomRightRadius: 7,
									borderTopLeftRadius: 7,
									borderTopRightRadius: 7,
									filter: "blur(15px)",
									WebkitFilter: "blur(15px)",
								}}
								variants={{
									"on4bS9Ijv-hover": {
										background:
											'radial-gradient(50% 100% at 50% 50%, var(--token-6edbd31d-41be-4de3-9d80-c4d0ae2c7447, rgb(158, 100, 46)) /* {"name":"UI Orange 450"} */ 0%, rgba(255, 255, 255, 0) 100%)',
									},
									"qjAclOIYh-hover": {
										background:
											'radial-gradient(50% 100% at 50% 50%, var(--token-6edbd31d-41be-4de3-9d80-c4d0ae2c7447, rgb(158, 100, 46)) /* {"name":"UI Orange 450"} */ 0%, rgba(255, 255, 255, 0) 100%)',
									},
									"R5CB1p15o-hover": {
										background:
											'radial-gradient(50% 100% at 50% 50%, var(--token-6edbd31d-41be-4de3-9d80-c4d0ae2c7447, rgb(158, 100, 46)) /* {"name":"UI Orange 450"} */ 0%, rgba(255, 255, 255, 0) 100%)',
									},
									"uaQcaqsJ0-hover": {
										background:
											'radial-gradient(50% 100% at 50% 50%, var(--token-6edbd31d-41be-4de3-9d80-c4d0ae2c7447, rgb(158, 100, 46)) /* {"name":"UI Orange 450"} */ 0%, rgba(255, 255, 255, 0) 100%)',
									},
									on4bS9Ijv: {
										background:
											'radial-gradient(25% 50% at 100% 100%, var(--token-6edbd31d-41be-4de3-9d80-c4d0ae2c7447, rgb(158, 100, 46)) /* {"name":"UI Orange 450"} */ 0%, rgba(255, 255, 255, 0) 100%)',
									},
									qjAclOIYh: {
										background:
											'radial-gradient(25% 34.4% at 0% 100%, var(--token-6edbd31d-41be-4de3-9d80-c4d0ae2c7447, rgb(158, 100, 46)) /* {"name":"UI Orange 450"} */ 0%, rgba(255, 255, 255, 0) 100%)',
									},
									R5CB1p15o: {
										background:
											'radial-gradient(25% 35.4% at 100% 0%, var(--token-6edbd31d-41be-4de3-9d80-c4d0ae2c7447, rgb(158, 100, 46)) /* {"name":"UI Orange 450"} */ 0%, rgba(255, 255, 255, 0) 100%)',
									},
								}}
							/>
							<motion.div
								className={"framer-ojxa4s"}
								data-framer-name={"Fill"}
								layoutDependency={layoutDependency}
								layoutId={"lzkNkabnt"}
								style={{
									backgroundColor:
										"var(--token-70b4ad58-9042-4a72-8dea-68d8a9efadf0, rgb(13, 13, 13))",
									borderBottomLeftRadius: 7,
									borderBottomRightRadius: 7,
									borderTopLeftRadius: 7,
									borderTopRightRadius: 7,
								}}
							/>
							<motion.div
								className={"framer-1ywzbdx"}
								layoutDependency={layoutDependency}
								layoutId={"bbNzfBOFy"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1fn3oyk"}
									data-framer-name={"Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"witvQazQ7"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-4a89092a-27d2-4444-a4b5-4bb982a67f8e, rgb(222, 222, 222))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
										"--framer-paragraph-spacing": "0px",
									}}
									text={ofLqZhEO8}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-180noy4"}
											data-styles-preset={"SdN8D7okU"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-4a89092a-27d2-4444-a4b5-4bb982a67f8e, rgb(222, 222, 222)))",
											}}
										>
											{"Running stroke"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<Transition value={transition3}>
									<motion.div
										className={"framer-4emm1m"}
										data-framer-name={"Icon Flip"}
										layoutDependency={layoutDependency}
										layoutId={"sx_WcIOaq"}
									>
										<ComponentViewportProvider>
											<motion.div
												className={"framer-kje1p8-container"}
												layoutDependency={layoutDependency}
												layoutId={"ZOS6T0BZp-container"}
											>
												<Icon
													color={
														"var(--token-4a89092a-27d2-4444-a4b5-4bb982a67f8e, rgb(222, 222, 222))"
													}
													height={"100%"}
													iconSearch={"Home"}
													iconSelection={"arrow-up-right"}
													id={"ZOS6T0BZp"}
													layoutId={"ZOS6T0BZp"}
													mirrored={false}
													selectByList={true}
													style={{
														height: "100%",
														width: "100%",
													}}
													width={"100%"}
												/>
											</motion.div>
										</ComponentViewportProvider>
										<ComponentViewportProvider>
											<motion.div
												className={"framer-118apwj-container"}
												layoutDependency={layoutDependency}
												layoutId={"quseSs4My-container"}
											>
												<Icon
													color={
														"var(--token-4a89092a-27d2-4444-a4b5-4bb982a67f8e, rgb(222, 222, 222))"
													}
													height={"100%"}
													iconSearch={"Home"}
													iconSelection={"arrow-up-right"}
													id={"quseSs4My"}
													layoutId={"quseSs4My"}
													mirrored={false}
													selectByList={true}
													style={{
														height: "100%",
														width: "100%",
													}}
													width={"100%"}
												/>
											</motion.div>
										</ComponentViewportProvider>
									</motion.div>
								</Transition>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-VNnqE.framer-k2w4b, .framer-VNnqE .framer-k2w4b { display: block; }",
	".framer-VNnqE.framer-kr6of7 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 8px 21px 8px 21px; position: relative; text-decoration: none; width: min-content; }",
	".framer-VNnqE .framer-kz9f2t, .framer-VNnqE .framer-ff818b { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; will-change: var(--framer-will-change-override, transform); z-index: 0; }",
	".framer-VNnqE .framer-ojxa4s { bottom: 1px; flex: none; left: 1px; overflow: hidden; position: absolute; right: 1px; top: 1px; will-change: var(--framer-will-change-override, transform); z-index: 0; }",
	".framer-VNnqE .framer-1ywzbdx { align-content: center; align-items: center; align-self: stretch; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: auto; }",
	".framer-VNnqE .framer-1fn3oyk { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-VNnqE .framer-4emm1m { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 18px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 18px; }",
	".framer-VNnqE .framer-kje1p8-container { flex: none; height: 18px; left: calc(50.00000000000002% - 18px / 2); position: absolute; top: calc(50.00000000000002% - 18px / 2); width: 18px; z-index: 1; }",
	".framer-VNnqE .framer-118apwj-container { bottom: -22px; flex: none; height: 18px; left: -22px; position: absolute; width: 18px; z-index: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-VNnqE.framer-kr6of7, .framer-VNnqE .framer-1ywzbdx, .framer-VNnqE .framer-4emm1m { gap: 0px; } .framer-VNnqE.framer-kr6of7 > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-VNnqE.framer-kr6of7 > :first-child { margin-top: 0px; } .framer-VNnqE.framer-kr6of7 > :last-child { margin-bottom: 0px; } .framer-VNnqE .framer-1ywzbdx > * { margin: 0px; margin-left: calc(8px / 2); margin-right: calc(8px / 2); } .framer-VNnqE .framer-1ywzbdx > :first-child, .framer-VNnqE .framer-4emm1m > :first-child { margin-left: 0px; } .framer-VNnqE .framer-1ywzbdx > :last-child, .framer-VNnqE .framer-4emm1m > :last-child { margin-right: 0px; } .framer-VNnqE .framer-4emm1m > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } }",
	".framer-VNnqE.framer-v-kr6of7.hover .framer-kje1p8-container, .framer-VNnqE.framer-v-vxtxsc.hover .framer-kje1p8-container, .framer-VNnqE.framer-v-1rr231u.hover .framer-kje1p8-container, .framer-VNnqE.framer-v-qbo91.hover .framer-kje1p8-container { left: unset; right: -22px; top: -22px; }",
	".framer-VNnqE.framer-v-kr6of7.hover .framer-118apwj-container { bottom: unset; left: calc(50.00000000000002% - 18px / 2); top: calc(50.00000000000002% - 18px / 2); }",
	".framer-VNnqE.framer-v-vxtxsc.hover .framer-118apwj-container, .framer-VNnqE.framer-v-1rr231u.hover .framer-118apwj-container, .framer-VNnqE.framer-v-qbo91.hover .framer-118apwj-container { bottom: 0px; left: 0px; }",
	...css2,
];
var FramerbUi6CG56e = withCSS(Component, css3, "framer-VNnqE");
var stdin_default = FramerbUi6CG56e;
FramerbUi6CG56e.displayName = "Button/Running-Stroke";
FramerbUi6CG56e.defaultProps = {
	height: 38,
	width: 179.5,
};
addPropertyControls(FramerbUi6CG56e, {
	variant: {
		options: ["uaQcaqsJ0", "R5CB1p15o", "on4bS9Ijv", "qjAclOIYh"],
		optionTitles: ["Top", "Right", "Bottom", "Left"],
		title: "Variant",
		type: ControlType.Enum,
	},
	ofLqZhEO8: {
		defaultValue: "Running stroke",
		displayTextArea: false,
		title: "Button text",
		type: ControlType.String,
	},
	GS3bSUXSK: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerbUi6CG56e,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...FeatherFonts,
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/o1jZdcUdW2kAIWh73jKJ/lcJq6cLcnT5IU0PZksCv/jQVnz9gLU.js
var FeatherFonts2 = getFonts2(Icon);
var MotionDivWithFX = withFX(motion2.div);
var ButtonRunningStrokeFonts = getFonts2(stdin_default);
var cycleOrder2 = ["Ox5wM8MTA", "mGrDyrpZD", "NYTQVxxd6", "tcJ_hCqgV"];
var serializationHash2 = "framer-waF1d";
var variantClassNames2 = {
	mGrDyrpZD: "framer-v-6rgoo",
	NYTQVxxd6: "framer-v-sa6n7b",
	Ox5wM8MTA: "framer-v-ab3g4n",
	tcJ_hCqgV: "framer-v-1a9g4rk",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	damping: 40,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var transition22 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition22,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition22,
	x: 0,
	y: 0,
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var Overlay = ({ children, blockDocumentScrolling, enabled = true }) => {
	const [visible, setVisible] = useOverlayState({
		blockDocumentScrolling,
	});
	return children({
		hide: () => setVisible(false),
		show: () => setVisible(true),
		toggle: () => setVisible(!visible),
		visible: enabled && visible,
	});
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	"Phone Open": "tcJ_hCqgV",
	Desktop: "Ox5wM8MTA",
	Phone: "NYTQVxxd6",
	Tablet: "mGrDyrpZD",
};
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "Ox5wM8MTA",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "Ox5wM8MTA",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback2(baseVariant);
	const onTapdcwruv = activeVariantCallback(async (...args) => {
		setVariant("NYTQVxxd6");
	});
	const onTapdoq7bq = activeVariantCallback(async (...args) => {
		setVariant("tcJ_hCqgV");
	});
	const onMouseEntertxyyif = ({ overlay, loadMore }) =>
		activeVariantCallback(async (...args) => {
			overlay.show();
		});
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["NYTQVxxd6", "tcJ_hCqgV"].includes(baseVariant)) return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "tcJ_hCqgV") return true;
		return false;
	};
	const isDisplayed2 = () => {
		if (baseVariant === "NYTQVxxd6") return false;
		return true;
	};
	const isDisplayed3 = () => {
		if (baseVariant === "tcJ_hCqgV") return false;
		return true;
	};
	const ref1 = React2.useRef(null);
	const ref2 = React2.useRef(null);
	const router = useRouter();
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.nav
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-ab3g4n",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"Ox5wM8MTA"}
						ref={refBinding}
						style={{
							background:
								"linear-gradient(180deg, var(--token-4d6fb0aa-347b-4d07-918a-f12b70b08ad3, rgb(33, 33, 33)) 0%, rgba(33, 33, 33, 0.4) 100%)",
							borderBottomLeftRadius: 40,
							borderBottomRightRadius: 40,
							borderTopLeftRadius: 40,
							borderTopRightRadius: 40,
							...style,
						}}
						variants={{
							tcJ_hCqgV: {
								borderBottomLeftRadius: 24,
								borderBottomRightRadius: 24,
								borderTopLeftRadius: 24,
								borderTopRightRadius: 24,
							},
						}}
						{...addPropertyOverrides2(
							{
								mGrDyrpZD: {
									"data-framer-name": "Tablet",
								},
								NYTQVxxd6: {
									"data-framer-name": "Phone",
								},
								tcJ_hCqgV: {
									"data-framer-name": "Phone Open",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-tszrmk"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"p1IJln4w6"}
							style={{
								backgroundColor:
									"var(--token-c311f7eb-2396-4f7f-8edd-f790b3c42ec3, rgb(5, 5, 5))",
								borderBottomLeftRadius: 40,
								borderBottomRightRadius: 40,
								borderTopLeftRadius: 40,
								borderTopRightRadius: 40,
							}}
							variants={{
								tcJ_hCqgV: {
									borderBottomLeftRadius: 23,
									borderBottomRightRadius: 23,
									borderTopLeftRadius: 23,
									borderTopRightRadius: 23,
								},
							}}
						>
							<motion2.div
								className={"framer-1ua4du"}
								data-framer-name={"Wrapper"}
								layoutDependency={layoutDependency}
								layoutId={"tCiadsZSF"}
							>
								<motion2.div
									className={"framer-1obtxts"}
									data-framer-name={"Top"}
									layoutDependency={layoutDependency}
									layoutId={"TiOJJpkEc"}
									{...addPropertyOverrides2(
										{
											tcJ_hCqgV: {
												"data-highlight": true,
												onTap: onTapdcwruv,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<Link2
										href={{
											webPageId: "augiA20Il",
										}}
										motionChild={true}
										nodeId={"s2cuUr6jr"}
										scopeId={"jQVnz9gLU"}
									>
										<Image
											aria-label={"brand-name"}
											as={"a"}
											background={{
												alt: "",
												fit: "fit",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														(1 +
															((componentViewport?.height || 66) - 2 - 64) /
																2) +
														17 +
														0 +
														0 +
														0,
												),
												pixelHeight: 1695,
												pixelWidth: 7801,
												positionX: "left",
												positionY: "center",
												sizes: "104px",
												src: "https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png",
												srcSet:
													"https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png?scale-down-to=512 512w,https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png?scale-down-to=2048 2048w,https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png?scale-down-to=4096 4096w,https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png 7801w",
											}}
											className={"framer-1d70se8 framer-g8yi6i"}
											data-framer-name={"Logo"}
											layoutDependency={layoutDependency}
											layoutId={"s2cuUr6jr"}
											{...addPropertyOverrides2(
												{
													mGrDyrpZD: {
														background: {
															alt: "",
															fit: "fit",
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																	(1 +
																		((componentViewport?.height || 200) -
																			2 -
																			64) /
																			2) +
																	17 +
																	0 +
																	0 +
																	0,
															),
															pixelHeight: 1695,
															pixelWidth: 7801,
															positionX: "left",
															positionY: "center",
															sizes: "104px",
															src: "https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png",
															srcSet:
																"https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png?scale-down-to=512 512w,https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png?scale-down-to=2048 2048w,https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png?scale-down-to=4096 4096w,https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png 7801w",
														},
													},
													NYTQVxxd6: {
														background: {
															alt: "",
															fit: "fit",
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																	1 +
																	0 +
																	8 +
																	0 +
																	0 +
																	7.0193,
															),
															pixelHeight: 1695,
															pixelWidth: 7801,
															positionX: "left",
															positionY: "center",
															sizes: "90px",
															src: "https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png",
															srcSet:
																"https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png?scale-down-to=512 512w,https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png?scale-down-to=2048 2048w,https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png?scale-down-to=4096 4096w,https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png 7801w",
														},
													},
													tcJ_hCqgV: {
														background: {
															alt: "",
															fit: "fit",
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																	1 +
																	0 +
																	8 +
																	0 +
																	0 +
																	0 +
																	7.0193,
															),
															pixelHeight: 1695,
															pixelWidth: 7801,
															positionX: "left",
															positionY: "center",
															sizes: "90px",
															src: "https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png",
															srcSet:
																"https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png?scale-down-to=512 512w,https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png?scale-down-to=2048 2048w,https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png?scale-down-to=4096 4096w,https://framerusercontent.com/images/Z6aYVOMp3JvPzbDPEtSwnu3aEmQ.png 7801w",
														},
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
									</Link2>
									{isDisplayed() && (
										<motion2.div
											className={"framer-15y5mbu"}
											data-framer-name={"Icon"}
											data-highlight={true}
											layoutDependency={layoutDependency}
											layoutId={"C3Br6OqKO"}
											onTap={onTapdoq7bq}
										>
											<motion2.div
												className={"framer-1y4vygg"}
												data-framer-name={"Bottom"}
												layoutDependency={layoutDependency}
												layoutId={"S7y38xpw3"}
												style={{
													backgroundColor: "rgb(153, 153, 153)",
													borderBottomLeftRadius: 10,
													borderBottomRightRadius: 10,
													borderTopLeftRadius: 10,
													borderTopRightRadius: 10,
													rotate: 0,
												}}
												variants={{
													tcJ_hCqgV: {
														rotate: -45,
													},
												}}
											/>
											<motion2.div
												className={"framer-4cjbyc"}
												data-framer-name={"Top"}
												layoutDependency={layoutDependency}
												layoutId={"aR0hY4Cqc"}
												style={{
													backgroundColor: "rgb(153, 153, 153)",
													borderBottomLeftRadius: 10,
													borderBottomRightRadius: 10,
													borderTopLeftRadius: 10,
													borderTopRightRadius: 10,
													rotate: 0,
												}}
												variants={{
													tcJ_hCqgV: {
														rotate: 45,
													},
												}}
											/>
										</motion2.div>
									)}
								</motion2.div>
								{isDisplayed1() && (
									<motion2.div
										className={"framer-npnllj"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"I5rupxgXp"}
										style={{
											background:
												"linear-gradient(90deg, rgba(61, 61, 61, 0) 0%, var(--token-4d6fb0aa-347b-4d07-918a-f12b70b08ad3, rgb(33, 33, 33)) 25%, var(--token-4d6fb0aa-347b-4d07-918a-f12b70b08ad3, rgb(33, 33, 33)) 75%, rgba(0, 80, 138, 0) 100%)",
										}}
									/>
								)}
							</motion2.div>
							{isDisplayed2() && (
								<motion2.div
									className={"framer-1pxc86g"}
									data-framer-name={"Links"}
									layoutDependency={layoutDependency}
									layoutId={"zA9_xVCTA"}
								>
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-ptoe3c"}
										fonts={["FS;Manrope-regular"]}
										layoutDependency={layoutDependency}
										layoutId={"feWteYphY"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, rgb(133, 133, 133))",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.p
												style={{
													"--font-selector": "RlM7TWFucm9wZS1yZWd1bGFy",
													"--framer-font-family":
														'"Manrope", "Manrope Placeholder", sans-serif',
													"--framer-line-height": "1.375em",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, rgb(133, 133, 133)))",
												}}
											>
												<Link2
													href={{
														hash: ":uTrHOqYco",
														webPageId: "augiA20Il",
													}}
													motionChild={true}
													nodeId={"feWteYphY"}
													openInNewTab={false}
													scopeId={"jQVnz9gLU"}
													smoothScroll={true}
												>
													<motion2.a
														className={"framer-styles-preset-rzeatr"}
														data-styles-preset={"NUFyQ_G3b"}
													>
														{"Why Us"}
													</motion2.a>
												</Link2>
											</motion2.p>
										</React2.Fragment>
									</RichText2>
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-1wknjal"}
										fonts={["FS;Manrope-regular"]}
										layoutDependency={layoutDependency}
										layoutId={"vc8b6RuCl"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, rgb(133, 133, 133))",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.p
												style={{
													"--font-selector": "RlM7TWFucm9wZS1yZWd1bGFy",
													"--framer-font-family":
														'"Manrope", "Manrope Placeholder", sans-serif',
													"--framer-line-height": "1.375em",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, rgb(133, 133, 133)))",
												}}
											>
												<Link2
													href={{
														hash: ":eCxvIfBt6",
														webPageId: "augiA20Il",
													}}
													motionChild={true}
													nodeId={"vc8b6RuCl"}
													openInNewTab={false}
													scopeId={"jQVnz9gLU"}
													smoothScroll={true}
												>
													<motion2.a
														className={"framer-styles-preset-rzeatr"}
														data-styles-preset={"NUFyQ_G3b"}
													>
														{"Mission"}
													</motion2.a>
												</Link2>
											</motion2.p>
										</React2.Fragment>
									</RichText2>
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-xw0tam"}
										fonts={["FS;Manrope-regular"]}
										layoutDependency={layoutDependency}
										layoutId={"DLsqbk8l0"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, rgb(133, 133, 133))",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.p
												style={{
													"--font-selector": "RlM7TWFucm9wZS1yZWd1bGFy",
													"--framer-font-family":
														'"Manrope", "Manrope Placeholder", sans-serif',
													"--framer-line-height": "1.375em",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, rgb(133, 133, 133)))",
												}}
											>
												<Link2
													href={{
														hash: ":a8kgD6gFC",
														webPageId: "augiA20Il",
													}}
													motionChild={true}
													nodeId={"DLsqbk8l0"}
													openInNewTab={false}
													scopeId={"jQVnz9gLU"}
													smoothScroll={true}
												>
													<motion2.a
														className={"framer-styles-preset-rzeatr"}
														data-styles-preset={"NUFyQ_G3b"}
													>
														{"Works"}
													</motion2.a>
												</Link2>
											</motion2.p>
										</React2.Fragment>
									</RichText2>
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-1o70b7k"}
										fonts={["FS;Manrope-regular"]}
										layoutDependency={layoutDependency}
										layoutId={"x5YKlxyIX"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, rgb(133, 133, 133))",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.p
												style={{
													"--font-selector": "RlM7TWFucm9wZS1yZWd1bGFy",
													"--framer-font-family":
														'"Manrope", "Manrope Placeholder", sans-serif',
													"--framer-line-height": "1.375em",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, rgb(133, 133, 133)))",
												}}
											>
												<Link2
													href={{
														hash: ":ACBgSFIb5",
														webPageId: "augiA20Il",
													}}
													motionChild={true}
													nodeId={"x5YKlxyIX"}
													openInNewTab={false}
													scopeId={"jQVnz9gLU"}
													smoothScroll={true}
												>
													<motion2.a
														className={"framer-styles-preset-rzeatr"}
														data-styles-preset={"NUFyQ_G3b"}
													>
														{"Services"}
													</motion2.a>
												</Link2>
											</motion2.p>
										</React2.Fragment>
									</RichText2>
									{isDisplayed1() && (
										<RichText2
											__fromCanvasComponent={true}
											className={"framer-12iptw6"}
											fonts={["FS;Manrope-regular"]}
											layoutDependency={layoutDependency}
											layoutId={"qPPrEm0fK"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, rgb(133, 133, 133))",
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React2.Fragment>
												<motion2.p
													style={{
														"--font-selector": "RlM7TWFucm9wZS1yZWd1bGFy",
														"--framer-font-family":
															'"Manrope", "Manrope Placeholder", sans-serif',
														"--framer-line-height": "1.375em",
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, rgb(133, 133, 133)))",
													}}
												>
													<Link2
														href={{
															webPageId: "O9HKScYjf",
														}}
														motionChild={true}
														nodeId={"qPPrEm0fK"}
														openInNewTab={false}
														scopeId={"jQVnz9gLU"}
														smoothScroll={false}
													>
														<motion2.a
															className={"framer-styles-preset-rzeatr"}
															data-styles-preset={"NUFyQ_G3b"}
														>
															{"Contact"}
														</motion2.a>
													</Link2>
												</motion2.p>
											</React2.Fragment>
										</RichText2>
									)}
									{isDisplayed1() && (
										<RichText2
											__fromCanvasComponent={true}
											className={"framer-1iogn3o"}
											fonts={["FS;Manrope-regular"]}
											layoutDependency={layoutDependency}
											layoutId={"gfL4z2hc7"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, rgb(133, 133, 133))",
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React2.Fragment>
												<motion2.p
													style={{
														"--font-selector": "RlM7TWFucm9wZS1yZWd1bGFy",
														"--framer-font-family":
															'"Manrope", "Manrope Placeholder", sans-serif',
														"--framer-line-height": "1.375em",
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, rgb(133, 133, 133)))",
													}}
												>
													<Link2
														href={{
															webPageId: "y5dAOCV3n",
														}}
														motionChild={true}
														nodeId={"gfL4z2hc7"}
														openInNewTab={false}
														scopeId={"jQVnz9gLU"}
														smoothScroll={false}
													>
														<motion2.a
															className={"framer-styles-preset-rzeatr"}
															data-styles-preset={"NUFyQ_G3b"}
														>
															{"Term & Conditions"}
														</motion2.a>
													</Link2>
												</motion2.p>
											</React2.Fragment>
										</RichText2>
									)}
									{isDisplayed1() && (
										<RichText2
											__fromCanvasComponent={true}
											className={"framer-ztfff6"}
											fonts={["FS;Manrope-regular"]}
											layoutDependency={layoutDependency}
											layoutId={"iulVIDdHz"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, rgb(133, 133, 133))",
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React2.Fragment>
												<motion2.p
													style={{
														"--font-selector": "RlM7TWFucm9wZS1yZWd1bGFy",
														"--framer-font-family":
															'"Manrope", "Manrope Placeholder", sans-serif',
														"--framer-line-height": "1.375em",
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, rgb(133, 133, 133)))",
													}}
												>
													<Link2
														href={{
															webPageId: "qX2wLzlJu",
														}}
														motionChild={true}
														nodeId={"iulVIDdHz"}
														openInNewTab={false}
														scopeId={"jQVnz9gLU"}
														smoothScroll={false}
													>
														<motion2.a
															className={"framer-styles-preset-rzeatr"}
															data-styles-preset={"NUFyQ_G3b"}
														>
															{"404"}
														</motion2.a>
													</Link2>
												</motion2.p>
											</React2.Fragment>
										</RichText2>
									)}
									{isDisplayed3() && (
										<Overlay blockDocumentScrolling={false}>
											{(overlay) => (
												<_Fragment>
													<motion2.div
														className={"framer-1n6vi3v"}
														data-framer-name={"Button/Button"}
														data-highlight={true}
														id={`${layoutId}-1n6vi3v`}
														layoutDependency={layoutDependency}
														layoutId={"kZIHM543X"}
														onMouseEnter={onMouseEntertxyyif({
															overlay,
														})}
														ref={ref1}
														style={{
															background:
																"radial-gradient(50% 50% at 50% 50%, var(--token-ca0eb946-0278-4b5f-be23-d71665cd022d, rgba(17, 17, 17, 0)) 0%, var(--token-ca0eb946-0278-4b5f-be23-d71665cd022d, rgba(17, 17, 17, 0)) 100%)",
															borderBottomLeftRadius: 7,
															borderBottomRightRadius: 7,
															borderTopLeftRadius: 7,
															borderTopRightRadius: 7,
														}}
													>
														<RichText2
															__fromCanvasComponent={true}
															className={"framer-iusfhp"}
															data-framer-name={"Pages"}
															fonts={["FS;Manrope-regular"]}
															layoutDependency={layoutDependency}
															layoutId={"G147pwp6G"}
															style={{
																"--extracted-r6o4lv":
																	"var(--token-0bd91f44-2ee2-49df-bd1a-78a1b1ec8984, rgb(175, 175, 175))",
																"--framer-link-text-color": "rgb(0, 153, 255)",
																"--framer-link-text-decoration": "underline",
															}}
															verticalAlignment={"top"}
															withExternalLayout={true}
														>
															<React2.Fragment>
																<motion2.p
																	style={{
																		"--font-selector":
																			"RlM7TWFucm9wZS1yZWd1bGFy",
																		"--framer-font-family":
																			'"Manrope", "Manrope Placeholder", sans-serif',
																		"--framer-line-height": "1.375em",
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, var(--token-0bd91f44-2ee2-49df-bd1a-78a1b1ec8984, rgb(175, 175, 175)))",
																	}}
																>
																	{"Pages"}
																</motion2.p>
															</React2.Fragment>
														</RichText2>
														<motion2.div
															className={"framer-xv4iny"}
															data-framer-name={"Icon Flip"}
															layoutDependency={layoutDependency}
															layoutId={"Ntiq6hRKH"}
														>
															<ComponentViewportProvider2>
																<SmartComponentScopedContainer
																	className={"framer-7oxje0-container"}
																	isAuthoredByUser={true}
																	isModuleExternal={true}
																	layoutDependency={layoutDependency}
																	layoutId={"E3jhb_p3i-container"}
																	nodeId={"E3jhb_p3i"}
																	rendersWithMotion={true}
																	scopeId={"jQVnz9gLU"}
																>
																	<Icon
																		color={
																			"var(--token-0bd91f44-2ee2-49df-bd1a-78a1b1ec8984, rgb(175, 175, 175))"
																		}
																		height={"100%"}
																		iconSearch={"Home"}
																		iconSelection={"chevron-down"}
																		id={"E3jhb_p3i"}
																		layoutId={"E3jhb_p3i"}
																		mirrored={false}
																		selectByList={true}
																		style={{
																			height: "100%",
																			width: "100%",
																		}}
																		width={"100%"}
																	/>
																</SmartComponentScopedContainer>
															</ComponentViewportProvider2>
															<ComponentViewportProvider2>
																<SmartComponentScopedContainer
																	className={"framer-18bzxfc-container"}
																	isAuthoredByUser={true}
																	isModuleExternal={true}
																	layoutDependency={layoutDependency}
																	layoutId={"CIjSTBEbu-container"}
																	nodeId={"CIjSTBEbu"}
																	rendersWithMotion={true}
																	scopeId={"jQVnz9gLU"}
																>
																	<Icon
																		color={
																			"var(--token-0bd91f44-2ee2-49df-bd1a-78a1b1ec8984, rgb(175, 175, 175))"
																		}
																		height={"100%"}
																		iconSearch={"Home"}
																		iconSelection={"chevron-down"}
																		id={"CIjSTBEbu"}
																		layoutId={"CIjSTBEbu"}
																		mirrored={false}
																		selectByList={true}
																		style={{
																			height: "100%",
																			width: "100%",
																		}}
																		width={"100%"}
																	/>
																</SmartComponentScopedContainer>
															</ComponentViewportProvider2>
														</motion2.div>
														<AnimatePresence>
															{overlay.visible && (
																<Floating
																	alignment={"start"}
																	anchorRef={ref1}
																	className={cx2(scopingClassNames, classNames)}
																	collisionDetection={true}
																	collisionDetectionPadding={0}
																	data-framer-portal-id={`${layoutId}-1n6vi3v`}
																	offsetX={-28}
																	offsetY={32}
																	onDismiss={overlay.hide}
																	placement={"bottom"}
																	safeArea={true}
																	zIndex={11}
																>
																	<MotionDivWithFX
																		__perspectiveFX={false}
																		__smartComponentFX={true}
																		__targetOpacity={1}
																		animate={animation1}
																		className={"framer-iwqelf"}
																		exit={animation}
																		initial={animation2}
																		layoutDependency={layoutDependency}
																		layoutId={"btzRGGYKv"}
																		ref={ref2}
																		role={"dialog"}
																		style={{
																			background:
																				"linear-gradient(180deg, var(--token-4d6fb0aa-347b-4d07-918a-f12b70b08ad3, rgb(33, 33, 33)) 0%, rgba(33, 33, 33, 0.4) 100%)",
																			borderBottomLeftRadius: 16,
																			borderBottomRightRadius: 16,
																			borderTopLeftRadius: 16,
																			borderTopRightRadius: 16,
																			boxShadow:
																				"0px 10px 20px 0px rgba(0, 0, 0, 0.05)",
																		}}
																	>
																		<motion2.div
																			className={"framer-1y132tz"}
																			data-framer-name={"Card"}
																			layoutDependency={layoutDependency}
																			layoutId={"KIdeLv78u"}
																			style={{
																				backgroundColor:
																					"var(--token-c311f7eb-2396-4f7f-8edd-f790b3c42ec3, rgb(5, 5, 5))",
																				borderBottomLeftRadius: 16,
																				borderBottomRightRadius: 16,
																				borderTopLeftRadius: 16,
																				borderTopRightRadius: 16,
																			}}
																		>
																			<RichText2
																				__fromCanvasComponent={true}
																				className={"framer-827h2v"}
																				fonts={["FS;Manrope-regular"]}
																				layoutDependency={layoutDependency}
																				layoutId={"VEpOhb6Zy"}
																				style={{
																					"--extracted-r6o4lv":
																						"var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, rgb(133, 133, 133))",
																					"--framer-paragraph-spacing": "0px",
																				}}
																				verticalAlignment={"top"}
																				withExternalLayout={true}
																				{...addPropertyOverrides2(
																					{
																						mGrDyrpZD: {
																							children: (
																								<React2.Fragment>
																									<motion2.p
																										style={{
																											"--font-selector":
																												"RlM7TWFucm9wZS1yZWd1bGFy",
																											"--framer-font-family":
																												'"Manrope", "Manrope Placeholder", sans-serif',
																											"--framer-line-height":
																												"1.375em",
																											"--framer-text-color":
																												"var(--extracted-r6o4lv, var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, rgb(133, 133, 133)))",
																										}}
																									>
																										<Link2
																											href={{
																												webPageId: "augiA20Il",
																											}}
																											motionChild={true}
																											nodeId={"VEpOhb6Zy"}
																											openInNewTab={false}
																											scopeId={"jQVnz9gLU"}
																											smoothScroll={false}
																										>
																											<motion2.a
																												className={
																													"framer-styles-preset-rzeatr"
																												}
																												data-styles-preset={
																													"NUFyQ_G3b"
																												}
																											>
																												{"Homepage"}
																											</motion2.a>
																										</Link2>
																									</motion2.p>
																								</React2.Fragment>
																							),
																						},
																					},
																					baseVariant,
																					gestureVariant,
																				)}
																			>
																				<React2.Fragment>
																					<motion2.p
																						style={{
																							"--font-selector":
																								"RlM7TWFucm9wZS1yZWd1bGFy",
																							"--framer-font-family":
																								'"Manrope", "Manrope Placeholder", sans-serif',
																							"--framer-line-height": "1.375em",
																							"--framer-text-color":
																								"var(--extracted-r6o4lv, var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, rgb(133, 133, 133)))",
																						}}
																					>
																						<Link2
																							href={{
																								webPageId: "O9HKScYjf",
																							}}
																							motionChild={true}
																							nodeId={"VEpOhb6Zy"}
																							openInNewTab={false}
																							scopeId={"jQVnz9gLU"}
																							smoothScroll={false}
																						>
																							<motion2.a
																								className={
																									"framer-styles-preset-rzeatr"
																								}
																								data-styles-preset={"NUFyQ_G3b"}
																							>
																								{"Contact"}
																							</motion2.a>
																						</Link2>
																					</motion2.p>
																				</React2.Fragment>
																			</RichText2>
																			<RichText2
																				__fromCanvasComponent={true}
																				className={"framer-1u4aobl"}
																				fonts={["FS;Manrope-regular"]}
																				layoutDependency={layoutDependency}
																				layoutId={"ruU9v8J5W"}
																				style={{
																					"--extracted-r6o4lv":
																						"var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, rgb(133, 133, 133))",
																					"--framer-paragraph-spacing": "0px",
																				}}
																				verticalAlignment={"top"}
																				withExternalLayout={true}
																			>
																				<React2.Fragment>
																					<motion2.p
																						style={{
																							"--font-selector":
																								"RlM7TWFucm9wZS1yZWd1bGFy",
																							"--framer-font-family":
																								'"Manrope", "Manrope Placeholder", sans-serif',
																							"--framer-line-height": "1.375em",
																							"--framer-text-color":
																								"var(--extracted-r6o4lv, var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, rgb(133, 133, 133)))",
																						}}
																					>
																						<Link2
																							href={{
																								webPageId: "y5dAOCV3n",
																							}}
																							motionChild={true}
																							nodeId={"ruU9v8J5W"}
																							openInNewTab={false}
																							scopeId={"jQVnz9gLU"}
																							smoothScroll={false}
																						>
																							<motion2.a
																								className={
																									"framer-styles-preset-rzeatr"
																								}
																								data-styles-preset={"NUFyQ_G3b"}
																							>
																								{"Term & Conditions"}
																							</motion2.a>
																						</Link2>
																					</motion2.p>
																				</React2.Fragment>
																			</RichText2>
																			<RichText2
																				__fromCanvasComponent={true}
																				className={"framer-hvc6qx"}
																				fonts={["FS;Manrope-regular"]}
																				layoutDependency={layoutDependency}
																				layoutId={"OFj5a3yci"}
																				style={{
																					"--extracted-r6o4lv":
																						"var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, rgb(133, 133, 133))",
																					"--framer-paragraph-spacing": "0px",
																				}}
																				verticalAlignment={"top"}
																				withExternalLayout={true}
																			>
																				<React2.Fragment>
																					<motion2.p
																						style={{
																							"--font-selector":
																								"RlM7TWFucm9wZS1yZWd1bGFy",
																							"--framer-font-family":
																								'"Manrope", "Manrope Placeholder", sans-serif',
																							"--framer-line-height": "1.375em",
																							"--framer-text-color":
																								"var(--extracted-r6o4lv, var(--token-af2f9c5a-7d1a-4f00-8c29-d477b6a07b93, rgb(133, 133, 133)))",
																						}}
																					>
																						<Link2
																							href={{
																								webPageId: "qX2wLzlJu",
																							}}
																							motionChild={true}
																							nodeId={"OFj5a3yci"}
																							openInNewTab={false}
																							scopeId={"jQVnz9gLU"}
																							smoothScroll={false}
																						>
																							<motion2.a
																								className={
																									"framer-styles-preset-rzeatr"
																								}
																								data-styles-preset={"NUFyQ_G3b"}
																							>
																								{"404"}
																							</motion2.a>
																						</Link2>
																					</motion2.p>
																				</React2.Fragment>
																			</RichText2>
																		</motion2.div>
																	</MotionDivWithFX>
																</Floating>
															)}
														</AnimatePresence>
													</motion2.div>
												</_Fragment>
											)}
										</Overlay>
									)}
								</motion2.div>
							)}
							{isDisplayed2() && (
								<ResolveLinks
									links={[
										{
											href: {
												webPageId: "O9HKScYjf",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "O9HKScYjf",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "O9HKScYjf",
											},
											implicitPathVariables: void 0,
										},
									]}
								>
									{(resolvedLinks) => (
										<ComponentViewportProvider2
											height={38}
											y={
												(componentViewport?.y || 0) +
												(1 + ((componentViewport?.height || 66) - 2 - 64) / 2) +
												13
											}
											{...addPropertyOverrides2(
												{
													mGrDyrpZD: {
														y:
															(componentViewport?.y || 0) +
															(1 +
																((componentViewport?.height || 200) - 2 - 64) /
																	2) +
															13,
													},
													tcJ_hCqgV: {
														width: `calc(${componentViewport?.width || "100vw"} - 62px)`,
														y: (componentViewport?.y || 0) + 1 + 0 + 8 + 403,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												className={"framer-hd6542-container"}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"oMiAfZpTH-container"}
												nodeId={"oMiAfZpTH"}
												rendersWithMotion={true}
												scopeId={"jQVnz9gLU"}
											>
												{_jsx2(stdin_default, {
													GS3bSUXSK: resolvedLinks[0],
													height: "100%",
													id: "oMiAfZpTH",
													layoutId: "oMiAfZpTH",
													ofLqZhEO8: "Let's Talk",
													variant: "uaQcaqsJ0",
													width: "100%",
													...addPropertyOverrides2(
														{
															mGrDyrpZD: {
																GS3bSUXSK: resolvedLinks[1],
															},
															tcJ_hCqgV: {
																GS3bSUXSK: resolvedLinks[2],
																style: {
																	width: "100%",
																},
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider2>
									)}
								</ResolveLinks>
							)}
						</motion2.div>
					</motion2.nav>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-waF1d.framer-g8yi6i, .framer-waF1d .framer-g8yi6i { display: block; }",
	".framer-waF1d.framer-ab3g4n { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 1px; position: relative; width: 854px; will-change: var(--framer-will-change-override, transform); }",
	".framer-waF1d .framer-tszrmk { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 13px 46px 13px 46px; position: relative; width: 1px; }",
	".framer-waF1d .framer-1ua4du { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-waF1d .framer-1obtxts { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-waF1d .framer-1d70se8 { aspect-ratio: 3.466666666666667 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 30px); overflow: visible; position: relative; text-decoration: none; width: 104px; }",
	".framer-waF1d .framer-15y5mbu { cursor: pointer; flex: none; height: 40px; overflow: hidden; position: relative; width: 40px; }",
	".framer-waF1d .framer-1y4vygg { flex: none; height: 2px; left: calc(50.00000000000002% - 20px / 2); overflow: hidden; position: absolute; top: calc(62.50000000000002% - 2px / 2); width: 20px; will-change: var(--framer-will-change-override, transform); }",
	".framer-waF1d .framer-4cjbyc { flex: none; height: 2px; left: calc(50.00000000000002% - 20px / 2); overflow: hidden; position: absolute; top: calc(37.50000000000002% - 2px / 2); width: 20px; will-change: var(--framer-will-change-override, transform); }",
	".framer-waF1d .framer-npnllj { flex: none; height: 1px; overflow: hidden; position: relative; width: 254px; }",
	".framer-waF1d .framer-1pxc86g { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 18px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-waF1d .framer-ptoe3c, .framer-waF1d .framer-1wknjal, .framer-waF1d .framer-xw0tam, .framer-waF1d .framer-1o70b7k, .framer-waF1d .framer-12iptw6, .framer-waF1d .framer-1iogn3o, .framer-waF1d .framer-ztfff6, .framer-waF1d .framer-827h2v, .framer-waF1d .framer-1u4aobl, .framer-waF1d .framer-hvc6qx { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-waF1d .framer-1n6vi3v { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 5px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-waF1d .framer-iusfhp { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-waF1d .framer-xv4iny { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 20px); justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 20px; }",
	".framer-waF1d .framer-7oxje0-container { flex: none; height: 20px; position: absolute; right: 0px; top: 0px; width: 20px; }",
	".framer-waF1d .framer-18bzxfc-container { bottom: -24px; flex: none; height: 20px; left: -24px; position: absolute; width: 20px; }",
	".framer-waF1d .framer-iwqelf { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 1px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-waF1d .framer-1y132tz { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 18px; height: min-content; justify-content: center; min-width: 230px; overflow: visible; padding: 28px; position: relative; width: min-content; }",
	".framer-waF1d .framer-hd6542-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-waF1d.framer-v-6rgoo .framer-tszrmk { padding: 13px 30px 13px 30px; }",
	".framer-waF1d.framer-v-sa6n7b.framer-ab3g4n { flex-direction: column; gap: 0px; width: 390px; }",
	".framer-waF1d.framer-v-sa6n7b .framer-tszrmk { flex: none; padding: 8px 30px 8px 30px; width: 100%; }",
	".framer-waF1d.framer-v-sa6n7b .framer-1ua4du { flex: 1 0 0px; width: 1px; }",
	".framer-waF1d.framer-v-sa6n7b .framer-1obtxts { gap: unset; justify-content: space-between; width: 100%; }",
	".framer-waF1d.framer-v-sa6n7b .framer-1d70se8, .framer-waF1d.framer-v-1a9g4rk .framer-1d70se8 { height: var(--framer-aspect-ratio-supported, 26px); width: 90px; }",
	".framer-waF1d.framer-v-sa6n7b .framer-1y4vygg, .framer-waF1d.framer-v-sa6n7b .framer-4cjbyc { left: calc(65.00000000000003% - 20px / 2); }",
	".framer-waF1d.framer-v-1a9g4rk.framer-ab3g4n { flex-direction: column; gap: 0px; max-height: calc(var(--framer-viewport-height, 100vh) * 1); width: 390px; }",
	".framer-waF1d.framer-v-1a9g4rk .framer-tszrmk { flex: none; flex-direction: column; gap: 32px; justify-content: flex-start; padding: 8px 30px 40px 30px; width: 100%; }",
	".framer-waF1d.framer-v-1a9g4rk .framer-1ua4du { gap: 12px; order: 0; width: 100%; }",
	".framer-waF1d.framer-v-1a9g4rk .framer-1obtxts { cursor: pointer; gap: unset; justify-content: space-between; width: 100%; }",
	".framer-waF1d.framer-v-1a9g4rk .framer-1y4vygg, .framer-waF1d.framer-v-1a9g4rk .framer-4cjbyc { left: calc(63.636363636363654% - 20px / 2); top: calc(50.00000000000002% - 2px / 2); }",
	".framer-waF1d.framer-v-1a9g4rk .framer-1pxc86g { flex-direction: column; gap: 22px; order: 1; width: 100%; }",
	".framer-waF1d.framer-v-1a9g4rk .framer-hd6542-container { order: 2; width: 100%; }",
	...css,
];
var FramerjQVnz9gLU = withCSS2(Component2, css4, "framer-waF1d");
var stdin_default2 = FramerjQVnz9gLU;
FramerjQVnz9gLU.displayName = "Section/Navigation 2";
FramerjQVnz9gLU.defaultProps = {
	height: 66,
	width: 854,
};
addPropertyControls2(FramerjQVnz9gLU, {
	variant: {
		options: ["Ox5wM8MTA", "mGrDyrpZD", "NYTQVxxd6", "tcJ_hCqgV"],
		optionTitles: ["Desktop", "Tablet", "Phone", "Phone Open"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts2(
	FramerjQVnz9gLU,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Manrope",
					source: "fontshare",
					style: "normal",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/2TYFCBHUANEXS6QGR5EQDUNAFH6LSWM3/AYNOU3VEA4LRTDNKJQUFNVNUTYSGOUOP/UXO4O7K2G3HI3D2VKD7UXVJVJD26P4BQ.woff2",
					weight: "400",
				},
			],
		},
		...FeatherFonts2,
		...ButtonRunningStrokeFonts,
		...getFontsFromSharedStyle2(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:section/navigation-2
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "NYTQVxxd6",
	md: "mGrDyrpZD",
	xl: "Ox5wM8MTA",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a6e0de7208a6e203a13a02c0c2342fdcb8c3548bcbc64ba40bb03307875e0fbf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders Navigation2FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a6e0de7208a6e203a13a02c0c2342fdcb8c3548bcbc64ba40bb03307875e0fbf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var navigation_2_default = ComponentWithRoot;
export { navigation_2_default as default };
