// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project a6e0de7208a6e203 "VeeBran", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' | 'Phone Open' // Variant
}} Props

 */
import { stdin_default } from "../chunks/chunk-I5JQW4T6.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "../chunks/chunk-ONDWJXSP.js";
import { className, css, fonts } from "../chunks/chunk-FKIQ7FXH.js";
import { Icon } from "../chunks/chunk-66EJKQKM.js";
import "../chunks/chunk-NULYBL27.js";
import { routes } from "../chunks/chunk-ID6ACFOJ.js";

// virtual:section/navigation
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/fgzuVvhMB4PbjEuONYnW/d2tSxh3cyeQv6b014yns/rUnEG13ed.js
import {
	jsx as _jsx,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	Floating,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOverlayState,
	useRouter,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import {
	AnimatePresence,
	LayoutGroup,
	motion,
	MotionConfigContext,
} from "unframer";
import * as React from "react";
import { useRef as useRef2 } from "react";
var RichTextWithFX = withFX(RichText);
var MotionDivWithFX = withFX(motion.div);
var FeatherFonts = getFonts(Icon);
var ButtonRunningStrokeFonts = getFonts(stdin_default);
var cycleOrder = ["EETSdeJhy", "rlsa9jKwo", "D2WlhEE0c", "mTNdKI81R"];
var serializationHash = "framer-KQubB";
var variantClassNames = {
	D2WlhEE0c: "framer-v-15038og",
	EETSdeJhy: "framer-v-17qoqm7",
	mTNdKI81R: "framer-v-k12gva",
	rlsa9jKwo: "framer-v-r827dn",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 40,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition2 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation2 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var Overlay = ({ children, blockDocumentScrolling, enabled = true }) => {
	const [visible, setVisible] = useOverlayState({
		blockDocumentScrolling,
	});
	return children({
		hide: () => setVisible(false),
		show: () => setVisible(true),
		toggle: () => setVisible(!visible),
		visible: enabled && visible,
	});
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Phone Open": "mTNdKI81R",
	Desktop: "EETSdeJhy",
	Phone: "D2WlhEE0c",
	Tablet: "rlsa9jKwo",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "EETSdeJhy",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "EETSdeJhy",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1agf7tv = activeVariantCallback(async (...args) => {
		setVariant("D2WlhEE0c");
	});
	const onTapbu7deh = activeVariantCallback(async (...args) => {
		setVariant("mTNdKI81R");
	});
	const onMouseEntertxyyif = ({ overlay, loadMore }) =>
		activeVariantCallback(async (...args) => {
			overlay.show();
		});
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["D2WlhEE0c", "mTNdKI81R"].includes(baseVariant)) return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "mTNdKI81R") return true;
		return false;
	};
	const isDisplayed2 = () => {
		if (baseVariant === "D2WlhEE0c") return false;
		return true;
	};
	const isDisplayed3 = () => {
		if (baseVariant === "mTNdKI81R") return false;
		return true;
	};
	const ref1 = React.useRef(null);
	const ref2 = React.useRef(null);
	const router = useRouter();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.nav
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-17qoqm7",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"EETSdeJhy"}
						ref={refBinding}
						style={{
							background:
								"linear-gradient(180deg, var(--token-4d6fb0aa-347b-4d07-918a-f12b70b08ad3, rgb(33, 33, 33)) 0%, rgba(33, 33, 33, 0.4) 100%)",
							borderBottomLeftRadius: 40,
							borderBottomRightRadius: 40,
							borderTopLeftRadius: 40,
							borderTopRightRadius: 40,
							...style,
						}}
						variants={{
							mTNdKI81R: {
								borderBottomLeftRadius: 24,
								borderBottomRightRadius: 24,
								borderTopLeftRadius: 24,
								borderTopRightRadius: 24,
							},
						}}
						{...addPropertyOverrides(
							{
								D2WlhEE0c: {
									"data-framer-name": "Phone",
								},
								mTNdKI81R: {
									"data-framer-name": "Phone Open",
								},
								rlsa9jKwo: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-3loh76"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"DM7MutwLp"}
							style={{
								backgroundColor:
									"var(--token-c311f7eb-2396-4f7f-8edd-f790b3c42ec3, rgb(5, 5, 5))",
								borderBottomLeftRadius: 40,
								borderBottomRightRadius: 40,
								borderTopLeftRadius: 40,
								borderTopRightRadius: 40,
							}}
							variants={{
								mTNdKI81R: {
									borderBottomLeftRadius: 23,
									borderBottomRightRadius: 23,
									borderTopLeftRadius: 23,
									borderTopRightRadius: 23,
								},
							}}
						>
							<motion.div
								className={"framer-1lzel8l"}
								data-framer-name={"Wrapper"}
								layoutDependency={layoutDependency}
								layoutId={"TK_Zl2WB1"}
							>
								<motion.div
									className={"framer-1b0mbde"}
									data-framer-name={"Top"}
									layoutDependency={layoutDependency}
									layoutId={"J5WlE5YAf"}
									{...addPropertyOverrides(
										{
											mTNdKI81R: {
												"data-highlight": true,
												onTap: onTap1agf7tv,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<Link
										href={{
											webPageId: "",
										}}
										motionChild={true}
										nodeId={"S0Q5IQHtQ"}
										scopeId={"rUnEG13ed"}
									>
										<Image
											aria-label={"brand-name"}
											as={"a"}
											background={{
												alt: "",
												fit: "fit",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
													(1 +
														((componentViewport?.height || 200) - 2 - 64) /
														2) +
													17 +
													0 +
													0 +
													0,
												),
												pixelHeight: 1695,
												pixelWidth: 7801,
												positionX: "left",
												positionY: "center",
												sizes: "104px",
												src: "/VB1.png", srcSet: "",
											}}
											className={"framer-1xrbt6z framer-13l2shf"}
											data-framer-name={"Logo"}
											layoutDependency={layoutDependency}
											layoutId={"S0Q5IQHtQ"}
											{...addPropertyOverrides(
												{
													D2WlhEE0c: {
														background: {
															alt: "",
															fit: "fit",
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																1 +
																0 +
																8 +
																0 +
																0 +
																7.0193,
															),
															pixelHeight: 1695,
															pixelWidth: 7801,
															positionX: "left",
															positionY: "center",
															sizes: "90px",
															src: "/VB1.png", srcSet: "",
														},
													},
													mTNdKI81R: {
														background: {
															alt: "",
															fit: "fit",
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																1 +
																0 +
																8 +
																0 +
																0 +
																0 +
																7.0193,
															),
															pixelHeight: 1695,
															pixelWidth: 7801,
															positionX: "left",
															positionY: "center",
															sizes: "90px",
															src: "/VB1.png", srcSet: "",
														},
													},
													rlsa9jKwo: {
														background: {
															alt: "",
															fit: "fit",
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																(1 +
																	((componentViewport?.height || 66) -
																		2 -
																		64) /
																	2) +
																17 +
																0 +
																0 +
																0,
															),
															pixelHeight: 1695,
															pixelWidth: 7801,
															positionX: "left",
															positionY: "center",
															sizes: "104px",
															src: "/VB1.png", srcSet: "",
														},
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
									</Link>
									{isDisplayed() && (
										<motion.div
											className={"framer-1sxaplr"}
											data-framer-name={"Icon"}
											data-highlight={true}
											layoutDependency={layoutDependency}
											layoutId={"fmg34vUAc"}
											onTap={onTapbu7deh}
										>
											<motion.div
												className={"framer-hmusal"}
												data-framer-name={"Bottom"}
												layoutDependency={layoutDependency}
												layoutId={"sSF5cFgAz"}
												style={{
													backgroundColor: "rgb(153, 153, 153)",
													borderBottomLeftRadius: 10,
													borderBottomRightRadius: 10,
													borderTopLeftRadius: 10,
													borderTopRightRadius: 10,
													rotate: 0,
												}}
												variants={{
													mTNdKI81R: {
														rotate: -45,
													},
												}}
											/>
											<motion.div
												className={"framer-11onw9j"}
												data-framer-name={"Top"}
												layoutDependency={layoutDependency}
												layoutId={"TPHY0aDs0"}
												style={{
													backgroundColor: "rgb(153, 153, 153)",
													borderBottomLeftRadius: 10,
													borderBottomRightRadius: 10,
													borderTopLeftRadius: 10,
													borderTopRightRadius: 10,
													rotate: 0,
												}}
												variants={{
													mTNdKI81R: {
														rotate: 45,
													},
												}}
											/>
										</motion.div>
									)}
								</motion.div>
								{isDisplayed1() && (
									<motion.div
										className={"framer-1lt1rey"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"Q_IDaIykr"}
										style={{
											background:
												"linear-gradient(90deg, rgba(61, 61, 61, 0) 0%, var(--token-4d6fb0aa-347b-4d07-918a-f12b70b08ad3, rgb(33, 33, 33)) 25%, var(--token-4d6fb0aa-347b-4d07-918a-f12b70b08ad3, rgb(33, 33, 33)) 75%, rgba(0, 80, 138, 0) 100%)",
										}}
									/>
								)}
							</motion.div>
							{isDisplayed2() && (
								<motion.div
									className={"framer-zm3fw4"}
									data-framer-name={"Links"}
									layoutDependency={layoutDependency}
									layoutId={"A9wOk1k61"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1njec72"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"J7xtR1deG"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-180noy4"}
												data-styles-preset={"SdN8D7okU"}
											>
												<Link
													href={{
														hash: ":uTrHOqYco",
														webPageId: "",
													}}
													motionChild={true}
													nodeId={"J7xtR1deG"}
													openInNewTab={false}
													scopeId={"rUnEG13ed"}
													smoothScroll={true}
												>
													<motion.a
														className={"framer-styles-preset-rzeatr"}
														data-styles-preset={"NUFyQ_G3b"}
													>
														{"Why Us"}
													</motion.a>
												</Link>
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-5vjhqe"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"YKqG_12ls"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-180noy4"}
												data-styles-preset={"SdN8D7okU"}
											>
												<Link
													href={{
														hash: ":eCxvIfBt6",
														webPageId: "",
													}}
													motionChild={true}
													nodeId={"YKqG_12ls"}
													openInNewTab={false}
													scopeId={"rUnEG13ed"}
													smoothScroll={true}
												>
													<motion.a
														className={"framer-styles-preset-rzeatr"}
														data-styles-preset={"NUFyQ_G3b"}
													>
														{"Mission"}
													</motion.a>
												</Link>
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-59da0g"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"XXruA7Ia0"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-180noy4"}
												data-styles-preset={"SdN8D7okU"}
											>
												<Link
													href={{
														hash: ":a8kgD6gFC",
														webPageId: "",
													}}
													motionChild={true}
													nodeId={"XXruA7Ia0"}
													openInNewTab={false}
													scopeId={"rUnEG13ed"}
													smoothScroll={true}
												>
													<motion.a
														className={"framer-styles-preset-rzeatr"}
														data-styles-preset={"NUFyQ_G3b"}
													>
														{"Works"}
													</motion.a>
												</Link>
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1blcc3c"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"Iocyglbjf"}
										style={{
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-180noy4"}
												data-styles-preset={"SdN8D7okU"}
											>
												<Link
													href={{
														hash: ":ACBgSFIb5",
														webPageId: "",
													}}
													motionChild={true}
													nodeId={"Iocyglbjf"}
													openInNewTab={false}
													scopeId={"rUnEG13ed"}
													smoothScroll={true}
												>
													<motion.a
														className={"framer-styles-preset-rzeatr"}
														data-styles-preset={"NUFyQ_G3b"}
													>
														{"Services"}
													</motion.a>
												</Link>
											</motion.p>
										</React.Fragment>
									</RichText>
									{isDisplayed1() && (
										<RichText
											__fromCanvasComponent={true}
											className={"framer-mdc85b"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"o49qQn8Ov"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-180noy4"}
													data-styles-preset={"SdN8D7okU"}
												>
													<Link
														href={{
															webPageId: "O9HKScYjf",
														}}
														motionChild={true}
														nodeId={"o49qQn8Ov"}
														openInNewTab={false}
														scopeId={"rUnEG13ed"}
														smoothScroll={false}
													>
														<motion.a
															className={"framer-styles-preset-rzeatr"}
															data-styles-preset={"NUFyQ_G3b"}
														>
															{"Contact"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
									)}
									{isDisplayed3() && (
										<Overlay blockDocumentScrolling={false}>
											{(overlay) => (
												<_Fragment>
													<motion.div
														className={"framer-1agl9qa"}
														data-framer-name={"Button/Button"}
														data-highlight={true}
														id={`${layoutId}-1agl9qa`}
														layoutDependency={layoutDependency}
														layoutId={"IBswFWDu5"}
														onMouseEnter={onMouseEntertxyyif({
															overlay,
														})}
														ref={ref1}
														style={{
															background:
																"radial-gradient(50% 50% at 50% 50%, var(--token-ca0eb946-0278-4b5f-be23-d71665cd022d, rgba(17, 17, 17, 0)) 0%, var(--token-ca0eb946-0278-4b5f-be23-d71665cd022d, rgba(17, 17, 17, 0)) 100%)",
															borderBottomLeftRadius: 7,
															borderBottomRightRadius: 7,
															borderTopLeftRadius: 7,
															borderTopRightRadius: 7,
														}}
													>
														<RichTextWithFX
															__framer__animate={{
																transition: transition2,
															}}
															__framer__animateOnce={false}
															__framer__enter={animation}
															__framer__exit={animation1}
															__framer__styleAppearEffectEnabled={true}
															__framer__threshold={0.5}
															__fromCanvasComponent={true}
															__perspectiveFX={false}
															__smartComponentFX={true}
															__targetOpacity={1}
															className={"framer-uofmhd"}
															data-framer-name={"Pages"}
															fonts={["Inter"]}
															layoutDependency={layoutDependency}
															layoutId={"njcZJgOCk"}
															style={{
																"--extracted-r6o4lv":
																	"var(--token-0bd91f44-2ee2-49df-bd1a-78a1b1ec8984, rgb(175, 175, 175))",
																"--framer-link-text-color": "rgb(0, 153, 255)",
																"--framer-link-text-decoration": "underline",
															}}
															verticalAlignment={"top"}
															withExternalLayout={true}
														>
															<React.Fragment>
																<motion.p
																	className={"framer-styles-preset-180noy4"}
																	data-styles-preset={"SdN8D7okU"}
																	style={{
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, var(--token-0bd91f44-2ee2-49df-bd1a-78a1b1ec8984, rgb(175, 175, 175)))",
																	}}
																>
																	{"Contact Us"}
																</motion.p>
															</React.Fragment>
														</RichTextWithFX>
														<AnimatePresence>
															{overlay.visible && (
																<Floating
																	alignment={"start"}
																	anchorRef={ref1}
																	className={cx(scopingClassNames, classNames)}
																	collisionDetection={true}
																	collisionDetectionPadding={0}
																	data-framer-portal-id={`${layoutId}-1agl9qa`}
																	offsetX={-28}
																	offsetY={32}
																	onDismiss={overlay.hide}
																	placement={"bottom"}
																	safeArea={true}
																	zIndex={11}
																>
																	<MotionDivWithFX
																		__perspectiveFX={false}
																		__smartComponentFX={true}
																		__targetOpacity={1}
																		animate={animation2}
																		className={"framer-1w5dxxq"}
																		exit={animation1}
																		initial={animation}
																		layoutDependency={layoutDependency}
																		layoutId={"UAJWg_Jof"}
																		ref={ref2}
																		role={"dialog"}
																		style={{
																			background:
																				"linear-gradient(180deg, var(--token-4d6fb0aa-347b-4d07-918a-f12b70b08ad3, rgb(33, 33, 33)) 0%, rgba(33, 33, 33, 0.4) 100%)",
																			borderBottomLeftRadius: 16,
																			borderBottomRightRadius: 16,
																			borderTopLeftRadius: 16,
																			borderTopRightRadius: 16,
																			boxShadow:
																				"0px 10px 20px 0px rgba(0, 0, 0, 0.05)",
																		}}
																	>
																		<motion.div
																			className={"framer-17a4np5"}
																			data-framer-name={"Card"}
																			layoutDependency={layoutDependency}
																			layoutId={"l9UyD39UD"}
																			style={{
																				backgroundColor:
																					"var(--token-c311f7eb-2396-4f7f-8edd-f790b3c42ec3, rgb(5, 5, 5))",
																				borderBottomLeftRadius: 16,
																				borderBottomRightRadius: 16,
																				borderTopLeftRadius: 16,
																				borderTopRightRadius: 16,
																			}}
																		>
																			<RichText
																				__fromCanvasComponent={true}
																				className={"framer-vyxcef"}
																				data-framer-name={"Contact"}
																				fonts={["Inter"]}
																				layoutDependency={layoutDependency}
																				layoutId={"R5adD0A4d"}
																				style={{
																					"--framer-paragraph-spacing": "0px",
																				}}
																				verticalAlignment={"top"}
																				withExternalLayout={true}
																			>
																				<React.Fragment>
																					<motion.p
																						className={
																							"framer-styles-preset-180noy4"
																						}
																						data-styles-preset={"SdN8D7okU"}
																					>
																						<Link
																							href={{
																								webPageId: "O9HKScYjf",
																							}}
																							motionChild={true}
																							nodeId={"R5adD0A4d"}
																							openInNewTab={false}
																							scopeId={"rUnEG13ed"}
																							smoothScroll={false}
																						>
																							<motion.a
																								className={
																									"framer-styles-preset-rzeatr"
																								}
																								data-styles-preset={"NUFyQ_G3b"}
																							>
																								{"Contact"}
																							</motion.a>
																						</Link>
																					</motion.p>
																				</React.Fragment>
																			</RichText>
																			<RichText
																				__fromCanvasComponent={true}
																				className={"framer-m4ah1c"}
																				fonts={["Inter"]}
																				layoutDependency={layoutDependency}
																				layoutId={"Zoq2qv_Ui"}
																				style={{
																					"--framer-paragraph-spacing": "0px",
																				}}
																				verticalAlignment={"top"}
																				withExternalLayout={true}
																			>
																				<React.Fragment>
																					<motion.p
																						className={
																							"framer-styles-preset-180noy4"
																						}
																						data-styles-preset={"SdN8D7okU"}
																					>
																						<Link
																							href={{
																								webPageId: "Po_UhMe4P",
																							}}
																							motionChild={true}
																							nodeId={"Zoq2qv_Ui"}
																							openInNewTab={false}
																							scopeId={"rUnEG13ed"}
																							smoothScroll={false}
																						>
																							<motion.a
																								className={
																									"framer-styles-preset-rzeatr"
																								}
																								data-styles-preset={"NUFyQ_G3b"}
																							>
																								{"Term & Conditions"}
																							</motion.a>
																						</Link>
																					</motion.p>
																				</React.Fragment>
																			</RichText>
																		</motion.div>
																	</MotionDivWithFX>
																</Floating>
															)}
														</AnimatePresence>
														<motion.div
															className={"framer-1g2ansa"}
															data-framer-name={"Icon Flip"}
															layoutDependency={layoutDependency}
															layoutId={"cPIpaxBEI"}
														>
															<ComponentViewportProvider>
																<SmartComponentScopedContainer
																	className={"framer-1s70c8o-container"}
																	isAuthoredByUser={true}
																	isModuleExternal={true}
																	layoutDependency={layoutDependency}
																	layoutId={"rlIhGcEgr-container"}
																	nodeId={"rlIhGcEgr"}
																	rendersWithMotion={true}
																	scopeId={"rUnEG13ed"}
																>
																	<Icon
																		color={
																			"var(--token-0bd91f44-2ee2-49df-bd1a-78a1b1ec8984, rgb(175, 175, 175))"
																		}
																		height={"100%"}
																		iconSearch={"Home"}
																		iconSelection={"chevron-down"}
																		id={"rlIhGcEgr"}
																		layoutId={"rlIhGcEgr"}
																		mirrored={false}
																		selectByList={true}
																		style={{
																			height: "100%",
																			width: "100%",
																		}}
																		width={"100%"}
																	/>
																</SmartComponentScopedContainer>
															</ComponentViewportProvider>
															<ComponentViewportProvider>
																<SmartComponentScopedContainer
																	className={"framer-18i6a0m-container"}
																	isAuthoredByUser={true}
																	isModuleExternal={true}
																	layoutDependency={layoutDependency}
																	layoutId={"EY2zAD8Jc-container"}
																	nodeId={"EY2zAD8Jc"}
																	rendersWithMotion={true}
																	scopeId={"rUnEG13ed"}
																>
																	<Icon
																		color={
																			"var(--token-0bd91f44-2ee2-49df-bd1a-78a1b1ec8984, rgb(175, 175, 175))"
																		}
																		height={"100%"}
																		iconSearch={"Home"}
																		iconSelection={"chevron-down"}
																		id={"EY2zAD8Jc"}
																		layoutId={"EY2zAD8Jc"}
																		mirrored={false}
																		selectByList={true}
																		style={{
																			height: "100%",
																			width: "100%",
																		}}
																		width={"100%"}
																	/>
																</SmartComponentScopedContainer>
															</ComponentViewportProvider>
														</motion.div>
													</motion.div>
												</_Fragment>
											)}
										</Overlay>
									)}
								</motion.div>
							)}
							{isDisplayed2() && (
								<ResolveLinks
									links={[
										{
											href: {
												webPageId: "O9HKScYjf",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "O9HKScYjf",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "O9HKScYjf",
											},
											implicitPathVariables: void 0,
										},
									]}
								>
									{(resolvedLinks) => (
										<ComponentViewportProvider
											height={38}
											y={
												(componentViewport?.y || 0) +
												(1 +
													((componentViewport?.height || 200) - 2 - 64) / 2) +
												13
											}
											{...addPropertyOverrides(
												{
													mTNdKI81R: {
														width: `calc(${componentViewport?.width || "100vw"} - 62px)`,
														y: (componentViewport?.y || 0) + 1 + 0 + 8 + 315,
													},
													rlsa9jKwo: {
														y:
															(componentViewport?.y || 0) +
															(1 +
																((componentViewport?.height || 66) - 2 - 64) /
																2) +
															13,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												className={"framer-71xnz7-container"}
												layoutDependency={layoutDependency}
												layoutId={"NDO6D9Vwe-container"}
												nodeId={"NDO6D9Vwe"}
												rendersWithMotion={true}
												scopeId={"rUnEG13ed"}
											>
												{_jsx(stdin_default, {
													GS3bSUXSK: resolvedLinks[0],
													height: "100%",
													id: "NDO6D9Vwe",
													layoutId: "NDO6D9Vwe",
													ofLqZhEO8: "Let's Talk",
													variant: "uaQcaqsJ0",
													width: "100%",
													...addPropertyOverrides(
														{
															mTNdKI81R: {
																GS3bSUXSK: resolvedLinks[2],
																style: {
																	width: "100%",
																},
															},
															rlsa9jKwo: {
																GS3bSUXSK: resolvedLinks[1],
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									)}
								</ResolveLinks>
							)}
						</motion.div>
					</motion.nav>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-KQubB.framer-13l2shf, .framer-KQubB .framer-13l2shf { display: block; }",
	".framer-KQubB.framer-17qoqm7 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 1px; position: relative; width: 854px; will-change: var(--framer-will-change-override, transform); }",
	".framer-KQubB .framer-3loh76 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 13px 46px 13px 46px; position: relative; width: 1px; }",
	".framer-KQubB .framer-1lzel8l { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-KQubB .framer-1b0mbde { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-KQubB .framer-1xrbt6z { aspect-ratio: 3.466666666666667 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 30px); overflow: visible; position: relative; text-decoration: none; width: 104px; }",
	".framer-KQubB .framer-1sxaplr { cursor: pointer; flex: none; height: 40px; overflow: hidden; position: relative; width: 40px; }",
	".framer-KQubB .framer-hmusal { flex: none; height: 2px; left: calc(50.00000000000002% - 20px / 2); overflow: hidden; position: absolute; top: calc(62.50000000000002% - 2px / 2); width: 20px; will-change: var(--framer-will-change-override, transform); }",
	".framer-KQubB .framer-11onw9j { flex: none; height: 2px; left: calc(50.00000000000002% - 20px / 2); overflow: hidden; position: absolute; top: calc(37.50000000000002% - 2px / 2); width: 20px; will-change: var(--framer-will-change-override, transform); }",
	".framer-KQubB .framer-1lt1rey { flex: none; height: 1px; overflow: hidden; position: relative; width: 254px; }",
	".framer-KQubB .framer-zm3fw4 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 18px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-KQubB .framer-1njec72, .framer-KQubB .framer-5vjhqe, .framer-KQubB .framer-59da0g, .framer-KQubB .framer-1blcc3c, .framer-KQubB .framer-mdc85b, .framer-KQubB .framer-vyxcef, .framer-KQubB .framer-m4ah1c { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-KQubB .framer-1agl9qa { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 5px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-KQubB .framer-uofmhd { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-KQubB .framer-1w5dxxq { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 1px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-KQubB .framer-17a4np5 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 18px; height: min-content; justify-content: center; min-width: 230px; overflow: visible; padding: 28px; position: relative; width: min-content; }",
	".framer-KQubB .framer-1g2ansa { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 20px); justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 20px; }",
	".framer-KQubB .framer-1s70c8o-container { flex: none; height: 20px; position: absolute; right: 0px; top: 0px; width: 20px; }",
	".framer-KQubB .framer-18i6a0m-container { bottom: -24px; flex: none; height: 20px; left: -24px; position: absolute; width: 20px; }",
	".framer-KQubB .framer-71xnz7-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-KQubB.framer-v-r827dn .framer-3loh76 { padding: 13px 30px 13px 30px; }",
	".framer-KQubB.framer-v-15038og.framer-17qoqm7 { flex-direction: column; gap: 0px; width: 390px; }",
	".framer-KQubB.framer-v-15038og .framer-3loh76 { flex: none; padding: 8px 30px 8px 30px; width: 100%; }",
	".framer-KQubB.framer-v-15038og .framer-1lzel8l { flex: 1 0 0px; width: 1px; }",
	".framer-KQubB.framer-v-15038og .framer-1b0mbde { gap: unset; justify-content: space-between; width: 100%; }",
	".framer-KQubB.framer-v-15038og .framer-1xrbt6z, .framer-KQubB.framer-v-k12gva .framer-1xrbt6z { height: var(--framer-aspect-ratio-supported, 26px); width: 90px; }",
	".framer-KQubB.framer-v-15038og .framer-hmusal, .framer-KQubB.framer-v-15038og .framer-11onw9j { left: calc(65.00000000000003% - 20px / 2); }",
	".framer-KQubB.framer-v-k12gva.framer-17qoqm7 { flex-direction: column; gap: 0px; max-height: calc(var(--framer-viewport-height, 100vh) * 1); width: 390px; }",
	".framer-KQubB.framer-v-k12gva .framer-3loh76 { flex: none; flex-direction: column; gap: 32px; justify-content: flex-start; padding: 8px 30px 40px 30px; width: 100%; }",
	".framer-KQubB.framer-v-k12gva .framer-1lzel8l { gap: 12px; order: 0; width: 100%; }",
	".framer-KQubB.framer-v-k12gva .framer-1b0mbde { cursor: pointer; gap: unset; justify-content: space-between; width: 100%; }",
	".framer-KQubB.framer-v-k12gva .framer-hmusal, .framer-KQubB.framer-v-k12gva .framer-11onw9j { left: calc(63.636363636363654% - 20px / 2); top: calc(50.00000000000002% - 2px / 2); }",
	".framer-KQubB.framer-v-k12gva .framer-zm3fw4 { flex-direction: column; gap: 22px; order: 1; width: 100%; }",
	".framer-KQubB.framer-v-k12gva .framer-71xnz7-container { order: 2; width: 100%; }",
	...css,
	...css2,
];
var FramerrUnEG13ed = withCSS(Component, css3, "framer-KQubB");
var stdin_default2 = FramerrUnEG13ed;
FramerrUnEG13ed.displayName = "Section/Navigation";
FramerrUnEG13ed.defaultProps = {
	height: 66,
	width: 854,
};
addPropertyControls(FramerrUnEG13ed, {
	variant: {
		options: ["EETSdeJhy", "rlsa9jKwo", "D2WlhEE0c", "mTNdKI81R"],
		optionTitles: ["Desktop", "Tablet", "Phone", "Phone Open"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerrUnEG13ed,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...FeatherFonts,
		...ButtonRunningStrokeFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:section/navigation
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "D2WlhEE0c",
	md: "rlsa9jKwo",
	xl: "EETSdeJhy",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a6e0de7208a6e203a13a02c0c2342fdcb8c3548bcbc64ba40bb03307875e0fbf"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavigationFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a6e0de7208a6e203a13a02c0c2342fdcb8c3548bcbc64ba40bb03307875e0fbf"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var navigation_default = ComponentWithRoot;
export { navigation_default as default };
